// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.mindhunter.g_launcher

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object LauncherApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Why the app list changed. Native pushes the FULL list every time, so this is
 * informational — nothing on the Dart side merges deltas.
 */
enum class AppChangeReason(val raw: Int) {
  ADDED(0),
  REMOVED(1),
  CHANGED(2),
  AVAILABILITY_CHANGED(3);

  companion object {
    fun ofRaw(raw: Int): AppChangeReason? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * The shape an icon is forced into.
 *
 * roundedSquare + a cornerRadius float covers most distros: 0.0 is square,
 * 0.22 the default, 0.5 a circle. squircle and teardrop stay separate because
 * they are genuinely different curves — a rounded rect cannot fake a
 * superellipse, and the eye picks that up across a grid of 40 icons.
 */
enum class IconTreatment(val raw: Int) {
  CIRCLE(0),
  SQUIRCLE(1),
  ROUNDED_SQUARE(2),
  SQUARE(3),
  TEARDROP(4),
  ORIGINAL(5);

  companion object {
    fun ofRaw(raw: Int): IconTreatment? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * One launchable activity, for one user profile.
 *
 * [componentKey] is the stable identity used everywhere: layout rows, icon
 * cache keys, folder membership, usage counts. Format is
 * "packageName/className#userSerial", and it is opaque to Dart — never
 * reconstruct it by hand.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AppEntry (
  val componentKey: String,
  val packageName: String,
  val className: String,
  val userSerial: Long,
  val label: String,
  /**
   * Changes whenever the app is updated or reinstalled. Part of the icon cache
   * key, and that is its ONLY job — it is not a version number. (It used to be
   * called versionCode. It never was one: getting a real version code needs
   * QUERY_ALL_PACKAGES, which we refuse to ship.)
   */
  val updateToken: Long,
  val isWorkProfile: Boolean,
  val isSuspended: Boolean,
  val isSystem: Boolean,
  /**
   * `ApplicationInfo.category` — the manifest's own `android:appCategory`.
   * -1 (CATEGORY_UNDEFINED) when the app declares none, which is most of them,
   * and always -1 below API 26 where the field does not exist.
   *
   * APPENDED, not inserted: field order is the decode index, so adding to the
   * END keeps AppEntry on codec 131 with every existing index unmoved.
   */
  val category: Long,
  /**
   * True when the app is a game. Reads the modern category first, then falls
   * back to the legacy `FLAG_IS_GAME` for apps that predate the category and
   * never set it — a lot of the games actually installed on a budget phone.
   */
  val isGame: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AppEntry {
      val componentKey = pigeonVar_list[0] as String
      val packageName = pigeonVar_list[1] as String
      val className = pigeonVar_list[2] as String
      val userSerial = pigeonVar_list[3] as Long
      val label = pigeonVar_list[4] as String
      val updateToken = pigeonVar_list[5] as Long
      val isWorkProfile = pigeonVar_list[6] as Boolean
      val isSuspended = pigeonVar_list[7] as Boolean
      val isSystem = pigeonVar_list[8] as Boolean
      val category = pigeonVar_list[9] as Long
      val isGame = pigeonVar_list[10] as Boolean
      return AppEntry(componentKey, packageName, className, userSerial, label, updateToken, isWorkProfile, isSuspended, isSystem, category, isGame)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      componentKey,
      packageName,
      className,
      userSerial,
      label,
      updateToken,
      isWorkProfile,
      isSuspended,
      isSystem,
      category,
      isGame,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AppEntry
    return LauncherApiPigeonUtils.deepEquals(this.componentKey, other.componentKey) && LauncherApiPigeonUtils.deepEquals(this.packageName, other.packageName) && LauncherApiPigeonUtils.deepEquals(this.className, other.className) && LauncherApiPigeonUtils.deepEquals(this.userSerial, other.userSerial) && LauncherApiPigeonUtils.deepEquals(this.label, other.label) && LauncherApiPigeonUtils.deepEquals(this.updateToken, other.updateToken) && LauncherApiPigeonUtils.deepEquals(this.isWorkProfile, other.isWorkProfile) && LauncherApiPigeonUtils.deepEquals(this.isSuspended, other.isSuspended) && LauncherApiPigeonUtils.deepEquals(this.isSystem, other.isSystem) && LauncherApiPigeonUtils.deepEquals(this.category, other.category) && LauncherApiPigeonUtils.deepEquals(this.isGame, other.isGame)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.componentKey)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.packageName)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.className)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.userSerial)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.label)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.updateToken)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.isWorkProfile)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.isSuspended)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.isSystem)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.category)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.isGame)
    return result
  }
  override fun toString(): String {
    return "AppEntry(componentKey=$componentKey, packageName=$packageName, className=$className, userSerial=$userSerial, label=$label, updateToken=$updateToken, isWorkProfile=$isWorkProfile, isSuspended=$isSuspended, isSystem=$isSystem, category=$category, isGame=$isGame)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AppChangeEvent (
  val reason: AppChangeReason,
  val apps: List<AppEntry>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AppChangeEvent {
      val reason = pigeonVar_list[0] as AppChangeReason
      val apps = pigeonVar_list[1] as List<AppEntry>
      return AppChangeEvent(reason, apps)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      reason,
      apps,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AppChangeEvent
    return LauncherApiPigeonUtils.deepEquals(this.reason, other.reason) && LauncherApiPigeonUtils.deepEquals(this.apps, other.apps)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.reason)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.apps)
    return result
  }
  override fun toString(): String {
    return "AppChangeEvent(reason=$reason, apps=$apps)"
  }
}

/**
 * The icon half of a ThemeSpec.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class IconStyle (
  val treatment: IconTreatment,
  /**
   * Fraction of icon size, for roundedSquare. 0.0 = square, 0.5 = circle.
   * A float rather than more enum cases on purpose: a distro whose icons are
   * slightly squarer than KDE's should be a CDN theme edit, not a Play release.
   */
  val cornerRadius: Double,
  /** <1 insets the glyph inside the shape. Papirus-ish sets want ~0.72. */
  val foregroundScale: Double,
  /**
   * null = keep the app's own adaptive background layer.
   * Set = flat fill, which is what makes an icon set feel coherent rather than
   * a bag of vendor colours. ARGB int.
   */
  val backgroundColor: Long? = null,
  /**
   * null = draw the app's real coloured foreground.
   * Set = force the monochrome layer, tinted. Degrades to the coloured
   * foreground when an app ships no monochrome layer — which is most of them.
   */
  val monochromeTint: Long? = null,
  /**
   * Hand-crafted icon pack that OVERRIDES the generator, e.g. "yaru".
   * ~40-60 icons: the ones that define the distro (Files, Terminal, Settings,
   * Software) plus the common third-party apps people actually look at.
   *
   * null = generator only. Part of the cache key.
   */
  val heroPack: String? = null,
  /**
   * The far end of a background GRADIENT, as ARGB. Null = flat fill.
   *
   * APPENDED, not inserted — same rule AppEntry.category follows. Field order
   * is the decode index, so adding at the END keeps IconStyle on codec 133
   * with every existing index unmoved.
   *
   * [backgroundColor] is the near end, so a gradient REQUIRES it: end set with
   * backgroundColor null means "no flat fill", and there is nothing to grade
   * from, so the renderer keeps the app's own adaptive background and ignores
   * this. That rule lives in IconRenderer.fillBackground and nowhere else.
   */
  val backgroundGradientEnd: Long? = null,
  /**
   * Gradient direction in degrees, rotating from top-to-bottom (0) toward
   * left-to-right (90). 45 is the top-left-to-bottom-right diagonal that most
   * desktop icon sets use. Ignored when [backgroundGradientEnd] is null.
   *
   * Nullable rather than defaulted so an existing theme.json with no gradient
   * block parses unchanged; the renderer substitutes 45.
   */
  val gradientAngle: Double? = null,
  /**
   * CC0 brand-glyph pack, e.g. "simple-icons". The HEAD of the icon pipeline:
   * a package-name map to a single 24x24 SVG path plus the brand's own hex.
   *
   * Sits BELOW [heroPack] in the lookup and above the generator. Hero art is
   * hand-drawn for one distro and wins; a brand glyph is shared across every
   * theme and only says "this is WhatsApp", not "this is Yaru's WhatsApp".
   *
   * null = skip the brand layer entirely. Part of the cache key.
   */
  val brandPack: String? = null,
  /**
   * How a brand glyph is coloured. "brandPlate" (default) fills the shape with
   * the brand's own hex and draws the glyph in whichever of white/near-black
   * reads on it — WhatsApp stays green and stays recognisable. "themePlate"
   * fills with the theme's own background (flat or graded) and draws the glyph
   * in the brand hex, so the whole grid reads as one set at the cost of some
   * recognisability. Yaru does the first; Papirus-style sets do the second.
   *
   * A STRING, NOT AN ENUM, AND THAT IS DELIBERATE. Pigeon numbers enums before
   * classes, so declaring a third enum would take codec 131 and shove AppEntry,
   * AppChangeEvent and IconStyle each up by one — silently repartitioning the
   * wire format this file's header pins down. Appending a nullable String to an
   * existing class costs nothing. Unknown values degrade to "brandPlate", same
   * contract as ShellKind.parse and the icon treatment.
   */
  val brandTreatment: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): IconStyle {
      val treatment = pigeonVar_list[0] as IconTreatment
      val cornerRadius = pigeonVar_list[1] as Double
      val foregroundScale = pigeonVar_list[2] as Double
      val backgroundColor = pigeonVar_list[3] as Long?
      val monochromeTint = pigeonVar_list[4] as Long?
      val heroPack = pigeonVar_list[5] as String?
      val backgroundGradientEnd = pigeonVar_list[6] as Long?
      val gradientAngle = pigeonVar_list[7] as Double?
      val brandPack = pigeonVar_list[8] as String?
      val brandTreatment = pigeonVar_list[9] as String?
      return IconStyle(treatment, cornerRadius, foregroundScale, backgroundColor, monochromeTint, heroPack, backgroundGradientEnd, gradientAngle, brandPack, brandTreatment)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      treatment,
      cornerRadius,
      foregroundScale,
      backgroundColor,
      monochromeTint,
      heroPack,
      backgroundGradientEnd,
      gradientAngle,
      brandPack,
      brandTreatment,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as IconStyle
    return LauncherApiPigeonUtils.deepEquals(this.treatment, other.treatment) && LauncherApiPigeonUtils.deepEquals(this.cornerRadius, other.cornerRadius) && LauncherApiPigeonUtils.deepEquals(this.foregroundScale, other.foregroundScale) && LauncherApiPigeonUtils.deepEquals(this.backgroundColor, other.backgroundColor) && LauncherApiPigeonUtils.deepEquals(this.monochromeTint, other.monochromeTint) && LauncherApiPigeonUtils.deepEquals(this.heroPack, other.heroPack) && LauncherApiPigeonUtils.deepEquals(this.backgroundGradientEnd, other.backgroundGradientEnd) && LauncherApiPigeonUtils.deepEquals(this.gradientAngle, other.gradientAngle) && LauncherApiPigeonUtils.deepEquals(this.brandPack, other.brandPack) && LauncherApiPigeonUtils.deepEquals(this.brandTreatment, other.brandTreatment)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.treatment)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.cornerRadius)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.foregroundScale)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.backgroundColor)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.monochromeTint)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.heroPack)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.backgroundGradientEnd)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.gradientAngle)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.brandPack)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.brandTreatment)
    return result
  }
  override fun toString(): String {
    return "IconStyle(treatment=$treatment, cornerRadius=$cornerRadius, foregroundScale=$foregroundScale, backgroundColor=$backgroundColor, monochromeTint=$monochromeTint, heroPack=$heroPack, backgroundGradientEnd=$backgroundGradientEnd, gradientAngle=$gradientAngle, brandPack=$brandPack, brandTreatment=$brandTreatment)"
  }
}

/**
 * One live sample of everything the device is willing to tell us.
 *
 * APPENDED AFTER IconStyle, so this takes codec 134 and every existing id
 * (129-133) is unmoved. `netTransport` is a String and not an enum for the
 * reason [IconStyle.brandTreatment] spells out: Pigeon numbers enums BEFORE
 * classes, so a third enum would take 131 and shove AppEntry, AppChangeEvent
 * and IconStyle each up by one. There will never be a third enum in this file.
 *
 * ─── EVERY FIELD IS NULLABLE, AND NULL IS LOAD-BEARING ──────────────────────
 *
 * `/proc/stat` returns nothing on a Galaxy S22: SELinux tightened proc access
 * and OEMs tightened further. There is NO permission-free system-wide CPU API
 * on modern Android — not restricted, absent. Any launcher showing a live CPU
 * percentage on Android 12+ is showing its own process or a number it invented.
 *
 * So null means "this device will not tell us", the row is absent, and nothing
 * renders `--%`. Which sources are absent is device-dependent, which is why
 * [StatCapabilities] exists as a separate answer.
 *
 * ─── NATIVE HOLDS NO STATE ──────────────────────────────────────────────────
 *
 * CPU and network are CUMULATIVE COUNTERS here, not rates. A rate needs two
 * samples and an interval, and the ticker that owns the interval lives in
 * Dart. Native reads and returns; the delta arithmetic stays in one tested
 * place. That is also why [elapsedRealtimeMillis] is non-null: it is both the
 * uptime row AND the sample clock the deltas divide by, so the rate stays
 * correct even when a frame is late.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DeviceStats (
  /**
   * `SystemClock.elapsedRealtime()`. Milliseconds since boot, INCLUDING deep
   * sleep, which is what makes it usable as a sample clock across a screen-off
   * gap. Never null: if this is unavailable the process is not running.
   */
  val elapsedRealtimeMillis: Long,
  /** 0-100 from the sticky ACTION_BATTERY_CHANGED broadcast. */
  val batteryPercent: Long? = null,
  val batteryCharging: Boolean? = null,
  /**
   * TENTHS of a degree Celsius, exactly as Android reports it. Kept in the
   * platform's own unit so the conversion happens once, in Dart, at the point
   * of display — converting here would round twice.
   */
  val batteryTempDeciC: Long? = null,
  /**
   * MICROAMPS, from `BATTERY_PROPERTY_CURRENT_NOW`.
   *
   * THE SIGN IS NOT PORTABLE. Most OEMs report negative while discharging;
   * several Samsung and Xiaomi builds report positive. So Dart displays the
   * MAGNITUDE and takes the direction from [batteryCharging], which is the one
   * signal that is consistent everywhere. Do not "fix" this by trusting the
   * sign.
   */
  val batteryCurrentMicroA: Long? = null,
  /**
   * `ActivityManager.MemoryInfo`, NOT `/proc/meminfo`. Same restriction story
   * as `/proc/stat`, and this one needs no file read at all.
   */
  val memAvailBytes: Long? = null,
  val memTotalBytes: Long? = null,
  /** `StatFs` on the data partition. No permission, works everywhere. */
  val storageFreeBytes: Long? = null,
  val storageTotalBytes: Long? = null,
  /**
   * `TrafficStats` device-wide byte counters since boot. Permission-free.
   * Null when the device reports `UNSUPPORTED`, which some emulators do.
   */
  val netRxBytes: Long? = null,
  val netTxBytes: Long? = null,
  /**
   * "wifi" | "cellular" | "ethernet" | "vpn" | "none".
   *
   * The transport only. NOT the SSID: reading the Wi-Fi network name needs
   * location permission on Android 10+, and a launcher that also sells itself
   * on privacy does not ask for location to draw a desktop widget.
   */
  val netTransport: String? = null,
  /**
   * `PowerManager.getCurrentThermalStatus()`, 0 (none) to 6 (shutdown).
   * API 29+; null below that.
   */
  val thermalStatus: Long? = null,
  /**
   * Aggregate `cpu` line of `/proc/stat`, idle+iowait and the grand total.
   *
   * Present because the READ IS WORTH ATTEMPTING even though it fails on a
   * Galaxy: SELinux policy is per-ROM, and the budget Infinix/Tecno/Xiaomi
   * devices this launcher targets are frequently laxer than Samsung. Probed
   * once at startup rather than fought with on every tick.
   */
  val cpuIdleJiffies: Long? = null,
  val cpuTotalJiffies: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DeviceStats {
      val elapsedRealtimeMillis = pigeonVar_list[0] as Long
      val batteryPercent = pigeonVar_list[1] as Long?
      val batteryCharging = pigeonVar_list[2] as Boolean?
      val batteryTempDeciC = pigeonVar_list[3] as Long?
      val batteryCurrentMicroA = pigeonVar_list[4] as Long?
      val memAvailBytes = pigeonVar_list[5] as Long?
      val memTotalBytes = pigeonVar_list[6] as Long?
      val storageFreeBytes = pigeonVar_list[7] as Long?
      val storageTotalBytes = pigeonVar_list[8] as Long?
      val netRxBytes = pigeonVar_list[9] as Long?
      val netTxBytes = pigeonVar_list[10] as Long?
      val netTransport = pigeonVar_list[11] as String?
      val thermalStatus = pigeonVar_list[12] as Long?
      val cpuIdleJiffies = pigeonVar_list[13] as Long?
      val cpuTotalJiffies = pigeonVar_list[14] as Long?
      return DeviceStats(elapsedRealtimeMillis, batteryPercent, batteryCharging, batteryTempDeciC, batteryCurrentMicroA, memAvailBytes, memTotalBytes, storageFreeBytes, storageTotalBytes, netRxBytes, netTxBytes, netTransport, thermalStatus, cpuIdleJiffies, cpuTotalJiffies)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      elapsedRealtimeMillis,
      batteryPercent,
      batteryCharging,
      batteryTempDeciC,
      batteryCurrentMicroA,
      memAvailBytes,
      memTotalBytes,
      storageFreeBytes,
      storageTotalBytes,
      netRxBytes,
      netTxBytes,
      netTransport,
      thermalStatus,
      cpuIdleJiffies,
      cpuTotalJiffies,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DeviceStats
    return LauncherApiPigeonUtils.deepEquals(this.elapsedRealtimeMillis, other.elapsedRealtimeMillis) && LauncherApiPigeonUtils.deepEquals(this.batteryPercent, other.batteryPercent) && LauncherApiPigeonUtils.deepEquals(this.batteryCharging, other.batteryCharging) && LauncherApiPigeonUtils.deepEquals(this.batteryTempDeciC, other.batteryTempDeciC) && LauncherApiPigeonUtils.deepEquals(this.batteryCurrentMicroA, other.batteryCurrentMicroA) && LauncherApiPigeonUtils.deepEquals(this.memAvailBytes, other.memAvailBytes) && LauncherApiPigeonUtils.deepEquals(this.memTotalBytes, other.memTotalBytes) && LauncherApiPigeonUtils.deepEquals(this.storageFreeBytes, other.storageFreeBytes) && LauncherApiPigeonUtils.deepEquals(this.storageTotalBytes, other.storageTotalBytes) && LauncherApiPigeonUtils.deepEquals(this.netRxBytes, other.netRxBytes) && LauncherApiPigeonUtils.deepEquals(this.netTxBytes, other.netTxBytes) && LauncherApiPigeonUtils.deepEquals(this.netTransport, other.netTransport) && LauncherApiPigeonUtils.deepEquals(this.thermalStatus, other.thermalStatus) && LauncherApiPigeonUtils.deepEquals(this.cpuIdleJiffies, other.cpuIdleJiffies) && LauncherApiPigeonUtils.deepEquals(this.cpuTotalJiffies, other.cpuTotalJiffies)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.elapsedRealtimeMillis)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.batteryPercent)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.batteryCharging)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.batteryTempDeciC)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.batteryCurrentMicroA)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.memAvailBytes)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.memTotalBytes)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.storageFreeBytes)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.storageTotalBytes)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.netRxBytes)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.netTxBytes)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.netTransport)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.thermalStatus)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.cpuIdleJiffies)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.cpuTotalJiffies)
    return result
  }
  override fun toString(): String {
    return "DeviceStats(elapsedRealtimeMillis=$elapsedRealtimeMillis, batteryPercent=$batteryPercent, batteryCharging=$batteryCharging, batteryTempDeciC=$batteryTempDeciC, batteryCurrentMicroA=$batteryCurrentMicroA, memAvailBytes=$memAvailBytes, memTotalBytes=$memTotalBytes, storageFreeBytes=$storageFreeBytes, storageTotalBytes=$storageTotalBytes, netRxBytes=$netRxBytes, netTxBytes=$netTxBytes, netTransport=$netTransport, thermalStatus=$thermalStatus, cpuIdleJiffies=$cpuIdleJiffies, cpuTotalJiffies=$cpuTotalJiffies)"
  }
}

/**
 * Which sources this specific device will actually serve. Codec 135.
 *
 * A SEPARATE ANSWER FROM A SNAPSHOT OF NULLS, and that distinction is the
 * whole reason this class exists. A null in [DeviceStats] is ambiguous: it can
 * mean "this device never provides it" or "not sampled yet" (network and CPU
 * are rates, so the first tick has no value by construction). Those need
 * different UI — permanently absent versus pending — and a desklet cannot tell
 * them apart from the snapshot alone.
 *
 * Probed ONCE natively and cached for the process. Without it you ship a panel
 * that is rich on one phone and half-empty on another with no way to know
 * which, and no way to tell a user's bug report from a platform limit.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class StatCapabilities (
  /** Level and charging state. True on effectively every device. */
  val battery: Boolean,
  /**
   * Temperature and current draw. Separate from [battery] because the sticky
   * broadcast can carry a level while `BATTERY_PROPERTY_CURRENT_NOW` returns
   * nothing, and the detail rows are the ones that make a battery desklet
   * worth having at all (Android's own status bar already shows a percentage).
   */
  val batteryDetail: Boolean,
  val memory: Boolean,
  val storage: Boolean,
  /**
   * `TrafficStats` counters. Independent of [networkTransport]: the counters
   * can work while the transport lookup does not, and the reverse.
   */
  val network: Boolean,
  /**
   * `ConnectivityManager` transport lookup. Needs ACCESS_NETWORK_STATE, which
   * is a NORMAL permission — auto-granted, no prompt, no Play declaration.
   */
  val networkTransport: Boolean,
  val thermal: Boolean,
  /**
   * Almost always false on Android 12+. Kept as an honest field rather than
   * dropped, so the answer is "this device says no" instead of "the launcher
   * never asked".
   */
  val cpu: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StatCapabilities {
      val battery = pigeonVar_list[0] as Boolean
      val batteryDetail = pigeonVar_list[1] as Boolean
      val memory = pigeonVar_list[2] as Boolean
      val storage = pigeonVar_list[3] as Boolean
      val network = pigeonVar_list[4] as Boolean
      val networkTransport = pigeonVar_list[5] as Boolean
      val thermal = pigeonVar_list[6] as Boolean
      val cpu = pigeonVar_list[7] as Boolean
      return StatCapabilities(battery, batteryDetail, memory, storage, network, networkTransport, thermal, cpu)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      battery,
      batteryDetail,
      memory,
      storage,
      network,
      networkTransport,
      thermal,
      cpu,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as StatCapabilities
    return LauncherApiPigeonUtils.deepEquals(this.battery, other.battery) && LauncherApiPigeonUtils.deepEquals(this.batteryDetail, other.batteryDetail) && LauncherApiPigeonUtils.deepEquals(this.memory, other.memory) && LauncherApiPigeonUtils.deepEquals(this.storage, other.storage) && LauncherApiPigeonUtils.deepEquals(this.network, other.network) && LauncherApiPigeonUtils.deepEquals(this.networkTransport, other.networkTransport) && LauncherApiPigeonUtils.deepEquals(this.thermal, other.thermal) && LauncherApiPigeonUtils.deepEquals(this.cpu, other.cpu)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.battery)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.batteryDetail)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.memory)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.storage)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.network)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.networkTransport)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.thermal)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.cpu)
    return result
  }
  override fun toString(): String {
    return "StatCapabilities(battery=$battery, batteryDetail=$batteryDetail, memory=$memory, storage=$storage, network=$network, networkTransport=$networkTransport, thermal=$thermal, cpu=$cpu)"
  }
}

/**
 * One installed third-party AppWidget provider, as returned by
 * `AppWidgetManager.getInstalledProviders()`.
 *
 * ADDED AT THE END OF THE CLASS GROUP → codec id 136. It carries METADATA only,
 * never the preview bitmap: a device can have dozens of providers, and pushing
 * a PNG for each across the bridge on every picker open is the kind of payload
 * that makes a budget phone stutter. Previews are pulled lazily, one at a time,
 * through [LauncherHostApi.getWidgetPreview] as the list scrolls — the same
 * memory-then-render discipline `getIcon` already follows.
 *
 * Every "enum-shaped" value here is an int, deliberately, because a new enum
 * would renumber the whole codec (see the header). [resizeMode] is Android's
 * bitmask (0 none, 1 horizontal, 2 vertical, 3 both); [category] is its
 * widgetCategory bitmask (1 home screen, 2 keyguard, 4 searchbox).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class WidgetProviderInfo (
  /**
   * `ComponentName.flattenToString()` — the stable id the host will bind and
   * inflate against later. The grouping key on the Dart side is [packageName];
   * this is the per-provider identity.
   */
  val providerKey: String,
  /**
   * The owning app's package. What the Dart side groups by, so "Adblock
   * Browser" shows once with a count rather than four loose rows.
   */
  val packageName: String,
  /**
   * The owning app's display label, resolved via PackageManager. The section
   * header in the picker ("Adblock Browser").
   */
  val appLabel: String,
  /**
   * The widget's OWN label ("Battery status", "Dual clock"). May equal the app
   * label for single-widget apps.
   */
  val label: String,
  /**
   * Minimum footprint, already converted to dp on the native side so Dart
   * never has to know the device density. Used to pick an initial cell span.
   */
  val minWidthDp: Long,
  val minHeightDp: Long,
  /**
   * How small the user may resize it. Equal to the min size when the provider
   * is not resizable in that axis.
   */
  val minResizeWidthDp: Long,
  val minResizeHeightDp: Long,
  /**
   * Android 12+ target cells (0 on older devices / unset). A hint for the
   * initial span that is already expressed in grid units rather than dp.
   */
  val targetCellWidth: Long,
  val targetCellHeight: Long,
  /** Android's resize bitmask: 0 none, 1 horizontal, 2 vertical, 3 both. */
  val resizeMode: Long,
  /**
   * widgetCategory bitmask: 1 home screen, 2 keyguard, 4 searchbox. The picker
   * shows only providers advertising the home-screen bit.
   */
  val category: Long,
  /**
   * Has a configuration Activity that must run when it is first placed. The
   * host has to launch it before the widget is usable (the host slice's job);
   * the picker only needs to know it exists.
   */
  val configurable: Boolean,
  /**
   * Whether `previewImage` is set, so the Dart side knows a real preview is
   * worth requesting rather than falling straight back to the app icon.
   */
  val hasPreviewImage: Boolean,
  /**
   * The provider's own one-line pitch, from `loadDescription()` on API 31+.
   *
   * "Play your favs and find new tunes, right from your home screen."
   * "Start a chat with Claude."
   *
   * The stock picker shows this under the size, and it is most of why a
   * third-party widget reads as a considered offer there rather than as a row
   * in a list. Empty on pre-31 devices and on providers that never set it, and
   * the card simply omits the line rather than printing a placeholder, the
   * same rule nullable stats follow everywhere else.
   *
   * APPENDED AT THE END, which is the whole reason this is a safe addition:
   * Pigeon numbers enums before classes and classes in declaration order, so a
   * field added at the tail of the LAST class shifts nothing a shipped APK
   * already agreed on. Inserting it mid-class would renumber every field after
   * it. No new enum either, for the same reason.
   */
  val description: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WidgetProviderInfo {
      val providerKey = pigeonVar_list[0] as String
      val packageName = pigeonVar_list[1] as String
      val appLabel = pigeonVar_list[2] as String
      val label = pigeonVar_list[3] as String
      val minWidthDp = pigeonVar_list[4] as Long
      val minHeightDp = pigeonVar_list[5] as Long
      val minResizeWidthDp = pigeonVar_list[6] as Long
      val minResizeHeightDp = pigeonVar_list[7] as Long
      val targetCellWidth = pigeonVar_list[8] as Long
      val targetCellHeight = pigeonVar_list[9] as Long
      val resizeMode = pigeonVar_list[10] as Long
      val category = pigeonVar_list[11] as Long
      val configurable = pigeonVar_list[12] as Boolean
      val hasPreviewImage = pigeonVar_list[13] as Boolean
      val description = pigeonVar_list[14] as String
      return WidgetProviderInfo(providerKey, packageName, appLabel, label, minWidthDp, minHeightDp, minResizeWidthDp, minResizeHeightDp, targetCellWidth, targetCellHeight, resizeMode, category, configurable, hasPreviewImage, description)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      providerKey,
      packageName,
      appLabel,
      label,
      minWidthDp,
      minHeightDp,
      minResizeWidthDp,
      minResizeHeightDp,
      targetCellWidth,
      targetCellHeight,
      resizeMode,
      category,
      configurable,
      hasPreviewImage,
      description,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WidgetProviderInfo
    return LauncherApiPigeonUtils.deepEquals(this.providerKey, other.providerKey) && LauncherApiPigeonUtils.deepEquals(this.packageName, other.packageName) && LauncherApiPigeonUtils.deepEquals(this.appLabel, other.appLabel) && LauncherApiPigeonUtils.deepEquals(this.label, other.label) && LauncherApiPigeonUtils.deepEquals(this.minWidthDp, other.minWidthDp) && LauncherApiPigeonUtils.deepEquals(this.minHeightDp, other.minHeightDp) && LauncherApiPigeonUtils.deepEquals(this.minResizeWidthDp, other.minResizeWidthDp) && LauncherApiPigeonUtils.deepEquals(this.minResizeHeightDp, other.minResizeHeightDp) && LauncherApiPigeonUtils.deepEquals(this.targetCellWidth, other.targetCellWidth) && LauncherApiPigeonUtils.deepEquals(this.targetCellHeight, other.targetCellHeight) && LauncherApiPigeonUtils.deepEquals(this.resizeMode, other.resizeMode) && LauncherApiPigeonUtils.deepEquals(this.category, other.category) && LauncherApiPigeonUtils.deepEquals(this.configurable, other.configurable) && LauncherApiPigeonUtils.deepEquals(this.hasPreviewImage, other.hasPreviewImage) && LauncherApiPigeonUtils.deepEquals(this.description, other.description)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.providerKey)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.packageName)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.appLabel)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.label)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.minWidthDp)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.minHeightDp)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.minResizeWidthDp)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.minResizeHeightDp)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.targetCellWidth)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.targetCellHeight)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.resizeMode)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.category)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.configurable)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.hasPreviewImage)
    result = 31 * result + LauncherApiPigeonUtils.deepHash(this.description)
    return result
  }
  override fun toString(): String {
    return "WidgetProviderInfo(providerKey=$providerKey, packageName=$packageName, appLabel=$appLabel, label=$label, minWidthDp=$minWidthDp, minHeightDp=$minHeightDp, minResizeWidthDp=$minResizeWidthDp, minResizeHeightDp=$minResizeHeightDp, targetCellWidth=$targetCellWidth, targetCellHeight=$targetCellHeight, resizeMode=$resizeMode, category=$category, configurable=$configurable, hasPreviewImage=$hasPreviewImage, description=$description)"
  }
}
private open class LauncherApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AppChangeReason.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          IconTreatment.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AppEntry.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AppChangeEvent.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          IconStyle.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeviceStats.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StatCapabilities.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WidgetProviderInfo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AppChangeReason -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is IconTreatment -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is AppEntry -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is AppChangeEvent -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is IconStyle -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is DeviceStats -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is StatCapabilities -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is WidgetProviderInfo -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Implemented by `LauncherHostApiImpl`, constructed in
 * `LauncherApplication.onCreate` against the warmed engine.
 *
 * `@async` marks the methods whose Kotlin side takes a callback instead of
 * returning: anything that touches disk, decodes a bitmap, or hits the package
 * manager cold. Everything else is a straight synchronous call. Getting this
 * wrong does not fail to compile — it silently moves work onto the platform
 * thread — so the four below are exactly the four that are async today.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface LauncherHostApi {
  /**
   * The full launchable-app list. Served from cache when warm, refreshed off
   * the main thread when cold.
   */
  fun getInstalledApps(callback: (Result<List<AppEntry>>) -> Unit)
  /**
   * [sourceLeft]..[sourceBottom] are the icon's on-screen rect in logical
   * pixels, so the system can expand the opening app FROM the icon. All null =
   * no animation origin.
   */
  fun launchApp(componentKey: String, sourceLeft: Double?, sourceTop: Double?, sourceRight: Double?, sourceBottom: Double?)
  fun openAppInfo(componentKey: String)
  /**
   * Start the system's uninstall confirmation, and report what happened.
   *
   * ─── WHY THIS RETURNS A STRING AND NOT void ─────────────────────────────
   *
   * It used to be `void`, and the native side answered every refusal with a
   * bare `return`. A guard that produces no output is indistinguishable from a
   * broken feature, which is exactly how it was reported: the button did
   * nothing, and nothing said why.
   *
   * A STRING AND NOT AN ENUM. Pigeon numbers enums ahead of classes in the
   * codec, so introducing one here would renumber every existing class and
   * break any APK already in the field against a newer engine. Every
   * enum-shaped value in this schema is a string for that reason.
   *
   * The vocabulary, mirrored in `UninstallStatus` (Kotlin) and
   * `UninstallStatus` (Dart, in data/repositories/app_repository.dart):
   *
   *   launched           the confirmation was started from the Activity
   *   launched_detached  started from the app context, no Activity attached
   *   unknown_app        not in the app list, usually a stale tile
   *   system_app         preinstalled and never updated, nothing to remove
   *   work_profile       owned by the profile admin
   *   no_installer       nothing on this device answers ACTION_DELETE
   *   refused            the system refused the start
   *
   * A status this side does not recognise must be treated as a failure with a
   * generic message, never as success.
   */
  fun requestUninstall(componentKey: String): String
  /**
   * Swap the active icon theme. Invalidates the in-memory icon cache; the DISK
   * cache is kept, so switching back to a theme you used before is instant.
   *
   * [themeId] is part of every cache key. Change the style without changing the
   * id and you will serve stale icons — so version the id ("ubuntu-24-04.v2")
   * whenever you edit a theme's icon block.
   */
  fun setIconTheme(themeId: String, style: IconStyle)
  /**
   * PNG bytes for one icon at one size, under the active theme.
   * Null if the component vanished (uninstalled mid-scroll).
   *
   * Memory LRU -> disk -> render. The render path is the only slow one, and it
   * runs off the main thread.
   */
  fun getIcon(componentKey: String, sizePx: Long, callback: (Result<ByteArray?>) -> Unit)
  /**
   * PNG bytes for several icons in an ARBITRARY tint, for the storefront.
   *
   * ─── WHY IT LIVES HERE AND NOT ON `PackHostApi` ───────────────────────────
   *
   * It went on `PackHostApi` first, which reads well: previews are a storefront
   * concern and the storefront is packs. But `PackHostApiImpl` is downloads and
   * entitlement and holds no `IconCache`, while `LauncherHostApiImpl` builds
   * one with six collaborators and already serves [getIcon] from it.
   *
   * Reaching across would have meant threading a cache into a class whose job
   * is fetching bytes, or exposing a singleton. Rendering an icon is this
   * interface's job; the fact that a storefront is asking does not change that.
   *
   * ─── NEEDS NO PURCHASE, AND NO INSTALL ────────────────────────────────────
   *
   * `arcticons-line` holds all 13,622 drawings and is already on the device: it
   * is free, and required by whichever official pack the user has. A derived
   * pack adds only a colour. So previewing Kali blue on an Ubuntu device is
   * installed geometry plus a hex value.
   *
   * NOT CACHED. `IconCache` keys bitmaps by the applied style, which carries no
   * previewed colour, so caching these would poison the drawer with a pack
   * nobody bought and it would survive a restart.
   *
   * One entry per key, in order, null where nothing could be drawn, so a fixed
   * grid can be laid out without matching lengths.
   */
  fun previewIcons(componentKeys: List<String>, tintHex: String, sizePx: Long, callback: (Result<List<ByteArray?>>) -> Unit)
  /** Nukes memory + disk. For a "rebuild icon cache" button in Settings. */
  fun clearIconCache(callback: (Result<Unit>) -> Unit)
  /** Are we the home app right now? Drives the "Set as default" banner. */
  fun isDefaultLauncher(): Boolean
  /**
   * Opens Android's Home-app picker.
   *
   * NOT RoleManager. RoleManager gives a prettier in-app dialog but needs an
   * Activity + result plumbing, and several OEMs (Samsung, Xiaomi) intercept
   * or ignore it anyway. ACTION_HOME_SETTINGS is boring and works everywhere.
   */
  fun requestDefaultLauncher()
  /**
   * Sets the REAL system wallpaper.
   *
   * [source] is "asset:<path>" (a theme preset) or a content:// URI the user
   * picked. Returns false on failure — a bad image must not take the launcher
   * down; the user simply keeps the wallpaper they had.
   * [fit] is how the image meets the screen: 'cover' | 'contain' | 'fill' |
   * 'center'. A STRING, NOT AN ENUM, same rule as `brandTreatment`: a third
   * enum would renumber this codec's positional ids, and an unknown value
   * from a newer build must degrade (natively, to 'cover') rather than fail
   * to parse. 'cover' is byte-for-byte the legacy path, so existing users
   * see no change. [letterboxColor] is the ARGB that fills the bars 'contain'
   * and 'center' leave; the Dart side passes the theme palette's background.
   *
   * [focalX] and [focalY] are 0 to 1 across the SOURCE image and say where the
   * subject is. [zoom] is 1 or more; above 1 keeps less of the picture.
   *
   * ─── WHY THESE ARE THREE LOOSE DOUBLES AND NOT A CLASS ──────────────────
   *
   * A `WallpaperFraming` data class would read better here and would cost a
   * codec id in a schema that already carries enums, and appending one is only
   * safe at the very END of the file where nothing follows it to renumber.
   * Three scalars on a method signature take no id at all: Pigeon methods are
   * named channels, so adding arguments to one cannot move another class's
   * position on the wire. The ugly version is the one that cannot break the
   * packs already installed on people's phones.
   *
   * All three are CLAMPED NATIVELY as well as in Dart. They arrive from stored
   * prefs, and prefs outlive the build that wrote them: a value from a future
   * version, or a hand-edited theme.json, must degrade rather than produce a
   * degenerate crop rect the system quietly ignores.
   */
  fun setWallpaper(source: String, applyToLock: Boolean, fit: String, letterboxColor: Long, focalX: Double, focalY: Double, zoom: Double, callback: (Result<Boolean>) -> Unit)
  /**
   * Rotates the wallpaper, desktop-style.
   *
   * [minutes] is CLAMPED TO 15 — WorkManager's hard floor. Do not offer a
   * shorter interval in the UI and quietly deliver fifteen; lying about a
   * setting is worse than not having it.
   * [fit] and [letterboxColor] as on [setWallpaper]: the worker stores them
   * beside the source list so every rotation tick renders the same way a
   * manual apply does.
   *
   * [framingJson] is a JSON object mapping a source string from [sources] to
   * its framing: `{"asset:a.webp":{"fit":"cover","focalY":0.38}}`. Sources
   * absent from it fall back to [fit] and a centred focal point.
   *
   * ─── WHY A JSON STRING AND NOT PARALLEL LISTS ───────────────────────────
   *
   * The alternative is four more `List<double>` arguments index-matched to
   * [sources], and index-matched lists across a process boundary is a bug
   * waiting for the first caller who filters one list and forgets the others:
   * the failure is silent and it is every wallpaper after the removed one
   * wearing its neighbour's framing. A map keyed by the source cannot
   * desynchronise, and an entry for a source that is no longer in the pool is
   * simply never looked up.
   *
   * It is also already the shape on the other side. The worker cannot use
   * WorkManager's inputData for this (10KB cap, which is why [sources] itself
   * lives in SharedPreferences), so it stores a string and re-reads it each
   * tick. Handing it a string it can store verbatim keeps the whole rotation
   * path free of a second serialisation format.
   */
  fun scheduleWallpaperRotation(minutes: Long, sources: List<String>, applyToLock: Boolean, fit: String, letterboxColor: Long, framingJson: String)
  fun cancelWallpaperRotation()
  /**
   * Is the gesture accessibility service actually enabled?
   *
   * Checked live rather than cached: the user can revoke it in system settings
   * at any moment, and a launcher whose gestures silently stopped working — with
   * no explanation — is a launcher people give up on.
   */
  fun isGestureServiceEnabled(): Boolean
  /** Opens Android's accessibility settings so the user can enable it. */
  fun openAccessibilitySettings()
  /**
   * "notifications" | "quickSettings" | "lockScreen" | "recents".
   * Returns false when the service is off or the action is unsupported.
   * NEVER throws — a gesture that crashes the home screen is unforgivable.
   */
  fun performGlobalAction(action: String): Boolean
  /**
   * Copy the CURRENT system wallpaper aside, once, before a theme first
   * replaces it. Returns true when a stash now exists.
   *
   * Best effort by necessity: reading the wallpaper back has been progressively
   * restricted (Android 13+ limits `getWallpaperFile` for apps that did not set
   * it), so on some devices this simply cannot succeed. It returns false rather
   * than throwing, and the Dart side hides "restore" instead of offering a
   * button that would not work — a restore that silently fails is worse than no
   * restore.
   */
  fun stashWallpaper(callback: (Result<Boolean>) -> Unit)
  /** Is there a stash to go back to? Drives whether the UI offers a restore. */
  fun hasStashedWallpaper(callback: (Result<Boolean>) -> Unit)
  /**
   * Put the stashed wallpaper back on both home and lock, and drop the stash.
   * False when there was nothing stashed or the write failed.
   */
  fun restoreWallpaper(callback: (Result<Boolean>) -> Unit)
  /**
   * Deep-link into a real Android settings screen instead of reimplementing it.
   * [action] is a Settings.ACTION_* string, e.g.
   * "android.settings.APPLICATION_DETAILS_SETTINGS".
   *
   * Reimplementing OS settings screens is how launchers rot: the OEM changes
   * something and your copy is quietly wrong forever.
   */
  fun openAndroidSettings(action: String)
  /**
   * Which stat sources this device will actually serve.
   *
   * Probed once natively and cached for the process lifetime, so calling it on
   * every desklet mount is free. `@async` because the probe attempts a file
   * read and a `StatFs`, and neither belongs on the platform thread even once.
   */
  fun getStatCapabilities(callback: (Result<StatCapabilities>) -> Unit)
  /**
   * ONE snapshot. No polling, no state, no stream.
   *
   * Native does not own a timer, deliberately. A native ticker would keep
   * running while Dart is paused and would need its own lifecycle plumbing
   * duplicating the one Dart already has; and a stream would push at a rate
   * no consumer chose. The Dart-side ticker calls this and stops calling it
   * when the launcher is not on screen, which is the only reliable way to keep
   * a permanently-visible home screen off a budget phone's battery.
   */
  fun readStats(callback: (Result<DeviceStats>) -> Unit)
  /**
   * Every installed home-screen AppWidget provider, grouped by app on the Dart
   * side. METADATA ONLY — no bitmaps (see [WidgetProviderInfo]).
   *
   * `@async` because it walks PackageManager to resolve each app label, which
   * is the same cold-package-manager cost that put `getInstalledApps` on this
   * list. This does NOT run a host and needs no BIND_APPWIDGET permission;
   * enumerating providers and hosting one live are separate capabilities, and
   * only the second needs the host.
   */
  fun getInstalledWidgetProviders(callback: (Result<List<WidgetProviderInfo>>) -> Unit)
  /**
   * The preview for ONE provider, rendered to a PNG at the requested size.
   * Null when the provider vanished or has neither a preview image nor an icon.
   *
   * Pulled lazily as the picker scrolls, one provider at a time, so the list
   * opens instantly and previews fill in — never a wall of bitmaps shipped up
   * front. [providerKey] is the flattened ComponentName from
   * [WidgetProviderInfo.providerKey].
   */
  fun getWidgetPreview(providerKey: String, widthPx: Long, heightPx: Long, callback: (Result<ByteArray?>) -> Unit)
  /**
   * Allocate + bind + configure a live AppWidget, returning its host widget id
   * — or null if the user cancelled the bind-permission dialog or the config
   * screen. This is the ONE call that can pop system UI: a launcher is not a
   * signed system app, so `bindAppWidgetIdIfAllowed` almost always returns
   * false and Android's consent dialog runs, and a provider with a config
   * Activity runs that too. `@async` because it holds until those results come
   * back through the Activity.
   *
   * The returned id is DEVICE-LOCAL and non-portable: it is stored on the
   * desklet's config for THIS install only, never in a starter or a CDN pack.
   */
  fun addWidget(providerKey: String, callback: (Result<Long?>) -> Unit)
  /**
   * Release a hosted widget id when its desklet is removed. Deletes the host
   * allocation so the id is not leaked for the life of the install.
   */
  fun removeWidget(widgetId: Long)
  /**
   * Tell the provider its new footprint after a resize, in dp, so its
   * RemoteViews re-lays-out (a wide clock shows seconds, a tall calendar shows
   * more rows). Without this the view keeps its placed layout and just scales.
   */
  fun updateWidgetSize(widgetId: Long, minWidthDp: Long, minHeightDp: Long, maxWidthDp: Long, maxHeightDp: Long)
  /**
   * Installed icon packs: package name -> user-visible label.
   *
   * `@async` because it is several `queryIntentActivities` calls plus a label
   * load each, and the picker opening is not worth a main-thread stall.
   *
   * Returns EMPTY, never an error, when nothing is installed. Note that an
   * empty result is also what a missing `<queries>` declaration produces, so if
   * this is empty on a phone that plainly has icon packs, check the manifest
   * before this code.
   */
  fun installedIconPacks(callback: (Result<Map<String, String>>) -> Unit)
  /**
   * Select a pack, or null to stop using one.
   *
   * `@async` because selecting one PARSES `appfilter.xml` out of the pack's
   * APK, which for a large pack is thousands of entries. On the main thread
   * that is a visible freeze on the home screen at the exact moment the user
   * taps a radio button.
   */
  fun setIconPack(packageName: String?, callback: (Result<Unit>) -> Unit)
  /**
   * Fire an arbitrary view intent and let Android pick who handles it.
   *
   * ─── WHY THIS IS NOT `openAndroidSettings` WITH A WIDER DOC ───────────────
   *
   * That method's contract says [action] is a `Settings.ACTION_*` string, and
   * `RoleRequester.openSettings` is written to that promise. Downloads happens
   * to be action-only, so passing `android.intent.action.VIEW_DOWNLOADS` there
   * would probably work today, and that is exactly the kind of "probably" that
   * breaks silently the next time someone tightens the helper to validate its
   * own documented input.
   *
   * Screenshots settles it regardless: there is no action-only intent for a
   * media folder. It needs ACTION_VIEW with a MediaStore URI and a MIME type,
   * which a one-string method cannot express at all.
   *
   * ─── APPENDED, WHICH IS THE SAFE HALF OF THE PIGEON RULE ──────────────────
   *
   * Codec ids are positional over CLASSES and ENUMS. A method carries no id,
   * so adding one renumbers nothing and a shipped APK keeps agreeing with this
   * schema. That is the whole reason this is a method taking three strings
   * rather than an `IntentRequest` class, which WOULD take an id: the class
   * would land last today and be safe, and be a trap the first time someone
   * inserts another one above it.
   *
   * [uri] and [type] are null for an action-only intent. Setting both is the
   * `setDataAndType` case, which is what a media folder needs and which is NOT
   * the same as calling setData then setType, since each clears the other.
   *
   * Returns false when nothing on the device can handle it, so the caller can
   * say so instead of the tap doing nothing. A phone with no gallery and no
   * file manager is not a crash.
   */
  fun openIntent(action: String, uri: String?, type: String?): Boolean
  /**
   * Can anything on this phone transcribe speech?
   *
   * Asked so the microphone in the search field can be ABSENT rather than
   * present and dead. Same rule the stats rows follow: a control that does
   * nothing is worse than no control, because the user concludes the app is
   * broken rather than that the phone lacks a recogniser.
   *
   * Needs the matching `<intent>` in the manifest's `<queries>` block.
   * `resolveActivity` is package-visibility filtered on Android 11+ and this
   * app deliberately does not hold QUERY_ALL_PACKAGES, so without it this
   * returns false on every modern phone and the microphone hides itself
   * everywhere.
   */
  fun canRecognizeSpeech(callback: (Result<Boolean>) -> Unit)
  /**
   * Run the phone's own speech recogniser and return what it heard, or null.
   *
   * ─── WHY THE INTENT AND NOT SpeechRecognizer ──────────────────────────────
   *
   * `SpeechRecognizer` listens inline with no screen change, which is nicer,
   * and costs RECORD_AUDIO, a runtime permission prompt and a microphone entry
   * on the data-safety form. `ACTION_RECOGNIZE_SPEECH` hands the job to
   * whichever recogniser the user already has, with that recogniser's own UI,
   * and needs no permission at all. For a launcher whose whole pitch is that it
   * does not surveil anyone, the second is not a compromise.
   *
   * Null covers every non-answer: cancelled, misheard, no recogniser, or the
   * Activity torn down while the recogniser was on screen. The caller leaves
   * the search field alone in all four cases.
   *
   * [prompt] is the line the recogniser shows above its microphone.
   */
  fun recognizeSpeech(prompt: String?, callback: (Result<String?>) -> Unit)

  companion object {
    /** The codec used by LauncherHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      LauncherApiPigeonCodec()
    }
    /** Sets up an instance of `LauncherHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: LauncherHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.getInstalledApps$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getInstalledApps{ result: Result<List<AppEntry>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LauncherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.launchApp$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val componentKeyArg = args[0] as String
            val sourceLeftArg = args[1] as Double?
            val sourceTopArg = args[2] as Double?
            val sourceRightArg = args[3] as Double?
            val sourceBottomArg = args[4] as Double?
            val wrapped: List<Any?> = try {
              api.launchApp(componentKeyArg, sourceLeftArg, sourceTopArg, sourceRightArg, sourceBottomArg)
              listOf(null)
            } catch (exception: Throwable) {
              LauncherApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.openAppInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val componentKeyArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.openAppInfo(componentKeyArg)
              listOf(null)
            } catch (exception: Throwable) {
              LauncherApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.requestUninstall$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val componentKeyArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.requestUninstall(componentKeyArg))
            } catch (exception: Throwable) {
              LauncherApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.setIconTheme$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val themeIdArg = args[0] as String
            val styleArg = args[1] as IconStyle
            val wrapped: List<Any?> = try {
              api.setIconTheme(themeIdArg, styleArg)
              listOf(null)
            } catch (exception: Throwable) {
              LauncherApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.getIcon$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val componentKeyArg = args[0] as String
            val sizePxArg = args[1] as Long
            api.getIcon(componentKeyArg, sizePxArg) { result: Result<ByteArray?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LauncherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.previewIcons$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val componentKeysArg = args[0] as List<String>
            val tintHexArg = args[1] as String
            val sizePxArg = args[2] as Long
            api.previewIcons(componentKeysArg, tintHexArg, sizePxArg) { result: Result<List<ByteArray?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LauncherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.clearIconCache$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.clearIconCache{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(LauncherApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.isDefaultLauncher$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isDefaultLauncher())
            } catch (exception: Throwable) {
              LauncherApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.requestDefaultLauncher$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.requestDefaultLauncher()
              listOf(null)
            } catch (exception: Throwable) {
              LauncherApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.setWallpaper$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sourceArg = args[0] as String
            val applyToLockArg = args[1] as Boolean
            val fitArg = args[2] as String
            val letterboxColorArg = args[3] as Long
            val focalXArg = args[4] as Double
            val focalYArg = args[5] as Double
            val zoomArg = args[6] as Double
            api.setWallpaper(sourceArg, applyToLockArg, fitArg, letterboxColorArg, focalXArg, focalYArg, zoomArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LauncherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.scheduleWallpaperRotation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val minutesArg = args[0] as Long
            val sourcesArg = args[1] as List<String>
            val applyToLockArg = args[2] as Boolean
            val fitArg = args[3] as String
            val letterboxColorArg = args[4] as Long
            val framingJsonArg = args[5] as String
            val wrapped: List<Any?> = try {
              api.scheduleWallpaperRotation(minutesArg, sourcesArg, applyToLockArg, fitArg, letterboxColorArg, framingJsonArg)
              listOf(null)
            } catch (exception: Throwable) {
              LauncherApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.cancelWallpaperRotation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.cancelWallpaperRotation()
              listOf(null)
            } catch (exception: Throwable) {
              LauncherApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.isGestureServiceEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isGestureServiceEnabled())
            } catch (exception: Throwable) {
              LauncherApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.openAccessibilitySettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openAccessibilitySettings()
              listOf(null)
            } catch (exception: Throwable) {
              LauncherApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.performGlobalAction$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val actionArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.performGlobalAction(actionArg))
            } catch (exception: Throwable) {
              LauncherApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.stashWallpaper$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stashWallpaper{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LauncherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.hasStashedWallpaper$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.hasStashedWallpaper{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LauncherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.restoreWallpaper$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.restoreWallpaper{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LauncherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.openAndroidSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val actionArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.openAndroidSettings(actionArg)
              listOf(null)
            } catch (exception: Throwable) {
              LauncherApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.getStatCapabilities$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getStatCapabilities{ result: Result<StatCapabilities> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LauncherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.readStats$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.readStats{ result: Result<DeviceStats> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LauncherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.getInstalledWidgetProviders$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getInstalledWidgetProviders{ result: Result<List<WidgetProviderInfo>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LauncherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.getWidgetPreview$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val providerKeyArg = args[0] as String
            val widthPxArg = args[1] as Long
            val heightPxArg = args[2] as Long
            api.getWidgetPreview(providerKeyArg, widthPxArg, heightPxArg) { result: Result<ByteArray?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LauncherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.addWidget$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val providerKeyArg = args[0] as String
            api.addWidget(providerKeyArg) { result: Result<Long?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LauncherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.removeWidget$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val widgetIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.removeWidget(widgetIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              LauncherApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.updateWidgetSize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val widgetIdArg = args[0] as Long
            val minWidthDpArg = args[1] as Long
            val minHeightDpArg = args[2] as Long
            val maxWidthDpArg = args[3] as Long
            val maxHeightDpArg = args[4] as Long
            val wrapped: List<Any?> = try {
              api.updateWidgetSize(widgetIdArg, minWidthDpArg, minHeightDpArg, maxWidthDpArg, maxHeightDpArg)
              listOf(null)
            } catch (exception: Throwable) {
              LauncherApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.installedIconPacks$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.installedIconPacks{ result: Result<Map<String, String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LauncherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.setIconPack$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String?
            api.setIconPack(packageNameArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(LauncherApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.openIntent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val actionArg = args[0] as String
            val uriArg = args[1] as String?
            val typeArg = args[2] as String?
            val wrapped: List<Any?> = try {
              listOf(api.openIntent(actionArg, uriArg, typeArg))
            } catch (exception: Throwable) {
              LauncherApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.canRecognizeSpeech$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.canRecognizeSpeech{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LauncherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.LauncherHostApi.recognizeSpeech$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val promptArg = args[0] as String?
            api.recognizeSpeech(promptArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(LauncherApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(LauncherApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Implemented in Dart by `AppList`. Native pushes the *full* list on every
 * change (install / uninstall / update / suspend / profile switch) and Dart
 * swaps it wholesale — no deltas, no merge logic, no way to drift out of sync
 * with the system.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class LauncherFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by LauncherFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      LauncherApiPigeonCodec()
    }
  }
  fun onAppsChanged(eventArg: AppChangeEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.g_launcher.LauncherFlutterApi.onAppsChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(LauncherApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
