// Autogenerated from Pigeon (v27.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Why the app list changed. Native pushes the FULL list every time, so this is
/// informational — nothing on the Dart side merges deltas.
enum AppChangeReason {
  added,
  removed,
  changed,
  availabilityChanged,
}

/// The shape an icon is forced into.
///
/// roundedSquare + a cornerRadius float covers most distros: 0.0 is square,
/// 0.22 the default, 0.5 a circle. squircle and teardrop stay separate because
/// they are genuinely different curves — a rounded rect cannot fake a
/// superellipse, and the eye picks that up across a grid of 40 icons.
enum IconTreatment {
  circle,
  squircle,
  roundedSquare,
  square,
  teardrop,
  original,
}

/// One launchable activity, for one user profile.
///
/// [componentKey] is the stable identity used everywhere: layout rows, icon
/// cache keys, folder membership, usage counts. Format is
/// "packageName/className#userSerial", and it is opaque to Dart — never
/// reconstruct it by hand.
class AppEntry {
  AppEntry({
    required this.componentKey,
    required this.packageName,
    required this.className,
    required this.userSerial,
    required this.label,
    required this.updateToken,
    required this.isWorkProfile,
    required this.isSuspended,
    required this.isSystem,
    required this.category,
    required this.isGame,
  });

  String componentKey;

  String packageName;

  String className;

  int userSerial;

  String label;

  /// Changes whenever the app is updated or reinstalled. Part of the icon cache
  /// key, and that is its ONLY job — it is not a version number. (It used to be
  /// called versionCode. It never was one: getting a real version code needs
  /// QUERY_ALL_PACKAGES, which we refuse to ship.)
  int updateToken;

  bool isWorkProfile;

  bool isSuspended;

  bool isSystem;

  /// `ApplicationInfo.category` — the manifest's own `android:appCategory`.
  /// -1 (CATEGORY_UNDEFINED) when the app declares none, which is most of them,
  /// and always -1 below API 26 where the field does not exist.
  ///
  /// APPENDED, not inserted: field order is the decode index, so adding to the
  /// END keeps AppEntry on codec 131 with every existing index unmoved.
  int category;

  /// True when the app is a game. Reads the modern category first, then falls
  /// back to the legacy `FLAG_IS_GAME` for apps that predate the category and
  /// never set it — a lot of the games actually installed on a budget phone.
  bool isGame;

  List<Object?> _toList() {
    return <Object?>[
      componentKey,
      packageName,
      className,
      userSerial,
      label,
      updateToken,
      isWorkProfile,
      isSuspended,
      isSystem,
      category,
      isGame,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppEntry decode(Object result) {
    result as List<Object?>;
    return AppEntry(
      componentKey: result[0]! as String,
      packageName: result[1]! as String,
      className: result[2]! as String,
      userSerial: result[3]! as int,
      label: result[4]! as String,
      updateToken: result[5]! as int,
      isWorkProfile: result[6]! as bool,
      isSuspended: result[7]! as bool,
      isSystem: result[8]! as bool,
      category: result[9]! as int,
      isGame: result[10]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppEntry || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(componentKey, other.componentKey) && _deepEquals(packageName, other.packageName) && _deepEquals(className, other.className) && _deepEquals(userSerial, other.userSerial) && _deepEquals(label, other.label) && _deepEquals(updateToken, other.updateToken) && _deepEquals(isWorkProfile, other.isWorkProfile) && _deepEquals(isSuspended, other.isSuspended) && _deepEquals(isSystem, other.isSystem) && _deepEquals(category, other.category) && _deepEquals(isGame, other.isGame);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppEntry(componentKey: $componentKey, packageName: $packageName, className: $className, userSerial: $userSerial, label: $label, updateToken: $updateToken, isWorkProfile: $isWorkProfile, isSuspended: $isSuspended, isSystem: $isSystem, category: $category, isGame: $isGame)';
  }
}

class AppChangeEvent {
  AppChangeEvent({
    required this.reason,
    required this.apps,
  });

  AppChangeReason reason;

  List<AppEntry> apps;

  List<Object?> _toList() {
    return <Object?>[
      reason,
      apps,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppChangeEvent decode(Object result) {
    result as List<Object?>;
    return AppChangeEvent(
      reason: result[0]! as AppChangeReason,
      apps: (result[1]! as List<Object?>).cast<AppEntry>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppChangeEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(reason, other.reason) && _deepEquals(apps, other.apps);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppChangeEvent(reason: $reason, apps: $apps)';
  }
}

/// The icon half of a ThemeSpec.
class IconStyle {
  IconStyle({
    required this.treatment,
    required this.cornerRadius,
    required this.foregroundScale,
    this.backgroundColor,
    this.monochromeTint,
    this.heroPack,
    this.backgroundGradientEnd,
    this.gradientAngle,
    this.brandPack,
    this.brandTreatment,
  });

  IconTreatment treatment;

  /// Fraction of icon size, for roundedSquare. 0.0 = square, 0.5 = circle.
  /// A float rather than more enum cases on purpose: a distro whose icons are
  /// slightly squarer than KDE's should be a CDN theme edit, not a Play release.
  double cornerRadius;

  /// <1 insets the glyph inside the shape. Papirus-ish sets want ~0.72.
  double foregroundScale;

  /// null = keep the app's own adaptive background layer.
  /// Set = flat fill, which is what makes an icon set feel coherent rather than
  /// a bag of vendor colours. ARGB int.
  int? backgroundColor;

  /// null = draw the app's real coloured foreground.
  /// Set = force the monochrome layer, tinted. Degrades to the coloured
  /// foreground when an app ships no monochrome layer — which is most of them.
  int? monochromeTint;

  /// Hand-crafted icon pack that OVERRIDES the generator, e.g. "yaru".
  /// ~40-60 icons: the ones that define the distro (Files, Terminal, Settings,
  /// Software) plus the common third-party apps people actually look at.
  ///
  /// null = generator only. Part of the cache key.
  String? heroPack;

  /// The far end of a background GRADIENT, as ARGB. Null = flat fill.
  ///
  /// APPENDED, not inserted — same rule AppEntry.category follows. Field order
  /// is the decode index, so adding at the END keeps IconStyle on codec 133
  /// with every existing index unmoved.
  ///
  /// [backgroundColor] is the near end, so a gradient REQUIRES it: end set with
  /// backgroundColor null means "no flat fill", and there is nothing to grade
  /// from, so the renderer keeps the app's own adaptive background and ignores
  /// this. That rule lives in IconRenderer.fillBackground and nowhere else.
  int? backgroundGradientEnd;

  /// Gradient direction in degrees, rotating from top-to-bottom (0) toward
  /// left-to-right (90). 45 is the top-left-to-bottom-right diagonal that most
  /// desktop icon sets use. Ignored when [backgroundGradientEnd] is null.
  ///
  /// Nullable rather than defaulted so an existing theme.json with no gradient
  /// block parses unchanged; the renderer substitutes 45.
  double? gradientAngle;

  /// CC0 brand-glyph pack, e.g. "simple-icons". The HEAD of the icon pipeline:
  /// a package-name map to a single 24x24 SVG path plus the brand's own hex.
  ///
  /// Sits BELOW [heroPack] in the lookup and above the generator. Hero art is
  /// hand-drawn for one distro and wins; a brand glyph is shared across every
  /// theme and only says "this is WhatsApp", not "this is Yaru's WhatsApp".
  ///
  /// null = skip the brand layer entirely. Part of the cache key.
  String? brandPack;

  /// How a brand glyph is coloured. "brandPlate" (default) fills the shape with
  /// the brand's own hex and draws the glyph in whichever of white/near-black
  /// reads on it — WhatsApp stays green and stays recognisable. "themePlate"
  /// fills with the theme's own background (flat or graded) and draws the glyph
  /// in the brand hex, so the whole grid reads as one set at the cost of some
  /// recognisability. Yaru does the first; Papirus-style sets do the second.
  ///
  /// A STRING, NOT AN ENUM, AND THAT IS DELIBERATE. Pigeon numbers enums before
  /// classes, so declaring a third enum would take codec 131 and shove AppEntry,
  /// AppChangeEvent and IconStyle each up by one — silently repartitioning the
  /// wire format this file's header pins down. Appending a nullable String to an
  /// existing class costs nothing. Unknown values degrade to "brandPlate", same
  /// contract as ShellKind.parse and the icon treatment.
  String? brandTreatment;

  List<Object?> _toList() {
    return <Object?>[
      treatment,
      cornerRadius,
      foregroundScale,
      backgroundColor,
      monochromeTint,
      heroPack,
      backgroundGradientEnd,
      gradientAngle,
      brandPack,
      brandTreatment,
    ];
  }

  Object encode() {
    return _toList();  }

  static IconStyle decode(Object result) {
    result as List<Object?>;
    return IconStyle(
      treatment: result[0]! as IconTreatment,
      cornerRadius: result[1]! as double,
      foregroundScale: result[2]! as double,
      backgroundColor: result[3] as int?,
      monochromeTint: result[4] as int?,
      heroPack: result[5] as String?,
      backgroundGradientEnd: result[6] as int?,
      gradientAngle: result[7] as double?,
      brandPack: result[8] as String?,
      brandTreatment: result[9] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! IconStyle || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(treatment, other.treatment) && _deepEquals(cornerRadius, other.cornerRadius) && _deepEquals(foregroundScale, other.foregroundScale) && _deepEquals(backgroundColor, other.backgroundColor) && _deepEquals(monochromeTint, other.monochromeTint) && _deepEquals(heroPack, other.heroPack) && _deepEquals(backgroundGradientEnd, other.backgroundGradientEnd) && _deepEquals(gradientAngle, other.gradientAngle) && _deepEquals(brandPack, other.brandPack) && _deepEquals(brandTreatment, other.brandTreatment);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'IconStyle(treatment: $treatment, cornerRadius: $cornerRadius, foregroundScale: $foregroundScale, backgroundColor: $backgroundColor, monochromeTint: $monochromeTint, heroPack: $heroPack, backgroundGradientEnd: $backgroundGradientEnd, gradientAngle: $gradientAngle, brandPack: $brandPack, brandTreatment: $brandTreatment)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is AppChangeReason) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is IconTreatment) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is AppEntry) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is AppChangeEvent) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is IconStyle) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : AppChangeReason.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : IconTreatment.values[value];
      case 131:
        return AppEntry.decode(readValue(buffer)!);
      case 132:
        return AppChangeEvent.decode(readValue(buffer)!);
      case 133:
        return IconStyle.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Implemented by `LauncherHostApiImpl`, constructed in
/// `LauncherApplication.onCreate` against the warmed engine.
///
/// `@async` marks the methods whose Kotlin side takes a callback instead of
/// returning: anything that touches disk, decodes a bitmap, or hits the package
/// manager cold. Everything else is a straight synchronous call. Getting this
/// wrong does not fail to compile — it silently moves work onto the platform
/// thread — so the four below are exactly the four that are async today.
class LauncherHostApi {
  /// Constructor for [LauncherHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  LauncherHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// The full launchable-app list. Served from cache when warm, refreshed off
  /// the main thread when cold.
  Future<List<AppEntry>> getInstalledApps() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_launcher.LauncherHostApi.getInstalledApps$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<AppEntry>();
  }

  /// [sourceLeft]..[sourceBottom] are the icon's on-screen rect in logical
  /// pixels, so the system can expand the opening app FROM the icon. All null =
  /// no animation origin.
  Future<void> launchApp(String componentKey, double? sourceLeft, double? sourceTop, double? sourceRight, double? sourceBottom) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_launcher.LauncherHostApi.launchApp$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[componentKey, sourceLeft, sourceTop, sourceRight, sourceBottom]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> openAppInfo(String componentKey) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_launcher.LauncherHostApi.openAppInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[componentKey]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Refused silently for apps that cannot be uninstalled (system, work
  /// profile) — the Dart side hides the option rather than relying on this.
  Future<void> requestUninstall(String componentKey) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_launcher.LauncherHostApi.requestUninstall$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[componentKey]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Swap the active icon theme. Invalidates the in-memory icon cache; the DISK
  /// cache is kept, so switching back to a theme you used before is instant.
  ///
  /// [themeId] is part of every cache key. Change the style without changing the
  /// id and you will serve stale icons — so version the id ("ubuntu-24-04.v2")
  /// whenever you edit a theme's icon block.
  Future<void> setIconTheme(String themeId, IconStyle style) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_launcher.LauncherHostApi.setIconTheme$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[themeId, style]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// PNG bytes for one icon at one size, under the active theme.
  /// Null if the component vanished (uninstalled mid-scroll).
  ///
  /// Memory LRU -> disk -> render. The render path is the only slow one, and it
  /// runs off the main thread.
  Future<Uint8List?> getIcon(String componentKey, int sizePx) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_launcher.LauncherHostApi.getIcon$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[componentKey, sizePx]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as Uint8List?;
  }

  /// Nukes memory + disk. For a "rebuild icon cache" button in Settings.
  Future<void> clearIconCache() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_launcher.LauncherHostApi.clearIconCache$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Are we the home app right now? Drives the "Set as default" banner.
  Future<bool> isDefaultLauncher() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_launcher.LauncherHostApi.isDefaultLauncher$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Opens Android's Home-app picker.
  ///
  /// NOT RoleManager. RoleManager gives a prettier in-app dialog but needs an
  /// Activity + result plumbing, and several OEMs (Samsung, Xiaomi) intercept
  /// or ignore it anyway. ACTION_HOME_SETTINGS is boring and works everywhere.
  Future<void> requestDefaultLauncher() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_launcher.LauncherHostApi.requestDefaultLauncher$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Sets the REAL system wallpaper.
  ///
  /// [source] is "asset:<path>" (a theme preset) or a content:// URI the user
  /// picked. Returns false on failure — a bad image must not take the launcher
  /// down; the user simply keeps the wallpaper they had.
  Future<bool> setWallpaper(String source, bool applyToLock) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_launcher.LauncherHostApi.setWallpaper$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[source, applyToLock]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Rotates the wallpaper, desktop-style.
  ///
  /// [minutes] is CLAMPED TO 15 — WorkManager's hard floor. Do not offer a
  /// shorter interval in the UI and quietly deliver fifteen; lying about a
  /// setting is worse than not having it.
  Future<void> scheduleWallpaperRotation(int minutes, List<String> sources, bool applyToLock) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_launcher.LauncherHostApi.scheduleWallpaperRotation$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[minutes, sources, applyToLock]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> cancelWallpaperRotation() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_launcher.LauncherHostApi.cancelWallpaperRotation$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Is the gesture accessibility service actually enabled?
  ///
  /// Checked live rather than cached: the user can revoke it in system settings
  /// at any moment, and a launcher whose gestures silently stopped working — with
  /// no explanation — is a launcher people give up on.
  Future<bool> isGestureServiceEnabled() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_launcher.LauncherHostApi.isGestureServiceEnabled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Opens Android's accessibility settings so the user can enable it.
  Future<void> openAccessibilitySettings() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_launcher.LauncherHostApi.openAccessibilitySettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// "notifications" | "quickSettings" | "lockScreen" | "recents".
  /// Returns false when the service is off or the action is unsupported.
  /// NEVER throws — a gesture that crashes the home screen is unforgivable.
  Future<bool> performGlobalAction(String action) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_launcher.LauncherHostApi.performGlobalAction$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[action]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Copy the CURRENT system wallpaper aside, once, before a theme first
  /// replaces it. Returns true when a stash now exists.
  ///
  /// Best effort by necessity: reading the wallpaper back has been progressively
  /// restricted (Android 13+ limits `getWallpaperFile` for apps that did not set
  /// it), so on some devices this simply cannot succeed. It returns false rather
  /// than throwing, and the Dart side hides "restore" instead of offering a
  /// button that would not work — a restore that silently fails is worse than no
  /// restore.
  Future<bool> stashWallpaper() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_launcher.LauncherHostApi.stashWallpaper$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Is there a stash to go back to? Drives whether the UI offers a restore.
  Future<bool> hasStashedWallpaper() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_launcher.LauncherHostApi.hasStashedWallpaper$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Put the stashed wallpaper back on both home and lock, and drop the stash.
  /// False when there was nothing stashed or the write failed.
  Future<bool> restoreWallpaper() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_launcher.LauncherHostApi.restoreWallpaper$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// Deep-link into a real Android settings screen instead of reimplementing it.
  /// [action] is a Settings.ACTION_* string, e.g.
  /// "android.settings.APPLICATION_DETAILS_SETTINGS".
  ///
  /// Reimplementing OS settings screens is how launchers rot: the OEM changes
  /// something and your copy is quietly wrong forever.
  Future<void> openAndroidSettings(String action) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_launcher.LauncherHostApi.openAndroidSettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[action]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

/// Implemented in Dart by `AppList`. Native pushes the *full* list on every
/// change (install / uninstall / update / suspend / profile switch) and Dart
/// swaps it wholesale — no deltas, no merge logic, no way to drift out of sync
/// with the system.
abstract class LauncherFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onAppsChanged(AppChangeEvent event);

  static void setUp(LauncherFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.g_launcher.LauncherFlutterApi.onAppsChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AppChangeEvent arg_event = args[0]! as AppChangeEvent;
          try {
            api.onAppsChanged(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
