// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.mindhunter.g_recovery.storage

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object StorageApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * The primary shared volume. Codec 129.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class VolumeInfo (
  /**
   * From StatFs on the data partition.
   *
   * NOT the number on the box. A 256 GB phone reports around 234 GB usable
   * after the filesystem, the system image and the vendor partition take their
   * share, and a user comparing against Settings must see the same figure we
   * do, which is this one.
   */
  val totalBytes: Long,
  val freeBytes: Long,
  /**
   * total minus free. Includes the OS and every app's private data, so it is
   * always larger than the sum of what the categories below can see.
   */
  val usedBytes: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VolumeInfo {
      val totalBytes = pigeonVar_list[0] as Long
      val freeBytes = pigeonVar_list[1] as Long
      val usedBytes = pigeonVar_list[2] as Long
      return VolumeInfo(totalBytes, freeBytes, usedBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      totalBytes,
      freeBytes,
      usedBytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VolumeInfo
    return StorageApiPigeonUtils.deepEquals(this.totalBytes, other.totalBytes) && StorageApiPigeonUtils.deepEquals(this.freeBytes, other.freeBytes) && StorageApiPigeonUtils.deepEquals(this.usedBytes, other.usedBytes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.totalBytes)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.freeBytes)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.usedBytes)
    return result
  }
  override fun toString(): String {
    return "VolumeInfo(totalBytes=$totalBytes, freeBytes=$freeBytes, usedBytes=$usedBytes)"
  }
}

/**
 * One media kind. Codec 130.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class KindUsage (
  /**
   * "image" | "video" | "audio" | "document" | "other". A String, because an
   * enum here would renumber the whole schema.
   */
  val kind: String,
  val itemCount: Long,
  val totalBytes: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KindUsage {
      val kind = pigeonVar_list[0] as String
      val itemCount = pigeonVar_list[1] as Long
      val totalBytes = pigeonVar_list[2] as Long
      return KindUsage(kind, itemCount, totalBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      kind,
      itemCount,
      totalBytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as KindUsage
    return StorageApiPigeonUtils.deepEquals(this.kind, other.kind) && StorageApiPigeonUtils.deepEquals(this.itemCount, other.itemCount) && StorageApiPigeonUtils.deepEquals(this.totalBytes, other.totalBytes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.kind)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.itemCount)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.totalBytes)
    return result
  }
  override fun toString(): String {
    return "KindUsage(kind=$kind, itemCount=$itemCount, totalBytes=$totalBytes)"
  }
}

/**
 * One folder, as MediaStore reports it. Codec 131.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class FolderUsage (
  /** The RELATIVE_PATH value, for example "DCIM/Camera/". */
  val path: String,
  /** The last meaningful segment, for display. */
  val label: String,
  val itemCount: Long,
  val totalBytes: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FolderUsage {
      val path = pigeonVar_list[0] as String
      val label = pigeonVar_list[1] as String
      val itemCount = pigeonVar_list[2] as Long
      val totalBytes = pigeonVar_list[3] as Long
      return FolderUsage(path, label, itemCount, totalBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      path,
      label,
      itemCount,
      totalBytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as FolderUsage
    return StorageApiPigeonUtils.deepEquals(this.path, other.path) && StorageApiPigeonUtils.deepEquals(this.label, other.label) && StorageApiPigeonUtils.deepEquals(this.itemCount, other.itemCount) && StorageApiPigeonUtils.deepEquals(this.totalBytes, other.totalBytes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.path)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.label)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.itemCount)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.totalBytes)
    return result
  }
  override fun toString(): String {
    return "FolderUsage(path=$path, label=$label, itemCount=$itemCount, totalBytes=$totalBytes)"
  }
}

/**
 * One year, for the age histogram. Codec 132.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AgeBucket (
  val year: Long,
  val itemCount: Long,
  val totalBytes: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AgeBucket {
      val year = pigeonVar_list[0] as Long
      val itemCount = pigeonVar_list[1] as Long
      val totalBytes = pigeonVar_list[2] as Long
      return AgeBucket(year, itemCount, totalBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      year,
      itemCount,
      totalBytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AgeBucket
    return StorageApiPigeonUtils.deepEquals(this.year, other.year) && StorageApiPigeonUtils.deepEquals(this.itemCount, other.itemCount) && StorageApiPigeonUtils.deepEquals(this.totalBytes, other.totalBytes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.year)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.itemCount)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.totalBytes)
    return result
  }
  override fun toString(): String {
    return "AgeBucket(year=$year, itemCount=$itemCount, totalBytes=$totalBytes)"
  }
}

/**
 * A file that is still on the device. Codec 133.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class StorageFile (
  /** Opaque handle. Dart must never parse it. */
  val fileId: String,
  val name: String,
  val kind: String,
  val sizeBytes: Long,
  val relativePath: String? = null,
  val mimeType: String? = null,
  val dateModifiedMillis: Long? = null,
  val durationMillis: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StorageFile {
      val fileId = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val kind = pigeonVar_list[2] as String
      val sizeBytes = pigeonVar_list[3] as Long
      val relativePath = pigeonVar_list[4] as String?
      val mimeType = pigeonVar_list[5] as String?
      val dateModifiedMillis = pigeonVar_list[6] as Long?
      val durationMillis = pigeonVar_list[7] as Long?
      return StorageFile(fileId, name, kind, sizeBytes, relativePath, mimeType, dateModifiedMillis, durationMillis)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      fileId,
      name,
      kind,
      sizeBytes,
      relativePath,
      mimeType,
      dateModifiedMillis,
      durationMillis,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as StorageFile
    return StorageApiPigeonUtils.deepEquals(this.fileId, other.fileId) && StorageApiPigeonUtils.deepEquals(this.name, other.name) && StorageApiPigeonUtils.deepEquals(this.kind, other.kind) && StorageApiPigeonUtils.deepEquals(this.sizeBytes, other.sizeBytes) && StorageApiPigeonUtils.deepEquals(this.relativePath, other.relativePath) && StorageApiPigeonUtils.deepEquals(this.mimeType, other.mimeType) && StorageApiPigeonUtils.deepEquals(this.dateModifiedMillis, other.dateModifiedMillis) && StorageApiPigeonUtils.deepEquals(this.durationMillis, other.durationMillis)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.fileId)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.name)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.kind)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.sizeBytes)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.relativePath)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.mimeType)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.dateModifiedMillis)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.durationMillis)
    return result
  }
  override fun toString(): String {
    return "StorageFile(fileId=$fileId, name=$name, kind=$kind, sizeBytes=$sizeBytes, relativePath=$relativePath, mimeType=$mimeType, dateModifiedMillis=$dateModifiedMillis, durationMillis=$durationMillis)"
  }
}

/**
 * Everything the Storage tab draws on open. Codec 134.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class StorageOverview (
  val volume: VolumeInfo,
  val kinds: List<KindUsage>,
  /**
   * Largest first, capped natively. A phone can have hundreds of folders and a
   * treemap of hundreds of rectangles is a texture, not information.
   */
  val folders: List<FolderUsage>,
  val ages: List<AgeBucket>,
  /**
   * The total this overview can actually account for.
   *
   * ALWAYS LESS THAN [VolumeInfo.usedBytes], and the gap is not an error. It is
   * the OS, app code, and every app's private directory, none of which
   * MediaStore indexes and none of which any app can enumerate. The UI shows
   * the gap as its own segment rather than quietly inflating a category, which
   * is what a cleaner app does to make its numbers look bigger.
   */
  val indexedBytes: Long,
  val indexedCount: Long,
  /** False when the index was truncated for time. The figures are then a floor. */
  val complete: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StorageOverview {
      val volume = pigeonVar_list[0] as VolumeInfo
      val kinds = pigeonVar_list[1] as List<KindUsage>
      val folders = pigeonVar_list[2] as List<FolderUsage>
      val ages = pigeonVar_list[3] as List<AgeBucket>
      val indexedBytes = pigeonVar_list[4] as Long
      val indexedCount = pigeonVar_list[5] as Long
      val complete = pigeonVar_list[6] as Boolean
      return StorageOverview(volume, kinds, folders, ages, indexedBytes, indexedCount, complete)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      volume,
      kinds,
      folders,
      ages,
      indexedBytes,
      indexedCount,
      complete,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as StorageOverview
    return StorageApiPigeonUtils.deepEquals(this.volume, other.volume) && StorageApiPigeonUtils.deepEquals(this.kinds, other.kinds) && StorageApiPigeonUtils.deepEquals(this.folders, other.folders) && StorageApiPigeonUtils.deepEquals(this.ages, other.ages) && StorageApiPigeonUtils.deepEquals(this.indexedBytes, other.indexedBytes) && StorageApiPigeonUtils.deepEquals(this.indexedCount, other.indexedCount) && StorageApiPigeonUtils.deepEquals(this.complete, other.complete)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.volume)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.kinds)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.folders)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.ages)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.indexedBytes)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.indexedCount)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.complete)
    return result
  }
  override fun toString(): String {
    return "StorageOverview(volume=$volume, kinds=$kinds, folders=$folders, ages=$ages, indexedBytes=$indexedBytes, indexedCount=$indexedCount, complete=$complete)"
  }
}

/**
 * A filter. Codec 135.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class StorageQuerySpec (
  /** Empty means every kind. */
  val kinds: List<String>,
  val limit: Long,
  val minBytes: Long? = null,
  val olderThanDays: Long? = null,
  val folderPrefix: String? = null,
  val nameContains: String? = null,
  /**
   * "newest" | "oldest" | "largest" | "smallest" | "name"
   *
   * SORTED NATIVELY, and it has to be. The query returns at most [limit] rows,
   * so ordering in Dart afterwards would sort the page rather than the library:
   * asking for smallest first would hand back the smallest of the 400 largest,
   * which is wrong in a way nobody notices until they trust it.
   *
   * A String rather than an enum, matching every other field here: an enum
   * numbers before classes and adding a sixth order would renumber every class
   * in the schema.
   */
  val sort: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StorageQuerySpec {
      val kinds = pigeonVar_list[0] as List<String>
      val limit = pigeonVar_list[1] as Long
      val minBytes = pigeonVar_list[2] as Long?
      val olderThanDays = pigeonVar_list[3] as Long?
      val folderPrefix = pigeonVar_list[4] as String?
      val nameContains = pigeonVar_list[5] as String?
      val sort = pigeonVar_list[6] as String
      return StorageQuerySpec(kinds, limit, minBytes, olderThanDays, folderPrefix, nameContains, sort)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      kinds,
      limit,
      minBytes,
      olderThanDays,
      folderPrefix,
      nameContains,
      sort,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as StorageQuerySpec
    return StorageApiPigeonUtils.deepEquals(this.kinds, other.kinds) && StorageApiPigeonUtils.deepEquals(this.limit, other.limit) && StorageApiPigeonUtils.deepEquals(this.minBytes, other.minBytes) && StorageApiPigeonUtils.deepEquals(this.olderThanDays, other.olderThanDays) && StorageApiPigeonUtils.deepEquals(this.folderPrefix, other.folderPrefix) && StorageApiPigeonUtils.deepEquals(this.nameContains, other.nameContains) && StorageApiPigeonUtils.deepEquals(this.sort, other.sort)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.kinds)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.limit)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.minBytes)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.olderThanDays)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.folderPrefix)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.nameContains)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.sort)
    return result
  }
  override fun toString(): String {
    return "StorageQuerySpec(kinds=$kinds, limit=$limit, minBytes=$minBytes, olderThanDays=$olderThanDays, folderPrefix=$folderPrefix, nameContains=$nameContains, sort=$sort)"
  }
}

/**
 * Codec 136.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class StorageQueryResult (
  /**
   * Capped by [StorageQuerySpec.limit]. [matchCount] is the real total, so the
   * headline figure never lies just because the list was truncated.
   */
  val files: List<StorageFile>,
  val matchCount: Long,
  val matchBytes: Long,
  /**
   * Breakdown of the MATCH, not of the device. This is what makes a query an
   * answer with a shape rather than a list.
   */
  val folders: List<FolderUsage>,
  val ages: List<AgeBucket>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StorageQueryResult {
      val files = pigeonVar_list[0] as List<StorageFile>
      val matchCount = pigeonVar_list[1] as Long
      val matchBytes = pigeonVar_list[2] as Long
      val folders = pigeonVar_list[3] as List<FolderUsage>
      val ages = pigeonVar_list[4] as List<AgeBucket>
      return StorageQueryResult(files, matchCount, matchBytes, folders, ages)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      files,
      matchCount,
      matchBytes,
      folders,
      ages,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as StorageQueryResult
    return StorageApiPigeonUtils.deepEquals(this.files, other.files) && StorageApiPigeonUtils.deepEquals(this.matchCount, other.matchCount) && StorageApiPigeonUtils.deepEquals(this.matchBytes, other.matchBytes) && StorageApiPigeonUtils.deepEquals(this.folders, other.folders) && StorageApiPigeonUtils.deepEquals(this.ages, other.ages)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.files)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.matchCount)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.matchBytes)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.folders)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.ages)
    return result
  }
  override fun toString(): String {
    return "StorageQueryResult(files=$files, matchCount=$matchCount, matchBytes=$matchBytes, folders=$folders, ages=$ages)"
  }
}

/**
 * Codec 137.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class StorageOutcome (
  val fileId: String,
  /**
   * "deleted" | "trashed" | "needsConsent" | "notFound" | "denied" | "failed"
   *
   * `trashed` is distinct from `deleted` on purpose: the default action moves a
   * file to the OS trash where it is recoverable for thirty days, and telling
   * the user it was deleted when it was not would be the same overclaim this
   * app refuses to make in the other direction.
   */
  val status: String,
  val detail: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StorageOutcome {
      val fileId = pigeonVar_list[0] as String
      val status = pigeonVar_list[1] as String
      val detail = pigeonVar_list[2] as String
      return StorageOutcome(fileId, status, detail)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      fileId,
      status,
      detail,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as StorageOutcome
    return StorageApiPigeonUtils.deepEquals(this.fileId, other.fileId) && StorageApiPigeonUtils.deepEquals(this.status, other.status) && StorageApiPigeonUtils.deepEquals(this.detail, other.detail)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.fileId)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.status)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.detail)
    return result
  }
  override fun toString(): String {
    return "StorageOutcome(fileId=$fileId, status=$status, detail=$detail)"
  }
}

/**
 * One thing inside a folder. Codec 138.
 *
 * Appended last, so nothing before it renumbers.
 *
 * ─── THIS IS NOT StorageFile ─────────────────────────────────────────────────
 *
 * StorageFile is a MediaStore row: indexed, with a kind and a media id, and
 * reachable by every other method here. This is what is actually on disk, which
 * is a different and larger set. MediaStore never saw the zip a file manager
 * dropped into Download, and it has no idea that Android/data exists.
 *
 * Keeping them apart is the point. A browser that could only show indexed files
 * would teach a false picture of the filesystem, which is the one thing this
 * screen exists not to do.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DirEntry (
  val path: String,
  val name: String,
  val isDirectory: Boolean,
  /**
   * Zero for a directory. Summing a tree means walking it, and a browser that
   * stalled on every folder to total its contents would be unusable on a
   * phone.
   */
  val sizeBytes: Long,
  val modifiedMillis: Long,
  /**
   * How many things are directly inside, or null when it could not be read.
   *
   * Null is meaningful here and is not the same as zero: an empty folder and a
   * folder the system refuses to open look identical without it.
   */
  val childCount: Long? = null,
  /**
   * False for the folders Android will not open, chiefly Android/data and
   * Android/obb from Android 11 onward.
   *
   * Shown rather than hidden. A person who cannot see the locked door does not
   * learn that it is locked, and this is the same folder that makes deleted
   * chat messages unrecoverable.
   */
  val readable: Boolean,
  /**
   * Starts with a dot. Listed, but behind a toggle, because a browser that
   * silently omits things teaches the wrong shape of the filesystem.
   */
  val hidden: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DirEntry {
      val path = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val isDirectory = pigeonVar_list[2] as Boolean
      val sizeBytes = pigeonVar_list[3] as Long
      val modifiedMillis = pigeonVar_list[4] as Long
      val childCount = pigeonVar_list[5] as Long?
      val readable = pigeonVar_list[6] as Boolean
      val hidden = pigeonVar_list[7] as Boolean
      return DirEntry(path, name, isDirectory, sizeBytes, modifiedMillis, childCount, readable, hidden)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      path,
      name,
      isDirectory,
      sizeBytes,
      modifiedMillis,
      childCount,
      readable,
      hidden,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DirEntry
    return StorageApiPigeonUtils.deepEquals(this.path, other.path) && StorageApiPigeonUtils.deepEquals(this.name, other.name) && StorageApiPigeonUtils.deepEquals(this.isDirectory, other.isDirectory) && StorageApiPigeonUtils.deepEquals(this.sizeBytes, other.sizeBytes) && StorageApiPigeonUtils.deepEquals(this.modifiedMillis, other.modifiedMillis) && StorageApiPigeonUtils.deepEquals(this.childCount, other.childCount) && StorageApiPigeonUtils.deepEquals(this.readable, other.readable) && StorageApiPigeonUtils.deepEquals(this.hidden, other.hidden)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.path)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.name)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.isDirectory)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.sizeBytes)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.modifiedMillis)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.childCount)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.readable)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.hidden)
    return result
  }
  override fun toString(): String {
    return "DirEntry(path=$path, name=$name, isDirectory=$isDirectory, sizeBytes=$sizeBytes, modifiedMillis=$modifiedMillis, childCount=$childCount, readable=$readable, hidden=$hidden)"
  }
}

/**
 * A mounted volume. Codec 139.
 *
 * ─── NOT VolumeInfo ──────────────────────────────────────────────────────────
 *
 * VolumeInfo is three numbers about the volume an overview describes. This is
 * a volume the phone has, with a name and a path, so it can be listed and
 * opened. A phone with an SD card has two of these and one overview.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class VolumeEntry (
  val id: String,
  /**
   * What the system calls it. "SanDisk SD card" rather than a mount point,
   * because the mount point is a different string on every device.
   */
  val label: String,
  /**
   * Null when the volume is mounted somewhere this app cannot reach, which
   * happens on some OEM builds for USB drives.
   */
  val path: String? = null,
  val totalBytes: Long,
  val freeBytes: Long,
  val removable: Boolean,
  /**
   * Internal storage. There is exactly one, and it is the one the overview
   * already describes.
   */
  val primary: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VolumeEntry {
      val id = pigeonVar_list[0] as String
      val label = pigeonVar_list[1] as String
      val path = pigeonVar_list[2] as String?
      val totalBytes = pigeonVar_list[3] as Long
      val freeBytes = pigeonVar_list[4] as Long
      val removable = pigeonVar_list[5] as Boolean
      val primary = pigeonVar_list[6] as Boolean
      return VolumeEntry(id, label, path, totalBytes, freeBytes, removable, primary)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      label,
      path,
      totalBytes,
      freeBytes,
      removable,
      primary,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VolumeEntry
    return StorageApiPigeonUtils.deepEquals(this.id, other.id) && StorageApiPigeonUtils.deepEquals(this.label, other.label) && StorageApiPigeonUtils.deepEquals(this.path, other.path) && StorageApiPigeonUtils.deepEquals(this.totalBytes, other.totalBytes) && StorageApiPigeonUtils.deepEquals(this.freeBytes, other.freeBytes) && StorageApiPigeonUtils.deepEquals(this.removable, other.removable) && StorageApiPigeonUtils.deepEquals(this.primary, other.primary)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.id)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.label)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.path)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.totalBytes)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.freeBytes)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.removable)
    result = 31 * result + StorageApiPigeonUtils.deepHash(this.primary)
    return result
  }
  override fun toString(): String {
    return "VolumeEntry(id=$id, label=$label, path=$path, totalBytes=$totalBytes, freeBytes=$freeBytes, removable=$removable, primary=$primary)"
  }
}
private open class StorageApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VolumeInfo.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KindUsage.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FolderUsage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AgeBucket.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StorageFile.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StorageOverview.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StorageQuerySpec.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StorageQueryResult.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StorageOutcome.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DirEntry.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VolumeEntry.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is VolumeInfo -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is KindUsage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is FolderUsage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is AgeBucket -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is StorageFile -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is StorageOverview -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is StorageQuerySpec -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is StorageQueryResult -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is StorageOutcome -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is DirEntry -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is VolumeEntry -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface StorageHostApi {
  /** Volume stats plus the MediaStore aggregate. One pass, no directory walk. */
  fun overview(callback: (Result<StorageOverview>) -> Unit)
  fun query(spec: StorageQuerySpec, callback: (Result<StorageQueryResult>) -> Unit)
  /**
   * JPEG preview bytes, downscaled natively. Same reasoning as the recovery
   * thumbnail: Flutter cannot load a content URI, and shipping full size
   * bitmaps across the channel is how a grid runs a phone out of memory.
   *
   * [kind], [name] and [mimeType] are passed IN rather than looked up.
   *
   * Native has only the file id, which carries no type, so deciding how to
   * draw a preview would mean a second MediaStore query per thumbnail: on a
   * scrolling grid, one extra cursor per cell. Dart already holds all three on
   * the StorageFile it is drawing, so handing them over costs nothing and the
   * native side goes straight to the right renderer.
   *
   * Without this the call site hardcoded "image", which meant audio artwork
   * and PDF first pages could never be reached however well they worked.
   */
  fun thumbnail(fileId: String, maxPixels: Long, kind: String, name: String?, mimeType: String?, callback: (Result<ByteArray?>) -> Unit)
  /**
   * Moves files to the OS trash by default, where the user has thirty days to
   * change their mind. [permanent] skips that.
   */
  fun remove(fileIds: List<String>, permanent: Boolean, callback: (Result<List<StorageOutcome>>) -> Unit)
  /**
   * A playable content URI for this file, or null if it is no longer listed.
   *
   * The one thing video playback cannot be done without. VideoPlayerController
   * takes a content URI and nothing else will do: Dart cannot open a
   * MediaStore row by id, and the file path behind it is unreadable under
   * scoped storage even when the row is perfectly readable.
   *
   * A STRING, not a typed URI, because Pigeon has no URI and because the same
   * value is handed straight back to the platform for the external chooser.
   */
  fun contentUri(fileId: String, callback: (Result<String?>) -> Unit)
  /**
   * Raw bytes, for the formats this app renders itself.
   *
   * Text and CSV, and nothing larger than [maxBytes]. Dart cannot read a
   * content URI on its own, so the bytes have to cross the bridge, and a
   * three hundred megabyte log decoded into a Dart string would take the app
   * down on a phone that had every right to survive opening it.
   *
   * Returns null when the file is missing or larger than the cap. The caller
   * distinguishes the two by checking the size it already has.
   */
  fun readBytes(fileId: String, maxBytes: Long, callback: (Result<ByteArray?>) -> Unit)
  /**
   * Every mounted volume: internal, and any SD card or USB drive.
   *
   * From StorageManager rather than a guessed path. On a phone with an SD card
   * the second volume has a different id on every device, and hardcoding
   * /storage/sdcard1 was already wrong a decade ago.
   */
  fun volumes(callback: (Result<List<VolumeEntry>>) -> Unit)
  /**
   * What is directly inside a folder.
   *
   * [path] null means the roots: internal storage, plus any SD card or USB
   * volume currently mounted.
   *
   * One level only. A recursive walk is what makes file managers hang on a
   * folder with forty thousand files in it, and nothing on this screen needs
   * more than the level being looked at.
   */
  fun listDirectory(path: String?, callback: (Result<List<DirEntry>>) -> Unit)
  /**
   * Hands the file to whatever app can open it.
   *
   * For the formats with no credible in-app renderer, which on Android means
   * office documents and anything proprietary. Returns false when nothing on
   * the phone can handle the type, so the UI can say that instead of appearing
   * to do nothing.
   *
   * Grants read permission on the URI for the duration of the target activity.
   * Without that flag the chooser opens onto a permission error, which looks
   * like a bug in this app rather than in the one that was launched.
   */
  fun openExternally(fileId: String, callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by StorageHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      StorageApiPigeonCodec()
    }
    /** Sets up an instance of `StorageHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: StorageHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_recovery.StorageHostApi.overview$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.overview{ result: Result<StorageOverview> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(StorageApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(StorageApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_recovery.StorageHostApi.query$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val specArg = args[0] as StorageQuerySpec
            api.query(specArg) { result: Result<StorageQueryResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(StorageApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(StorageApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_recovery.StorageHostApi.thumbnail$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val fileIdArg = args[0] as String
            val maxPixelsArg = args[1] as Long
            val kindArg = args[2] as String
            val nameArg = args[3] as String?
            val mimeTypeArg = args[4] as String?
            api.thumbnail(fileIdArg, maxPixelsArg, kindArg, nameArg, mimeTypeArg) { result: Result<ByteArray?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(StorageApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(StorageApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_recovery.StorageHostApi.remove$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val fileIdsArg = args[0] as List<String>
            val permanentArg = args[1] as Boolean
            api.remove(fileIdsArg, permanentArg) { result: Result<List<StorageOutcome>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(StorageApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(StorageApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_recovery.StorageHostApi.contentUri$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val fileIdArg = args[0] as String
            api.contentUri(fileIdArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(StorageApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(StorageApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_recovery.StorageHostApi.readBytes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val fileIdArg = args[0] as String
            val maxBytesArg = args[1] as Long
            api.readBytes(fileIdArg, maxBytesArg) { result: Result<ByteArray?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(StorageApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(StorageApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_recovery.StorageHostApi.volumes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.volumes{ result: Result<List<VolumeEntry>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(StorageApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(StorageApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_recovery.StorageHostApi.listDirectory$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String?
            api.listDirectory(pathArg) { result: Result<List<DirEntry>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(StorageApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(StorageApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_recovery.StorageHostApi.openExternally$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val fileIdArg = args[0] as String
            api.openExternally(fileIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(StorageApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(StorageApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
