// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.mindhunter.g_launcher.pack

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PackApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * A pack, as the storefront needs to draw it.
 *
 * Deliberately NOT a mirror of Kotlin's `CdnPack`. That type carries the
 * remote path and the signed file list, and a screen that knows the CDN path
 * is a screen that could be tempted to fetch it. This is the presentation
 * subset and nothing more.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PackInfo (
  val packId: String,
  /**
   * "theme", "brand", "hero", "icon".
   *
   * A STRING, NOT AN ENUM, on purpose. Pigeon assigns enum ids positionally,
   * so adding a pack type later would renumber the codec; and a pack type the
   * client does not recognise must degrade to "ignore it", not "fail to
   * parse". Same rule `brandTreatment` follows in the other schema.
   */
  val packType: String,
  val title: String,
  val summary: String,
  /** What the catalogue advertises. */
  val version: Long,
  /** What is on disk. 0 when nothing is installed. */
  val installedVersion: Long,
  val sizeBytes: Long,
  /**
   * "available" | "installed" | "updateAvailable" | "bundled" |
   * "requiresAppUpdate". String for the same reason as [packType].
   *
   * `requiresAppUpdate` is a state and not an error because the action differs:
   * the user must update the app, and a storefront that shows a Get button
   * there is lying to them.
   */
  val state: String,
  /**
   * Whether this device may install it.
   *
   * Resolved NATIVELY against the signed index's entitlement grants and the
   * owned-SKU set, so the rule lives in exactly one place
   * (`CdnIndex.isUnlocked`) rather than being reimplemented in Dart where it
   * would drift. Free packs are always true.
   */
  val unlocked: Boolean,
  /**
   * null = free. PRESENTATION ONLY: it tells the card which price to draw.
   * Ownership is Play's answer and is already folded into [unlocked].
   */
  val sku: String? = null,
  /**
   * The shell this distro draws: "gnome" | "plasma" | "aqua" | "tiling" |
   * "tui". Picks WHICH miniature the card renders.
   *
   * Null on every pack published before this field existed, and the card falls
   * back to the flat rectangle it draws today. Optional the whole way down, so
   * nothing already in the index has to be republished.
   */
  val previewShell: String? = null,
  /**
   * The six palette colours, as "#RRGGBB" or "#AARRGGBB", exactly as they
   * appear in the pack's own theme.json.
   *
   * Strings rather than ints because that is how they are authored, how they
   * travel in the index, and how the panel already stores them. Parsing them
   * once on the Dart side beats three representations of the same colour.
   */
  val previewBgTop: String? = null,
  val previewBgBottom: String? = null,
  val previewBar: String? = null,
  val previewDock: String? = null,
  val previewAccent: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PackInfo {
      val packId = pigeonVar_list[0] as String
      val packType = pigeonVar_list[1] as String
      val title = pigeonVar_list[2] as String
      val summary = pigeonVar_list[3] as String
      val version = pigeonVar_list[4] as Long
      val installedVersion = pigeonVar_list[5] as Long
      val sizeBytes = pigeonVar_list[6] as Long
      val state = pigeonVar_list[7] as String
      val unlocked = pigeonVar_list[8] as Boolean
      val sku = pigeonVar_list[9] as String?
      val previewShell = pigeonVar_list[10] as String?
      val previewBgTop = pigeonVar_list[11] as String?
      val previewBgBottom = pigeonVar_list[12] as String?
      val previewBar = pigeonVar_list[13] as String?
      val previewDock = pigeonVar_list[14] as String?
      val previewAccent = pigeonVar_list[15] as String?
      return PackInfo(packId, packType, title, summary, version, installedVersion, sizeBytes, state, unlocked, sku, previewShell, previewBgTop, previewBgBottom, previewBar, previewDock, previewAccent)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      packId,
      packType,
      title,
      summary,
      version,
      installedVersion,
      sizeBytes,
      state,
      unlocked,
      sku,
      previewShell,
      previewBgTop,
      previewBgBottom,
      previewBar,
      previewDock,
      previewAccent,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PackInfo
    return PackApiPigeonUtils.deepEquals(this.packId, other.packId) && PackApiPigeonUtils.deepEquals(this.packType, other.packType) && PackApiPigeonUtils.deepEquals(this.title, other.title) && PackApiPigeonUtils.deepEquals(this.summary, other.summary) && PackApiPigeonUtils.deepEquals(this.version, other.version) && PackApiPigeonUtils.deepEquals(this.installedVersion, other.installedVersion) && PackApiPigeonUtils.deepEquals(this.sizeBytes, other.sizeBytes) && PackApiPigeonUtils.deepEquals(this.state, other.state) && PackApiPigeonUtils.deepEquals(this.unlocked, other.unlocked) && PackApiPigeonUtils.deepEquals(this.sku, other.sku) && PackApiPigeonUtils.deepEquals(this.previewShell, other.previewShell) && PackApiPigeonUtils.deepEquals(this.previewBgTop, other.previewBgTop) && PackApiPigeonUtils.deepEquals(this.previewBgBottom, other.previewBgBottom) && PackApiPigeonUtils.deepEquals(this.previewBar, other.previewBar) && PackApiPigeonUtils.deepEquals(this.previewDock, other.previewDock) && PackApiPigeonUtils.deepEquals(this.previewAccent, other.previewAccent)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PackApiPigeonUtils.deepHash(this.packId)
    result = 31 * result + PackApiPigeonUtils.deepHash(this.packType)
    result = 31 * result + PackApiPigeonUtils.deepHash(this.title)
    result = 31 * result + PackApiPigeonUtils.deepHash(this.summary)
    result = 31 * result + PackApiPigeonUtils.deepHash(this.version)
    result = 31 * result + PackApiPigeonUtils.deepHash(this.installedVersion)
    result = 31 * result + PackApiPigeonUtils.deepHash(this.sizeBytes)
    result = 31 * result + PackApiPigeonUtils.deepHash(this.state)
    result = 31 * result + PackApiPigeonUtils.deepHash(this.unlocked)
    result = 31 * result + PackApiPigeonUtils.deepHash(this.sku)
    result = 31 * result + PackApiPigeonUtils.deepHash(this.previewShell)
    result = 31 * result + PackApiPigeonUtils.deepHash(this.previewBgTop)
    result = 31 * result + PackApiPigeonUtils.deepHash(this.previewBgBottom)
    result = 31 * result + PackApiPigeonUtils.deepHash(this.previewBar)
    result = 31 * result + PackApiPigeonUtils.deepHash(this.previewDock)
    result = 31 * result + PackApiPigeonUtils.deepHash(this.previewAccent)
    return result
  }
  override fun toString(): String {
    return "PackInfo(packId=$packId, packType=$packType, title=$title, summary=$summary, version=$version, installedVersion=$installedVersion, sizeBytes=$sizeBytes, state=$state, unlocked=$unlocked, sku=$sku, previewShell=$previewShell, previewBgTop=$previewBgTop, previewBgBottom=$previewBgBottom, previewBar=$previewBar, previewDock=$previewDock, previewAccent=$previewAccent)"
  }
}

/**
 * A purchasable bundle, as advertised by the signed index.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BundleInfo (
  val sku: String,
  val title: String,
  val summary: String,
  /**
   * True when the bundle grants every pack, present AND FUTURE. Surfaced as a
   * flag rather than an expanded list because expanding it would quietly break
   * the promise the store listing makes: buy the complete collection and packs
   * that ship later are covered.
   */
  val grantsAll: Boolean,
  /**
   * Explicit grants. Empty when [grantsAll]. May name a pack that has not
   * shipped yet, so a bundle can be announced before its contents are live.
   */
  val grantedPackIds: List<String>,
  val owned: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BundleInfo {
      val sku = pigeonVar_list[0] as String
      val title = pigeonVar_list[1] as String
      val summary = pigeonVar_list[2] as String
      val grantsAll = pigeonVar_list[3] as Boolean
      val grantedPackIds = pigeonVar_list[4] as List<String>
      val owned = pigeonVar_list[5] as Boolean
      return BundleInfo(sku, title, summary, grantsAll, grantedPackIds, owned)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sku,
      title,
      summary,
      grantsAll,
      grantedPackIds,
      owned,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BundleInfo
    return PackApiPigeonUtils.deepEquals(this.sku, other.sku) && PackApiPigeonUtils.deepEquals(this.title, other.title) && PackApiPigeonUtils.deepEquals(this.summary, other.summary) && PackApiPigeonUtils.deepEquals(this.grantsAll, other.grantsAll) && PackApiPigeonUtils.deepEquals(this.grantedPackIds, other.grantedPackIds) && PackApiPigeonUtils.deepEquals(this.owned, other.owned)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PackApiPigeonUtils.deepHash(this.sku)
    result = 31 * result + PackApiPigeonUtils.deepHash(this.title)
    result = 31 * result + PackApiPigeonUtils.deepHash(this.summary)
    result = 31 * result + PackApiPigeonUtils.deepHash(this.grantsAll)
    result = 31 * result + PackApiPigeonUtils.deepHash(this.grantedPackIds)
    result = 31 * result + PackApiPigeonUtils.deepHash(this.owned)
    return result
  }
  override fun toString(): String {
    return "BundleInfo(sku=$sku, title=$title, summary=$summary, grantsAll=$grantsAll, grantedPackIds=$grantedPackIds, owned=$owned)"
  }
}

/**
 * Progress for one in-flight download.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PackProgress (
  val packId: String,
  val bytesDone: Long,
  /**
   * From the SIGNED manifest, so it is a real number rather than a
   * Content-Length the origin can lie about.
   */
  val bytesTotal: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PackProgress {
      val packId = pigeonVar_list[0] as String
      val bytesDone = pigeonVar_list[1] as Long
      val bytesTotal = pigeonVar_list[2] as Long
      return PackProgress(packId, bytesDone, bytesTotal)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      packId,
      bytesDone,
      bytesTotal,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PackProgress
    return PackApiPigeonUtils.deepEquals(this.packId, other.packId) && PackApiPigeonUtils.deepEquals(this.bytesDone, other.bytesDone) && PackApiPigeonUtils.deepEquals(this.bytesTotal, other.bytesTotal)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PackApiPigeonUtils.deepHash(this.packId)
    result = 31 * result + PackApiPigeonUtils.deepHash(this.bytesDone)
    result = 31 * result + PackApiPigeonUtils.deepHash(this.bytesTotal)
    return result
  }
  override fun toString(): String {
    return "PackProgress(packId=$packId, bytesDone=$bytesDone, bytesTotal=$bytesTotal)"
  }
}

/**
 * The outcome of an install attempt.
 *
 * A RESULT OBJECT RATHER THAN A THROWN ERROR, because most of these are not
 * errors. `upToDate` is the common case and must be silent; `noSpace` and
 * `appTooOld` are user-actionable and need different copy; `rejected` means a
 * signature failed and should be reported, never retried; only `failed` is
 * worth a retry button. Collapsing them into an exception produces the
 * "Download failed" dialog that tells nobody anything.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PackResult (
  val packId: String,
  /**
   * "installed" | "upToDate" | "notOffered" | "appTooOld" | "noSpace" |
   * "cancelled" | "rejected" | "notEntitled" | "failed"
   */
  val status: String,
  /**
   * Human-readable, for logs and for the rare case worth showing. Never the
   * primary thing the UI branches on; branch on [status].
   */
  val detail: String,
  val installedVersion: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PackResult {
      val packId = pigeonVar_list[0] as String
      val status = pigeonVar_list[1] as String
      val detail = pigeonVar_list[2] as String
      val installedVersion = pigeonVar_list[3] as Long
      return PackResult(packId, status, detail, installedVersion)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      packId,
      status,
      detail,
      installedVersion,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PackResult
    return PackApiPigeonUtils.deepEquals(this.packId, other.packId) && PackApiPigeonUtils.deepEquals(this.status, other.status) && PackApiPigeonUtils.deepEquals(this.detail, other.detail) && PackApiPigeonUtils.deepEquals(this.installedVersion, other.installedVersion)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PackApiPigeonUtils.deepHash(this.packId)
    result = 31 * result + PackApiPigeonUtils.deepHash(this.status)
    result = 31 * result + PackApiPigeonUtils.deepHash(this.detail)
    result = 31 * result + PackApiPigeonUtils.deepHash(this.installedVersion)
    return result
  }
  override fun toString(): String {
    return "PackResult(packId=$packId, status=$status, detail=$detail, installedVersion=$installedVersion)"
  }
}
private open class PackApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PackInfo.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BundleInfo.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PackProgress.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PackResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PackInfo -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is BundleInfo -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is PackProgress -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is PackResult -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PackHostApi {
  /**
   * Everything the catalogue knows, merged with what is on disk.
   *
   * Reads the CACHED index only. It never touches the network, so the
   * storefront opens instantly and works on a plane. [refreshCatalogue] is the
   * explicit network call.
   */
  fun catalogue(callback: (Result<List<PackInfo>>) -> Unit)
  /** The bundles, with ownership already resolved. */
  fun bundles(callback: (Result<List<BundleInfo>>) -> Unit)
  /**
   * Fetch a newer index if there is one. Returns true when the catalogue
   * changed and the caller should re-read it.
   *
   * Safe to call on every storefront open: it sends an ETag, so the common
   * case is a 304 with no body.
   */
  fun refreshCatalogue(callback: (Result<Boolean>) -> Unit)
  /**
   * Download, verify and install. Progress arrives on [PackFlutterApi].
   *
   * Entitlement is re-checked HERE, natively, immediately before the
   * download. Not because the UI cannot be trusted, but because the UI's copy
   * of the answer can be stale by minutes and a refund is a worse outcome than
   * a redundant check.
   */
  fun installPack(packId: String, callback: (Result<PackResult>) -> Unit)
  /** Stop an in-flight download. Staging is discarded; nothing partial is kept. */
  fun cancelInstall(packId: String, callback: (Result<Unit>) -> Unit)
  /**
   * Remove an installed pack. Refuses the active theme, which would leave the
   * home screen resolving a theme that is no longer on disk.
   */
  fun uninstallPack(packId: String, callback: (Result<Boolean>) -> Unit)
  /**
   * Tell native which SKUs Play says are owned.
   *
   * PUSHED FROM DART, because Play Billing lives in `g_account` on the Dart
   * side and native has no billing client of its own. Native holds the set
   * only to answer `unlocked`; it never decides ownership and never persists
   * it. A restart re-asks Play, which is the only source that can be trusted.
   */
  fun setOwnedSkus(skus: List<String>, callback: (Result<Unit>) -> Unit)
  /**
   * The resolved CDN base URL, written where the headless sync worker can read
   * it. Called once after Remote Config resolves.
   */
  fun setCdnBaseUrl(url: String, callback: (Result<Unit>) -> Unit)
  /**
   * The raw `theme.json` of an installed theme pack, or null when the pack is
   * not on disk (never downloaded, uninstalled, or its files were swept).
   *
   * Returns the BYTES AS TEXT and parses nothing. Dart already owns
   * `ThemeSpec.fromJson`, and a second parser in Kotlin is a second thing to
   * keep in step with the schema — the exact drift that made the icon
   * `IconStyle` data class a hand-written twin of the Pigeon one.
   *
   * Signature verification is NOT repeated here. The pack was verified when it
   * installed; re-verifying on every theme resolve would put an ed25519 check
   * on the home screen's critical path for no additional guarantee, since the
   * file lives in app-private storage.
   */
  fun readInstalledTheme(themeId: String, callback: (Result<String?>) -> Unit)
  /**
   * Absolute path to an installed pack's file directory, or null.
   *
   * Dart needs this because a downloaded theme's wallpapers and logo are FILES,
   * not bundled assets: `AssetImage('wall.jpg')` on an installed theme resolves
   * to nothing and renders an empty box with no error. `ThemeSource` turns this
   * directory into the right ImageProvider per asset.
   *
   * Pack files are BARE FILENAMES by construction (`PackPaths.installedFile`
   * refuses separators), so joining is always one `/` and never a traversal.
   */
  fun installedPackDir(packId: String, callback: (Result<String?>) -> Unit)
  /**
   * Where a pack's `preview.png` can be drawn from, or null when it has none.
   *
   * A `file://` URI once the pack is installed, an https URL from the CDN
   * before it. Display-only bytes that go through Flutter's image cache,
   * never the pack pipeline, so nothing about verification changes.
   *
   * A METHOD rather than a field on [PackInfo], deliberately: that class
   * documents itself as the presentation subset that does NOT carry the CDN
   * path, and a single URL to one image keeps that promise while an appended
   * field carrying `path` would quietly break it. Appended last, which is the
   * safe position, and it is a method so not even the codec moves.
   */
  fun packPreviewUrl(packId: String, callback: (Result<String?>) -> Unit)

  companion object {
    /** The codec used by PackHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PackApiPigeonCodec()
    }
    /** Sets up an instance of `PackHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PackHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.PackHostApi.catalogue$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.catalogue{ result: Result<List<PackInfo>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PackApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PackApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.PackHostApi.bundles$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.bundles{ result: Result<List<BundleInfo>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PackApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PackApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.PackHostApi.refreshCatalogue$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.refreshCatalogue{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PackApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PackApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.PackHostApi.installPack$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packIdArg = args[0] as String
            api.installPack(packIdArg) { result: Result<PackResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PackApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PackApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.PackHostApi.cancelInstall$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packIdArg = args[0] as String
            api.cancelInstall(packIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PackApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PackApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.PackHostApi.uninstallPack$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packIdArg = args[0] as String
            api.uninstallPack(packIdArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PackApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PackApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.PackHostApi.setOwnedSkus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val skusArg = args[0] as List<String>
            api.setOwnedSkus(skusArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PackApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PackApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.PackHostApi.setCdnBaseUrl$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.setCdnBaseUrl(urlArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PackApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PackApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.PackHostApi.readInstalledTheme$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val themeIdArg = args[0] as String
            api.readInstalledTheme(themeIdArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PackApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PackApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.PackHostApi.installedPackDir$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packIdArg = args[0] as String
            api.installedPackDir(packIdArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PackApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PackApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.g_launcher.PackHostApi.packPreviewUrl$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packIdArg = args[0] as String
            api.packPreviewUrl(packIdArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PackApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PackApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class PackFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by PackFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      PackApiPigeonCodec()
    }
  }
  /** Fires on the platform thread during a download, roughly per chunk. */
  fun onPackProgress(progressArg: PackProgress, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.g_launcher.PackFlutterApi.onPackProgress$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(progressArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PackApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /** Fires after a pack lands, so the storefront can re-read without polling. */
  fun onPackInstalled(packIdArg: String, versionArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.g_launcher.PackFlutterApi.onPackInstalled$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(packIdArg, versionArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PackApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
