package com.mindhunter.g_launcher.theme

import java.io.File
import java.security.MessageDigest
import org.bouncycastle.crypto.params.Ed25519PrivateKeyParameters
import org.bouncycastle.crypto.signers.Ed25519Signer
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder

/**
 * PHASE C1 - the tests that make the signature check worth having.
 *
 * A verifier that only ever sees valid input is indistinguishable from `return
 * true`. Every test below except the first one exists to prove a specific way
 * of lying gets caught, and the interesting assertion is always the failure.
 *
 * NO FIXTURE FILES ON DISK, AND THAT IS A CHOICE. The keypair comes from a
 * fixed 32-byte seed and the pack is built in-memory each run, so:
 *   - there are no binary blobs in the repo to go stale against a format change
 *   - the SIGNER is exercised too, which is what the admin panel will have to
 *     reimplement in C4; if the two ever disagree, this test is the reference
 *   - a "tamper one byte" test is a one-line mutation instead of a second
 *     checked-in fixture that has to be regenerated by hand
 *
 * The seed is NOT one of PackKeys.accepted. A test key the shipped app trusts
 * is a backdoor with a unit test attached.
 */
class PackVerifierTest {

    @get:Rule
    val temp = TemporaryFolder()

    private lateinit var privateKey: Ed25519PrivateKeyParameters
    private lateinit var publicKeyBytes: ByteArray
    private lateinit var verifier: PackVerifier

    private val keyId = "test-key"
    private val appVersion = 6

    @Before
    fun setUp() {
        val seed = ByteArray(32) { i -> (i * 7 + 3).toByte() }
        privateKey = Ed25519PrivateKeyParameters(seed, 0)
        publicKeyBytes = privateKey.generatePublicKey().encoded
        verifier = PackVerifier(
            acceptedKeys = mapOf(keyId to publicKeyBytes),
            appVersionCode = appVersion,
        )
    }

    // ── the happy path ───────────────────────────────────────────────────────

    @Test
    fun `a well formed pack verifies`() {
        val dir = buildPack()
        val result = verifier.verify(dir)
        assertTrue("expected Ok, got $result", result is VerifyResult.Ok)
        assertEquals("ubuntu-24-04", (result as VerifyResult.Ok).manifest.packId)
        assertEquals(2, result.manifest.files.size)
    }

    // ── tampering ────────────────────────────────────────────────────────────

    @Test
    fun `flipping one byte of a payload file fails`() {
        val dir = buildPack()
        val f = File(dir, "theme.json")
        val bytes = f.readBytes()
        bytes[10] = (bytes[10].toInt() xor 0x01).toByte()
        f.writeBytes(bytes)

        val result = verifier.verify(dir)
        assertTrue("expected HashMismatch, got $result", result is VerifyResult.HashMismatch)
        assertEquals("theme.json", (result as VerifyResult.HashMismatch).path)
    }

    @Test
    fun `appending to a payload file fails on size before hashing`() {
        val dir = buildPack()
        File(dir, "theme.json").appendText(" ")
        val result = verifier.verify(dir)
        assertTrue("expected SizeMismatch, got $result", result is VerifyResult.SizeMismatch)
    }

    @Test
    fun `editing the manifest breaks the signature`() {
        val dir = buildPack()
        val m = File(dir, PackVerifier.MANIFEST_NAME)
        // Bump the version. A plausible edit, not a corruption: this is exactly
        // what someone with write access to the bucket would try.
        m.writeText(m.readText().replace("\"version\": 1", "\"version\": 99"))

        val result = verifier.verify(dir)
        assertTrue("expected BadSignature, got $result", result is VerifyResult.BadSignature)
    }

    @Test
    fun `rewriting a hash in the manifest to match a tampered file still fails`() {
        // The attack the per-file hashes alone would NOT stop, and the reason
        // the signature covers the manifest rather than the files.
        val dir = buildPack()
        val payload = File(dir, "theme.json")
        payload.writeText("""{"id":"evil"}""")

        val m = File(dir, PackVerifier.MANIFEST_NAME)
        val old = sha256Hex("""{"id":"ubuntu-24-04","tier":"free"}""".toByteArray())
        val new = sha256Hex(payload.readBytes())
        m.writeText(m.readText().replace(old, new))

        val result = verifier.verify(dir)
        assertTrue("expected BadSignature, got $result", result is VerifyResult.BadSignature)
    }

    @Test
    fun `flipping one byte of the signature fails`() {
        val dir = buildPack()
        val s = File(dir, PackVerifier.SIGNATURE_NAME)
        val bytes = s.readBytes()
        bytes[0] = (bytes[0].toInt() xor 0x01).toByte()
        s.writeBytes(bytes)

        assertTrue(verifier.verify(dir) is VerifyResult.BadSignature)
    }

    @Test
    fun `a truncated signature fails without throwing`() {
        val dir = buildPack()
        val s = File(dir, PackVerifier.SIGNATURE_NAME)
        s.writeBytes(s.readBytes().copyOf(32))
        assertTrue(verifier.verify(dir) is VerifyResult.BadSignature)
    }

    @Test
    fun `a pack signed by a key we do not accept fails`() {
        val strangerSeed = ByteArray(32) { 0x5A }
        val stranger = Ed25519PrivateKeyParameters(strangerSeed, 0)
        // Correctly signed, self-consistent, entirely valid - by the wrong key.
        val dir = buildPack(signWith = stranger)
        assertTrue(verifier.verify(dir) is VerifyResult.BadSignature)
    }

    @Test
    fun `an unknown keyId is refused before any crypto runs`() {
        val dir = buildPack(keyIdOverride = "some-key-we-never-shipped")
        val result = verifier.verify(dir)
        assertTrue("expected UnknownKey, got $result", result is VerifyResult.UnknownKey)
    }

    // ── structural refusals ──────────────────────────────────────────────────

    @Test
    fun `an unlisted extra file is refused`() {
        val dir = buildPack()
        File(dir, "sneaky.ttf").writeText("unsigned payload")
        val result = verifier.verify(dir)
        assertTrue("expected UnlistedFiles, got $result", result is VerifyResult.UnlistedFiles)
        assertEquals(listOf("sneaky.ttf"), (result as VerifyResult.UnlistedFiles).paths)
    }

    @Test
    fun `a missing payload file is refused`() {
        val dir = buildPack()
        assertTrue(File(dir, "wallpapers/bg.webp").delete())
        val result = verifier.verify(dir)
        assertTrue("expected MissingFile, got $result", result is VerifyResult.MissingFile)
    }

    @Test
    fun `a pack requiring a newer app is refused distinctly`() {
        val dir = buildPack(minAppVersion = appVersion + 1)
        val result = verifier.verify(dir)
        assertTrue("expected AppTooOld, got $result", result is VerifyResult.AppTooOld)
        assertEquals(appVersion + 1, (result as VerifyResult.AppTooOld).required)
    }

    @Test
    fun `a missing manifest or signature is refused`() {
        val a = buildPack()
        File(a, PackVerifier.MANIFEST_NAME).delete()
        assertTrue(verifier.verify(a) is VerifyResult.MissingManifest)

        val b = buildPack(name = "b")
        File(b, PackVerifier.SIGNATURE_NAME).delete()
        assertTrue(verifier.verify(b) is VerifyResult.MissingSignature)
    }

    // ── path safety ──────────────────────────────────────────────────────────

    @Test
    fun `traversal and absolute paths are rejected by the parser`() {
        val bad = listOf(
            "../evil.json",
            "a/../../evil.json",
            "/etc/passwd",
            "C:/windows/system32",
            "wallpapers//bg.webp",
            "wallpapers\\bg.webp",
            "./bg.webp",
            "bg.webp/",
            "",
            "wallpapers/ bg.webp",
            "wallpapers/bg webp",
        )
        for (p in bad) {
            assertFalse("should have rejected '$p'", PackManifest.isSafeRelativePath(p))
        }

        val good = listOf("theme.json", "wallpapers/bg.webp", "fonts/Ubuntu-Regular.ttf", "a/b/c/d.png")
        for (p in good) {
            assertTrue("should have accepted '$p'", PackManifest.isSafeRelativePath(p))
        }
    }

    @Test
    fun `a traversal path inside a signed manifest is still refused`() {
        // Even signed by a key we trust. The parser gate runs on the trusted
        // path too, because a compromised signing key must not be a filesystem
        // write primitive.
        val dir = buildPack(extraFilePath = "../escaped.json")
        val result = verifier.verify(dir)
        assertTrue("expected MalformedManifest, got $result", result is VerifyResult.MalformedManifest)
    }

    @Test
    fun `unsafe pack ids are rejected`() {
        for (id in listOf("..", ".", "", "../x", "A-B", "a/b", ".hidden")) {
            assertFalse("should have rejected '$id'", PackManifest.isSafePackId(id))
        }
        for (id in listOf("ubuntu-24-04", "simple-icons", "kde_plasma.6")) {
            assertTrue("should have accepted '$id'", PackManifest.isSafePackId(id))
        }
    }

    // ── the loader ───────────────────────────────────────────────────────────

    @Test
    fun `a verified pack installs and a stale one is refused`() {
        val root = temp.newFolder("packs")
        val loader = ThemeAssetLoader(root, verifier)

        val staging = loader.prepareStaging("ubuntu-24-04")
        assertNotNull(staging)
        buildPackInto(staging!!, version = 2)

        val installed = loader.install("ubuntu-24-04")
        assertTrue("expected Installed, got $installed", installed is InstallResult.Installed)
        assertTrue(loader.isInstalled("ubuntu-24-04"))
        assertEquals(2, loader.installedVersion("ubuntu-24-04"))
        assertTrue(File(loader.installedDir("ubuntu-24-04"), "theme.json").isFile)
        assertEquals(listOf("ubuntu-24-04"), loader.installedPackIds())

        // The rollback attempt: correctly signed, older.
        buildPackInto(loader.prepareStaging("ubuntu-24-04")!!, version = 1)
        val stale = loader.install("ubuntu-24-04")
        assertTrue("expected Stale, got $stale", stale is InstallResult.Stale)
        assertEquals(2, loader.installedVersion("ubuntu-24-04"))

        // Re-publishing the same version without a bump is refused too.
        buildPackInto(loader.prepareStaging("ubuntu-24-04")!!, version = 2)
        assertTrue(loader.install("ubuntu-24-04") is InstallResult.Stale)

        // A genuine update goes through.
        buildPackInto(loader.prepareStaging("ubuntu-24-04")!!, version = 3)
        assertTrue(loader.install("ubuntu-24-04") is InstallResult.Installed)
        assertEquals(3, loader.installedVersion("ubuntu-24-04"))
    }

    @Test
    fun `a failed pack never reaches the installed directory`() {
        val root = temp.newFolder("packs")
        val loader = ThemeAssetLoader(root, verifier)

        // Install a good one first, so there is something to protect.
        buildPackInto(loader.prepareStaging("ubuntu-24-04")!!, version = 1)
        assertTrue(loader.install("ubuntu-24-04") is InstallResult.Installed)

        // Now stage a tampered v2.
        val staging = loader.prepareStaging("ubuntu-24-04")!!
        buildPackInto(staging, version = 2)
        File(staging, "theme.json").appendText("tampered")

        val result = loader.install("ubuntu-24-04")
        assertTrue("expected Rejected, got $result", result is InstallResult.Rejected)

        // The device kept what it had. This is the whole point.
        assertEquals(1, loader.installedVersion("ubuntu-24-04"))
        assertFalse(File(loader.installedDir("ubuntu-24-04"), "theme.json").readText().contains("tampered"))
    }

    @Test
    fun `a manifest whose packId disagrees with its directory is refused`() {
        val root = temp.newFolder("packs")
        val loader = ThemeAssetLoader(root, verifier)
        val staging = loader.prepareStaging("fedora-41")!!
        buildPackInto(staging, version = 1, packId = "ubuntu-24-04")

        val result = loader.install("fedora-41")
        assertTrue("expected Rejected, got $result", result is InstallResult.Rejected)
        assertFalse(loader.isInstalled("fedora-41"))
    }

    // ── the fixture builder ──────────────────────────────────────────────────

    private var counter = 0

    private fun buildPack(
        name: String = "pack${counter++}",
        packId: String = "ubuntu-24-04",
        version: Int = 1,
        minAppVersion: Int = 0,
        keyIdOverride: String = keyId,
        signWith: Ed25519PrivateKeyParameters = privateKey,
        extraFilePath: String? = null,
    ): File {
        val dir = temp.newFolder(name)
        buildPackInto(dir, packId, version, minAppVersion, keyIdOverride, signWith, extraFilePath)
        return dir
    }

    /**
     * Writes a complete, correctly signed pack into [dir].
     *
     * This is the reference implementation of the format. `tools/sign-pack.mjs`
     * must produce byte-identical manifests for the same input, and the C4
     * admin publisher must produce the same again. If they ever drift, the
     * symptom is BadSignature on a pack that looks perfect, so keep this
     * function and that script edited together.
     */
    private fun buildPackInto(
        dir: File,
        packId: String = "ubuntu-24-04",
        version: Int = 1,
        minAppVersion: Int = 0,
        keyIdOverride: String = keyId,
        signWith: Ed25519PrivateKeyParameters = privateKey,
        extraFilePath: String? = null,
    ) {
        dir.mkdirs()

        val themeJson = """{"id":"ubuntu-24-04","tier":"free"}""".toByteArray()
        val wallpaper = ByteArray(4096) { i -> (i % 251).toByte() }

        File(dir, "theme.json").writeBytes(themeJson)
        File(dir, "wallpapers").mkdirs()
        File(dir, "wallpapers/bg.webp").writeBytes(wallpaper)

        val entries = mutableListOf(
            fileEntry("theme.json", themeJson),
            fileEntry("wallpapers/bg.webp", wallpaper),
        )
        if (extraFilePath != null) entries.add(fileEntry(extraFilePath, themeJson))

        // Built by concatenation rather than a trimIndent raw string ON PURPOSE.
        // trimIndent runs AFTER interpolation, so a multi-line interpolated
        // value with its own indentation silently changes the minimum indent of
        // the whole literal and reshapes the manifest. The signature is over
        // these exact bytes, so "the JSON looks the same" is not the bar.
        val manifest = buildString {
            append("{\n")
            append("  \"formatVersion\": 1,\n")
            append("  \"packType\": \"theme\",\n")
            append("  \"packId\": \"").append(packId).append("\",\n")
            append("  \"version\": ").append(version).append(",\n")
            append("  \"minAppVersion\": ").append(minAppVersion).append(",\n")
            append("  \"keyId\": \"").append(keyIdOverride).append("\",\n")
            append("  \"files\": [\n")
            append(entries.joinToString(",\n"))
            append("\n  ]\n")
            append("}")
        }.toByteArray(Charsets.UTF_8)

        File(dir, PackVerifier.MANIFEST_NAME).writeBytes(manifest)
        File(dir, PackVerifier.SIGNATURE_NAME).writeBytes(sign(signWith, manifest))
    }

    private fun fileEntry(path: String, bytes: ByteArray): String =
        """    {"path": "$path", "size": ${bytes.size}, "sha256": "${sha256Hex(bytes)}"}"""

    private fun sign(key: Ed25519PrivateKeyParameters, message: ByteArray): ByteArray {
        val signer = Ed25519Signer()
        signer.init(true, key)
        signer.update(message, 0, message.size)
        return signer.generateSignature()
    }

    private fun sha256Hex(bytes: ByteArray): String =
        PackKeys.encodeHex(MessageDigest.getInstance("SHA-256").digest(bytes))
}
