// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// One installed app and what it occupies. Codec 129.
class AppEntry {
  AppEntry({
    required this.packageName,
    required this.label,
    required this.appBytes,
    required this.dataBytes,
    required this.cacheBytes,
    required this.system,
    this.lastUsedMillis,
  });

  String packageName;

  String label;

  /// The APK and its libraries.
  int appBytes;

  /// Everything the app saved: accounts, messages, downloaded media.
  ///
  /// SEPARATE FROM CACHE, and the distinction is the whole point of this
  /// screen. Cache can be thrown away with no loss. Data is the app's actual
  /// content, and clearing it signs you out and deletes what you had.
  int dataBytes;

  /// Rebuildable. This is the number a person is looking for.
  int cacheBytes;

  bool system;

  /// Null when the app has never been opened, or when usage access is off.
  int? lastUsedMillis;

  List<Object?> _toList() {
    return <Object?>[
      packageName,
      label,
      appBytes,
      dataBytes,
      cacheBytes,
      system,
      lastUsedMillis,
    ];
  }

  Object encode() {
    return _toList();
  }

  static AppEntry decode(Object result) {
    result as List<Object?>;
    return AppEntry(
      packageName: result[0]! as String,
      label: result[1]! as String,
      appBytes: result[2]! as int,
      dataBytes: result[3]! as int,
      cacheBytes: result[4]! as int,
      system: result[5]! as bool,
      lastUsedMillis: result[6] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppEntry || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(packageName, other.packageName) &&
        _deepEquals(label, other.label) &&
        _deepEquals(appBytes, other.appBytes) &&
        _deepEquals(dataBytes, other.dataBytes) &&
        _deepEquals(cacheBytes, other.cacheBytes) &&
        _deepEquals(system, other.system) &&
        _deepEquals(lastUsedMillis, other.lastUsedMillis);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppEntry(packageName: $packageName, label: $label, appBytes: $appBytes, dataBytes: $dataBytes, cacheBytes: $cacheBytes, system: $system, lastUsedMillis: $lastUsedMillis)';
  }
}

/// Whether this can work at all. Codec 130.
class AppsState {
  AppsState({
    required this.usageAccess,
    required this.totalBytes,
    required this.cacheBytes,
    required this.count,
  });

  /// Usage Access, granted on a settings screen. Without it no size can be read
  /// at all, so the UI asks before it shows an empty list.
  bool usageAccess;

  int totalBytes;

  int cacheBytes;

  int count;

  List<Object?> _toList() {
    return <Object?>[usageAccess, totalBytes, cacheBytes, count];
  }

  Object encode() {
    return _toList();
  }

  static AppsState decode(Object result) {
    result as List<Object?>;
    return AppsState(
      usageAccess: result[0]! as bool,
      totalBytes: result[1]! as int,
      cacheBytes: result[2]! as int,
      count: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppsState || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(usageAccess, other.usageAccess) &&
        _deepEquals(totalBytes, other.totalBytes) &&
        _deepEquals(cacheBytes, other.cacheBytes) &&
        _deepEquals(count, other.count);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppsState(usageAccess: $usageAccess, totalBytes: $totalBytes, cacheBytes: $cacheBytes, count: $count)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();

  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is AppEntry) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is AppsState) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return AppEntry.decode(readValue(buffer)!);
      case 130:
        return AppsState.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class AppsHostApi {
  /// Constructor for [AppsHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AppsHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<AppsState> state() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.AppsHostApi.state$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as AppsState;
  }

  /// Opens the Usage Access settings screen.
  Future<bool> requestUsageAccess() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.AppsHostApi.requestUsageAccess$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Every app this phone will admit to, largest first.
  ///
  /// Slow. StorageStatsManager reads each package separately and a phone with
  /// two hundred apps takes a few seconds, which is why the caller shows a
  /// loading state rather than blocking.
  Future<List<AppEntry>> apps() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.AppsHostApi.apps$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<AppEntry>();
  }

  /// The system storage screen for one app, where Clear cache actually works.
  Future<bool> openAppSettings(String packageName) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.AppsHostApi.openAppSettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[packageName],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }
}
