// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// A file worth looking at. Codec 129.
class CompressCandidate {
  CompressCandidate({
    required this.fileId,
    required this.name,
    required this.sizeBytes,
    required this.widthPx,
    required this.heightPx,
    required this.mimeType,
    this.kind,
    this.dateMillis,
    this.folder,
  });

  String fileId;

  String name;

  int sizeBytes;

  /// Zero when MediaStore does not know, which happens on files written by
  /// apps that never told it. The picture still compresses; only the row on
  /// screen is thinner.
  int widthPx;

  int heightPx;

  String mimeType;

  /// "screenshot" | "photo". Null from an older native layer.
  ///
  /// Separate categories because they are separate operations, not a filter on
  /// one. A photo is re-encoded as JPEG and loses a little quality for a lot of
  /// space. A screenshot is re-encoded as lossless WebP and loses nothing at
  /// all, because it is text and flat colour, which is exactly the content JPEG
  /// is worst at.
  String? kind;

  /// When the picture was taken, for the sort and the details row.
  ///
  /// Without it the shared sort control offers newest and oldest against a
  /// field that does not exist, which is a list ordered by nothing wearing the
  /// label of a list ordered by date.
  int? dateMillis;

  /// The folder it lives in, for details mode. "DCIM/Camera" and the like.
  String? folder;

  List<Object?> _toList() {
    return <Object?>[
      fileId,
      name,
      sizeBytes,
      widthPx,
      heightPx,
      mimeType,
      kind,
      dateMillis,
      folder,
    ];
  }

  Object encode() {
    return _toList();  }

  static CompressCandidate decode(Object result) {
    result as List<Object?>;
    return CompressCandidate(
      fileId: result[0]! as String,
      name: result[1]! as String,
      sizeBytes: result[2]! as int,
      widthPx: result[3]! as int,
      heightPx: result[4]! as int,
      mimeType: result[5]! as String,
      kind: result[6] as String?,
      dateMillis: result[7] as int?,
      folder: result[8] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CompressCandidate || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(fileId, other.fileId) && _deepEquals(name, other.name) && _deepEquals(sizeBytes, other.sizeBytes) && _deepEquals(widthPx, other.widthPx) && _deepEquals(heightPx, other.heightPx) && _deepEquals(mimeType, other.mimeType) && _deepEquals(kind, other.kind) && _deepEquals(dateMillis, other.dateMillis) && _deepEquals(folder, other.folder);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CompressCandidate(fileId: $fileId, name: $name, sizeBytes: $sizeBytes, widthPx: $widthPx, heightPx: $heightPx, mimeType: $mimeType, kind: $kind, dateMillis: $dateMillis, folder: $folder)';
  }
}

/// What a re-encode would actually produce. Codec 130.
class CompressPreview {
  CompressPreview({
    required this.fileId,
    required this.originalBytes,
    required this.newBytes,
    required this.quality,
    this.outputMime,
    this.lossless,
  });

  String fileId;

  int originalBytes;

  /// MEASURED, not predicted. The encode really happened, into memory.
  ///
  /// Can be LARGER than the original, and often is for a photo already saved at
  /// a lower quality than the one being applied. The UI drops those rather than
  /// offering to make a file bigger.
  int newBytes;

  int quality;

  /// What the re-encode produced, which is NOT always the source type.
  ///
  /// A PNG becomes WebP. The screen has to be able to say so, because "your
  /// screenshots will become .webp files" is a thing a person may object to and
  /// must not discover afterwards.
  String? outputMime;

  /// Whether a single pixel changed.
  ///
  /// Load bearing on screen. A lossless saving can be offered without any
  /// warning at all, and it also justifies a far lower worth-it threshold: the
  /// 20 percent floor exists to stop trading permanent quality for a trivial
  /// gain, and with nothing being traded there is nothing to protect against.
  bool? lossless;

  List<Object?> _toList() {
    return <Object?>[
      fileId,
      originalBytes,
      newBytes,
      quality,
      outputMime,
      lossless,
    ];
  }

  Object encode() {
    return _toList();  }

  static CompressPreview decode(Object result) {
    result as List<Object?>;
    return CompressPreview(
      fileId: result[0]! as String,
      originalBytes: result[1]! as int,
      newBytes: result[2]! as int,
      quality: result[3]! as int,
      outputMime: result[4] as String?,
      lossless: result[5] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CompressPreview || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(fileId, other.fileId) && _deepEquals(originalBytes, other.originalBytes) && _deepEquals(newBytes, other.newBytes) && _deepEquals(quality, other.quality) && _deepEquals(outputMime, other.outputMime) && _deepEquals(lossless, other.lossless);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CompressPreview(fileId: $fileId, originalBytes: $originalBytes, newBytes: $newBytes, quality: $quality, outputMime: $outputMime, lossless: $lossless)';
  }
}

/// What happened to one file. Codec 131.
class CompressOutcome {
  CompressOutcome({
    required this.fileId,
    required this.status,
    required this.savedBytes,
  });

  String fileId;

  /// "replaced" | "skipped" | "failed"
  ///
  /// Skipped means the new file was not smaller enough to be worth it, which is
  /// a success for the user and a non event for the app.
  String status;

  int savedBytes;

  List<Object?> _toList() {
    return <Object?>[
      fileId,
      status,
      savedBytes,
    ];
  }

  Object encode() {
    return _toList();  }

  static CompressOutcome decode(Object result) {
    result as List<Object?>;
    return CompressOutcome(
      fileId: result[0]! as String,
      status: result[1]! as String,
      savedBytes: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CompressOutcome || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(fileId, other.fileId) && _deepEquals(status, other.status) && _deepEquals(savedBytes, other.savedBytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CompressOutcome(fileId: $fileId, status: $status, savedBytes: $savedBytes)';
  }
}

/// How a run is going. Codec 132.
class CompressProgress {
  CompressProgress({
    required this.running,
    required this.done,
    required this.total,
    required this.savedBytes,
    this.currentName,
  });

  bool running;

  int done;

  int total;

  int savedBytes;

  String? currentName;

  List<Object?> _toList() {
    return <Object?>[
      running,
      done,
      total,
      savedBytes,
      currentName,
    ];
  }

  Object encode() {
    return _toList();  }

  static CompressProgress decode(Object result) {
    result as List<Object?>;
    return CompressProgress(
      running: result[0]! as bool,
      done: result[1]! as int,
      total: result[2]! as int,
      savedBytes: result[3]! as int,
      currentName: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CompressProgress || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(running, other.running) && _deepEquals(done, other.done) && _deepEquals(total, other.total) && _deepEquals(savedBytes, other.savedBytes) && _deepEquals(currentName, other.currentName);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CompressProgress(running: $running, done: $done, total: $total, savedBytes: $savedBytes, currentName: $currentName)';
  }
}

/// Counts and bytes, with nothing encoded. Codec 133.
///
/// ─── THE ONE READING IN THIS API THAT IS FREE ────────────────────────────────
///
/// Everything else here measures by re-encoding, which is the whole point and
/// is also why none of it can run unasked. But counting the screenshots and
/// adding up their sizes is a single MediaStore query, instant and cheap.
///
/// That is enough for the storage tab to say "1,204 screenshots, 8.7 GB" before
/// anything has been scanned, which is a real fact rather than an empty
/// invitation, and it still promises no saving it has not measured.
class CompressSummary {
  CompressSummary({
    required this.screenshotCount,
    required this.screenshotBytes,
    required this.photoCount,
    required this.photoBytes,
    this.videoCount,
    this.videoBytes,
  });

  int screenshotCount;

  int screenshotBytes;

  int photoCount;

  int photoBytes;

  /// Clips whose codec makes them worth re-encoding. Null from older native.
  ///
  /// Counted the same way as the others and just as cheaply: MediaStore knows
  /// the size, and the codec test is a header read rather than a decode.
  int? videoCount;

  int? videoBytes;

  List<Object?> _toList() {
    return <Object?>[
      screenshotCount,
      screenshotBytes,
      photoCount,
      photoBytes,
      videoCount,
      videoBytes,
    ];
  }

  Object encode() {
    return _toList();  }

  static CompressSummary decode(Object result) {
    result as List<Object?>;
    return CompressSummary(
      screenshotCount: result[0]! as int,
      screenshotBytes: result[1]! as int,
      photoCount: result[2]! as int,
      photoBytes: result[3]! as int,
      videoCount: result[4] as int?,
      videoBytes: result[5] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CompressSummary || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(screenshotCount, other.screenshotCount) && _deepEquals(screenshotBytes, other.screenshotBytes) && _deepEquals(photoCount, other.photoCount) && _deepEquals(photoBytes, other.photoBytes) && _deepEquals(videoCount, other.videoCount) && _deepEquals(videoBytes, other.videoBytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CompressSummary(screenshotCount: $screenshotCount, screenshotBytes: $screenshotBytes, photoCount: $photoCount, photoBytes: $photoBytes, videoCount: $videoCount, videoBytes: $videoBytes)';
  }
}

/// Both versions of one picture, for looking at. Codec 134.
///
/// ─── WHY BOTH BUFFERS AND NOT JUST THE NEW ONE ───────────────────────────────
///
/// The screen has to show the original too, and the obvious shortcut is to pull
/// it from the thumbnailer. That would be dishonest: the thumbnailer returns a
/// scaled decode, so the original would arrive softer than the full resolution
/// re-encode sitting beside it, and the compressed version would look BETTER
/// than the file it came from.
///
/// A comparison that flatters the thing being sold is worse than no comparison.
/// Both sides come back at their true size, from one decode, and the difference
/// on screen is only ever the difference the encoder made.
class CompressComparison {
  CompressComparison({
    required this.fileId,
    required this.original,
    required this.encoded,
    required this.originalBytes,
    required this.newBytes,
    required this.lossless,
  });

  String fileId;

  /// The file exactly as it is on disk.
  Uint8List original;

  /// What the re-encode produced. Identical bytes are still returned when
  /// [lossless] is true, so the screen never has to special case a null.
  Uint8List encoded;

  int originalBytes;

  int newBytes;

  /// True for a screenshot. The viewer shows no comparison at all in that case,
  /// because a control that swaps an image for the same image is a control that
  /// teaches the user their eyes are wrong.
  bool lossless;

  List<Object?> _toList() {
    return <Object?>[
      fileId,
      original,
      encoded,
      originalBytes,
      newBytes,
      lossless,
    ];
  }

  Object encode() {
    return _toList();  }

  static CompressComparison decode(Object result) {
    result as List<Object?>;
    return CompressComparison(
      fileId: result[0]! as String,
      original: result[1]! as Uint8List,
      encoded: result[2]! as Uint8List,
      originalBytes: result[3]! as int,
      newBytes: result[4]! as int,
      lossless: result[5]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CompressComparison || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(fileId, other.fileId) && _deepEquals(original, other.original) && _deepEquals(encoded, other.encoded) && _deepEquals(originalBytes, other.originalBytes) && _deepEquals(newBytes, other.newBytes) && _deepEquals(lossless, other.lossless);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CompressComparison(fileId: $fileId, original: $original, encoded: $encoded, originalBytes: $originalBytes, newBytes: $newBytes, lossless: $lossless)';
  }
}

/// One file this app has already made smaller. Codec 135.
///
/// ─── A RECORD, NOT A FOLDER ──────────────────────────────────────────────────
///
/// Nothing moves on disk. The picture stays exactly where it was, in the
/// gallery, next to everything else. Moving people's photographs into an app
/// directory is what cleaner apps do and it is how photographs get lost, along
/// with every other app's ability to find them.
///
/// ─── AND IT IS WHAT STOPS THE LOOP ───────────────────────────────────────────
///
/// The output of a compression is itself a large JPEG, so without this it comes
/// straight back as a candidate and the app offers to compress the thing it
/// just made. That is why a freshly compressed library fills with rows reading
/// "no gain": they were all correct, and all pointless.
class CompressedEntry {
  CompressedEntry({
    required this.fileId,
    required this.name,
    required this.originalBytes,
    required this.newBytes,
    required this.whenMillis,
    required this.lossless,
    required this.quality,
  });

  /// The id of the file that was WRITTEN, not the one that was trashed.
  ///
  /// It is the one that still exists, so it is the one the candidate query has
  /// to exclude and the one a thumbnail can be drawn from.
  String fileId;

  String name;

  int originalBytes;

  int newBytes;

  int whenMillis;

  /// Whether a pixel changed. "lossless" and "quality 85" are different
  /// promises, and a week later nobody remembers which a given file got.
  bool lossless;

  /// Meaningless when [lossless]. Recorded anyway, because a file that turns
  /// out badly is evidence about a setting.
  int quality;

  List<Object?> _toList() {
    return <Object?>[
      fileId,
      name,
      originalBytes,
      newBytes,
      whenMillis,
      lossless,
      quality,
    ];
  }

  Object encode() {
    return _toList();  }

  static CompressedEntry decode(Object result) {
    result as List<Object?>;
    return CompressedEntry(
      fileId: result[0]! as String,
      name: result[1]! as String,
      originalBytes: result[2]! as int,
      newBytes: result[3]! as int,
      whenMillis: result[4]! as int,
      lossless: result[5]! as bool,
      quality: result[6]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CompressedEntry || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(fileId, other.fileId) && _deepEquals(name, other.name) && _deepEquals(originalBytes, other.originalBytes) && _deepEquals(newBytes, other.newBytes) && _deepEquals(whenMillis, other.whenMillis) && _deepEquals(lossless, other.lossless) && _deepEquals(quality, other.quality);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CompressedEntry(fileId: $fileId, name: $name, originalBytes: $originalBytes, newBytes: $newBytes, whenMillis: $whenMillis, lossless: $lossless, quality: $quality)';
  }
}

/// A clip, and whether re-encoding it would achieve anything. Codec 136.
///
/// ─── THE CODEC DECIDES, NOT THE SIZE ─────────────────────────────────────────
///
/// H.264 to HEVC reliably clears 40 percent because H.264 is a twenty year old
/// codec every phone still records in for compatibility. HEVC to HEVC clears
/// almost nothing and costs ten minutes of full rate encoding and a noticeable
/// bite out of the battery.
///
/// A cleaner that offers every video by size will therefore spend the longest
/// it has ever made someone wait, on the file with the least to gain. So the
/// verdict is read from the track header before anything is offered, and the
/// ones that cannot be helped are shown saying so rather than hidden.
class VideoCandidate {
  VideoCandidate({
    required this.fileId,
    required this.name,
    required this.sizeBytes,
    required this.widthPx,
    required this.heightPx,
    required this.durationMillis,
    required this.codec,
    required this.bitrate,
    required this.eligible,
    this.reason,
    this.dateMillis,
    this.folder,
  });

  String fileId;

  String name;

  int sizeBytes;

  int widthPx;

  int heightPx;

  int durationMillis;

  /// "h264" | "hevc" | "vp9" | "av1" | "mpeg4" | "unknown"
  ///
  /// Normalised from the track mime type, so the screen can print something a
  /// person recognises rather than "video/x-vnd.on2.vp9".
  String codec;

  /// Bits per second, from the container. Zero when it does not say.
  int bitrate;

  bool eligible;

  /// Why not, in words, and null when it is. "Already HEVC", "Too short".
  ///
  /// A sentence rather than a code, because unlike the server probe there is no
  /// button attached to any of these: they are all the same outcome, which is
  /// that nothing will be done to this file.
  String? reason;

  int? dateMillis;

  String? folder;

  List<Object?> _toList() {
    return <Object?>[
      fileId,
      name,
      sizeBytes,
      widthPx,
      heightPx,
      durationMillis,
      codec,
      bitrate,
      eligible,
      reason,
      dateMillis,
      folder,
    ];
  }

  Object encode() {
    return _toList();  }

  static VideoCandidate decode(Object result) {
    result as List<Object?>;
    return VideoCandidate(
      fileId: result[0]! as String,
      name: result[1]! as String,
      sizeBytes: result[2]! as int,
      widthPx: result[3]! as int,
      heightPx: result[4]! as int,
      durationMillis: result[5]! as int,
      codec: result[6]! as String,
      bitrate: result[7]! as int,
      eligible: result[8]! as bool,
      reason: result[9] as String?,
      dateMillis: result[10] as int?,
      folder: result[11] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VideoCandidate || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(fileId, other.fileId) && _deepEquals(name, other.name) && _deepEquals(sizeBytes, other.sizeBytes) && _deepEquals(widthPx, other.widthPx) && _deepEquals(heightPx, other.heightPx) && _deepEquals(durationMillis, other.durationMillis) && _deepEquals(codec, other.codec) && _deepEquals(bitrate, other.bitrate) && _deepEquals(eligible, other.eligible) && _deepEquals(reason, other.reason) && _deepEquals(dateMillis, other.dateMillis) && _deepEquals(folder, other.folder);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VideoCandidate(fileId: $fileId, name: $name, sizeBytes: $sizeBytes, widthPx: $widthPx, heightPx: $heightPx, durationMillis: $durationMillis, codec: $codec, bitrate: $bitrate, eligible: $eligible, reason: $reason, dateMillis: $dateMillis, folder: $folder)';
  }
}

/// What a real sample of one clip suggests. Codec 137.
///
/// ─── AN ESTIMATE, AND THE FIRST ONE IN THIS API ──────────────────────────────
///
/// Every figure elsewhere here is measured by encoding the whole file, which is
/// possible at four megabytes and absurd at two gigabytes, where measuring IS
/// the job. So a short slice is really encoded and the rest is extrapolated
/// from it.
///
/// That is a forecast, not a measurement, and it must never wear the same word
/// on screen as the photo figures. It is also honest in a way a bitrate formula
/// is not: it is this encoder, on this phone, on these pixels.
///
/// ─── AND IT CAN BE WRONG IN A KNOWN DIRECTION ────────────────────────────────
///
/// A clip that opens on a still shot and later pans across a market will
/// compress better in its first seconds than across its length, so the estimate
/// runs high. [sampledMillis] is reported so the screen can say what it was
/// based on rather than presenting a number from nowhere.
class VideoEstimate {
  VideoEstimate({
    required this.fileId,
    required this.originalBytes,
    required this.estimatedBytes,
    required this.sampledMillis,
    required this.preset,
  });

  String fileId;

  int originalBytes;

  /// Extrapolated. Can exceed [originalBytes] on a clip already well encoded,
  /// and the UI drops those rather than offering to make a file bigger.
  int estimatedBytes;

  /// How much was actually encoded to reach it.
  int sampledMillis;

  /// "same" or "smaller".
  String preset;

  List<Object?> _toList() {
    return <Object?>[
      fileId,
      originalBytes,
      estimatedBytes,
      sampledMillis,
      preset,
    ];
  }

  Object encode() {
    return _toList();  }

  static VideoEstimate decode(Object result) {
    result as List<Object?>;
    return VideoEstimate(
      fileId: result[0]! as String,
      originalBytes: result[1]! as int,
      estimatedBytes: result[2]! as int,
      sampledMillis: result[3]! as int,
      preset: result[4]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VideoEstimate || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(fileId, other.fileId) && _deepEquals(originalBytes, other.originalBytes) && _deepEquals(estimatedBytes, other.estimatedBytes) && _deepEquals(sampledMillis, other.sampledMillis) && _deepEquals(preset, other.preset);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VideoEstimate(fileId: $fileId, originalBytes: $originalBytes, estimatedBytes: $estimatedBytes, sampledMillis: $sampledMillis, preset: $preset)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is CompressCandidate) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is CompressPreview) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is CompressOutcome) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is CompressProgress) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is CompressSummary) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is CompressComparison) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is CompressedEntry) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is VideoCandidate) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is VideoEstimate) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return CompressCandidate.decode(readValue(buffer)!);
      case 130:
        return CompressPreview.decode(readValue(buffer)!);
      case 131:
        return CompressOutcome.decode(readValue(buffer)!);
      case 132:
        return CompressProgress.decode(readValue(buffer)!);
      case 133:
        return CompressSummary.decode(readValue(buffer)!);
      case 134:
        return CompressComparison.decode(readValue(buffer)!);
      case 135:
        return CompressedEntry.decode(readValue(buffer)!);
      case 136:
        return VideoCandidate.decode(readValue(buffer)!);
      case 137:
        return VideoEstimate.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class CompressHostApi {
  /// Constructor for [CompressHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CompressHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Counts and total bytes per category. No encoding, so it is safe to call
  /// on a screen the user did not ask to scan.
  Future<CompressSummary> summary(int minBytes) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_recovery.CompressHostApi.summary$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[minBytes]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as CompressSummary;
  }

  /// Images large enough to be worth re-encoding, largest first.
  ///
  /// [kind] is "screenshot", "photo", or "all". Filtered in the query rather
  /// than in Dart, because the alternative is fetching three thousand rows to
  /// display twelve.
  Future<List<CompressCandidate>> candidates(String kind, int minBytes, int limit) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_recovery.CompressHostApi.candidates$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[kind, minBytes, limit]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<CompressCandidate>();
  }

  /// Re-encodes into memory and reports the real size.
  ///
  /// Slow: a full decode and encode per file. The caller previews only what is
  /// on screen, never the whole list.
  /// [quality] applies to photos only. A screenshot is encoded losslessly and
  /// ignores it, which is why the output format is reported back rather than
  /// assumed from what was asked for.
  Future<List<CompressPreview>> preview(List<String> fileIds, int quality) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_recovery.CompressHostApi.preview$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[fileIds, quality]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<CompressPreview>();
  }

  /// Replaces the originals, keeping them in the trash.
  ///
  /// ─── THE ORIGINAL IS TRASHED, NOT DELETED ────────────────────────────────
  ///
  /// A re-encode is lossy and irreversible. The user gets thirty days to notice
  /// that a picture they cared about now has artefacts in the sky, which is the
  /// only safe way to offer this at all.
  Future<List<CompressOutcome>> compress(List<String> fileIds, int quality) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_recovery.CompressHostApi.compress$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[fileIds, quality]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<CompressOutcome>();
  }

  /// Remembers files that were measured and cannot be improved.
  ///
  /// ─── THE OTHER HALF OF THE LOOP ──────────────────────────────────────────
  ///
  /// Excluding this app's own output stopped it offering to re-compress what it
  /// wrote. It did nothing about the far larger group: photographs that were
  /// already saved efficiently and gain nothing at all. Those are measured,
  /// shown as "no gain", left alone by the run, and then measured again from
  /// scratch the next time the screen opens, forever.
  ///
  /// After one run the list is made up entirely of those files, which is
  /// indistinguishable from the run having done nothing.
  ///
  /// Not recorded during [preview], which is speculative and runs on every
  /// scroll. Only when the user has actually run a compression and the answer
  /// has been acted on.
  Future<void> markNoGain(List<String> fileIds) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_recovery.CompressHostApi.markNoGain$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[fileIds]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Forgets every no-gain verdict.
  ///
  /// Called when the quality changes, because the verdict was reached at one
  /// setting and does not hold at another: a file that gains nothing at 85 may
  /// well gain at 65. Simpler and more obviously correct than storing a quality
  /// per file and comparing.
  Future<void> clearNoGain() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_recovery.CompressHostApi.clearNoGain$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// What this app has already compressed, newest first.
  ///
  /// Kept in native rather than in Dart prefs because the candidate query needs
  /// it to exclude its own output, and a filter that lived on the far side of
  /// the bridge would mean shipping every row across just to drop most of them.
  Future<List<CompressedEntry>> history(int limit) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_recovery.CompressHostApi.history$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[limit]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<CompressedEntry>();
  }

  /// Every clip, with the ineligible ones included and marked.
  ///
  /// Included rather than filtered, because a user whose largest video is
  /// missing from a list about making files smaller will assume the app failed
  /// to see it. Saying "already HEVC" costs one row and answers the question.
  Future<List<VideoCandidate>> videoCandidates(int minBytes, int limit) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_recovery.CompressHostApi.videoCandidates$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[minBytes, limit]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<VideoCandidate>();
  }

  /// Encodes a slice of one clip and extrapolates from what it produced.
  ///
  /// Slow: seconds rather than milliseconds, because it really runs the
  /// encoder. The caller estimates what is on screen, one at a time, never the
  /// whole list.
  ///
  /// [preset] is "same" for a codec swap at matched quality, or "smaller" for a
  /// reduced bitrate as well. Resolution is never touched by either.
  Future<VideoEstimate?> estimateVideo(String fileId, String preset) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_recovery.CompressHostApi.estimateVideo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[fileId, preset]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as VideoEstimate?;
  }

  /// Re-encodes clips and replaces them, keeping the originals in the trash.
  ///
  /// ─── LONGER THAN ANYTHING ELSE IN THIS APP ───────────────────────────────
  ///
  /// Minutes per file rather than milliseconds, so it runs behind a foreground
  /// service with a notification and can be stopped between files or during
  /// one. Progress arrives through the same [progress] call the image path
  /// uses, and [cancel] stops both.
  Future<List<CompressOutcome>> compressVideo(List<String> fileIds, String preset) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_recovery.CompressHostApi.compressVideo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[fileIds, preset]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<CompressOutcome>();
  }

  /// One file, decoded once, returned as both versions.
  ///
  /// Deliberately not part of [preview]. That measures a whole selection and
  /// must stay cheap per file; this carries megabytes across the bridge and is
  /// only ever called for the single picture on screen.
  Future<CompressComparison?> comparison(String fileId, int quality) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_recovery.CompressHostApi.comparison$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[fileId, quality]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as CompressComparison?;
  }

  Future<void> cancel() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_recovery.CompressHostApi.cancel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<CompressProgress> progress() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.g_recovery.CompressHostApi.progress$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as CompressProgress;
  }
}
