// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// One content pack, as the client sees it. Codec 129.
class ContentPackInfo {
  ContentPackInfo({
    required this.packId,
    required this.packType,
    required this.version,
    required this.installedVersion,
    required this.sizeBytes,
  });

  /// "trashmap", "learn-en", "oem-guide".
  String packId;

  /// "registry" for the trashmap, "article" for Learn. A String, because an
  /// enum would renumber the schema.
  String packType;

  /// What the signed index advertises. 0 when the index has not been read.
  int version;

  /// What is on disk and verified. 0 when nothing is installed and the app is
  /// running on its bundled copy.
  int installedVersion;

  int sizeBytes;

  List<Object?> _toList() {
    return <Object?>[packId, packType, version, installedVersion, sizeBytes];
  }

  Object encode() {
    return _toList();
  }

  static ContentPackInfo decode(Object result) {
    result as List<Object?>;
    return ContentPackInfo(
      packId: result[0]! as String,
      packType: result[1]! as String,
      version: result[2]! as int,
      installedVersion: result[3]! as int,
      sizeBytes: result[4]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ContentPackInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(packId, other.packId) &&
        _deepEquals(packType, other.packType) &&
        _deepEquals(version, other.version) &&
        _deepEquals(installedVersion, other.installedVersion) &&
        _deepEquals(sizeBytes, other.sizeBytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ContentPackInfo(packId: $packId, packType: $packType, version: $version, installedVersion: $installedVersion, sizeBytes: $sizeBytes)';
  }
}

/// The outcome of one sync. Codec 130.
class ContentSyncResult {
  ContentSyncResult({
    required this.status,
    required this.detail,
    required this.changed,
    required this.packs,
  });

  /// "updated" | "upToDate" | "offline" | "rejected" | "failed"
  ///
  /// A RESULT OBJECT RATHER THAN A THROWN ERROR, and the statuses are not
  /// interchangeable. `offline` is the ordinary case on a phone in a lift and
  /// deserves silence. `rejected` means a signature failed, which should be
  /// reported and NEVER retried, because retrying a bad signature just fetches
  /// the same bad bytes again. Only `failed` is worth a retry button.
  String status;

  String detail;

  /// True when something on disk changed and callers should re-read.
  bool changed;

  List<ContentPackInfo> packs;

  List<Object?> _toList() {
    return <Object?>[status, detail, changed, packs];
  }

  Object encode() {
    return _toList();
  }

  static ContentSyncResult decode(Object result) {
    result as List<Object?>;
    return ContentSyncResult(
      status: result[0]! as String,
      detail: result[1]! as String,
      changed: result[2]! as bool,
      packs: (result[3]! as List<Object?>).cast<ContentPackInfo>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ContentSyncResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(status, other.status) &&
        _deepEquals(detail, other.detail) &&
        _deepEquals(changed, other.changed) &&
        _deepEquals(packs, other.packs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ContentSyncResult(status: $status, detail: $detail, changed: $changed, packs: $packs)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();

  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is ContentPackInfo) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is ContentSyncResult) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return ContentPackInfo.decode(readValue(buffer)!);
      case 130:
        return ContentSyncResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class ContentHostApi {
  /// Constructor for [ContentHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ContentHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// The CDN root, for example the g-recovery folder under the Mindberzerk CDN.
  ///
  /// Pushed from Dart so the host can move without a Kotlin change, exactly as
  /// the launcher does it. Validated natively before use: https only, no path
  /// traversal. A base URL that arrives from anywhere other than a constant is
  /// still a value to check, not a value to trust.
  Future<void> setBaseUrl(String url) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.ContentHostApi.setBaseUrl$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[url],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Fetch the signed index, verify it, and install any pack that is newer.
  ///
  /// Safe to call on every launch: the index request carries an ETag, so the
  /// common case is a 304 with no body.
  Future<ContentSyncResult> sync() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.ContentHostApi.sync$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as ContentSyncResult;
  }

  /// The verified JSON for a content id, or null when nothing is installed.
  ///
  /// Null is the ORDINARY answer, not an error. It means the app should use its
  /// bundled copy, which is what happens on first launch and whenever the CDN
  /// is unreachable.
  Future<String?> readContent(String packId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.ContentHostApi.readContent$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[packId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  /// What is installed right now, without touching the network.
  Future<List<ContentPackInfo>> packs() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.ContentHostApi.packs$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<ContentPackInfo>();
  }
}
