// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// The screen. Codec 129.
class DisplayInfo {
  DisplayInfo({
    required this.widthPx,
    required this.heightPx,
    required this.densityDpi,
    required this.refreshHz,
    required this.supportedHz,
    required this.hdr,
    required this.wideColour,
    required this.hdrTypes,
    this.maxLuminance,
    this.minLuminance,
    this.averageLuminance,
  });

  int widthPx;

  int heightPx;

  int densityDpi;

  double refreshHz;

  /// Every mode the panel will run at, largest first. One entry on a fixed
  /// 60 Hz screen, which is not an error and needs no note.
  List<double> supportedHz;

  bool hdr;

  bool wideColour;

  /// "HDR10", "HLG", "HDR10+", "Dolby Vision".
  List<String> hdrTypes;

  /// Candelas per square metre, and null on a panel that does not declare them,
  /// which is most non HDR screens.
  double? maxLuminance;

  double? minLuminance;

  double? averageLuminance;

  List<Object?> _toList() {
    return <Object?>[
      widthPx,
      heightPx,
      densityDpi,
      refreshHz,
      supportedHz,
      hdr,
      wideColour,
      hdrTypes,
      maxLuminance,
      minLuminance,
      averageLuminance,
    ];
  }

  Object encode() {
    return _toList();
  }

  static DisplayInfo decode(Object result) {
    result as List<Object?>;
    return DisplayInfo(
      widthPx: result[0]! as int,
      heightPx: result[1]! as int,
      densityDpi: result[2]! as int,
      refreshHz: result[3]! as double,
      supportedHz: (result[4]! as List<Object?>).cast<double>(),
      hdr: result[5]! as bool,
      wideColour: result[6]! as bool,
      hdrTypes: (result[7]! as List<Object?>).cast<String>(),
      maxLuminance: result[8] as double?,
      minLuminance: result[9] as double?,
      averageLuminance: result[10] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DisplayInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(widthPx, other.widthPx) &&
        _deepEquals(heightPx, other.heightPx) &&
        _deepEquals(densityDpi, other.densityDpi) &&
        _deepEquals(refreshHz, other.refreshHz) &&
        _deepEquals(supportedHz, other.supportedHz) &&
        _deepEquals(hdr, other.hdr) &&
        _deepEquals(wideColour, other.wideColour) &&
        _deepEquals(hdrTypes, other.hdrTypes) &&
        _deepEquals(maxLuminance, other.maxLuminance) &&
        _deepEquals(minLuminance, other.minLuminance) &&
        _deepEquals(averageLuminance, other.averageLuminance);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DisplayInfo(widthPx: $widthPx, heightPx: $heightPx, densityDpi: $densityDpi, refreshHz: $refreshHz, supportedHz: $supportedHz, hdr: $hdr, wideColour: $wideColour, hdrTypes: $hdrTypes, maxLuminance: $maxLuminance, minLuminance: $minLuminance, averageLuminance: $averageLuminance)';
  }
}

/// The active connection. Codec 130.
class NetworkInfo {
  NetworkInfo({
    required this.type,
    required this.connected,
    required this.metered,
    this.ipv4,
    this.ipv6,
    required this.rxBytesTotal,
    required this.txBytesTotal,
  });

  /// "wifi" | "cellular" | "ethernet" | "vpn" | "none"
  String type;

  bool connected;

  bool metered;

  String? ipv4;

  String? ipv6;

  /// Since boot, across every interface. TrafficStats needs no permission for
  /// device totals, unlike the per app figures.
  int rxBytesTotal;

  int txBytesTotal;

  List<Object?> _toList() {
    return <Object?>[
      type,
      connected,
      metered,
      ipv4,
      ipv6,
      rxBytesTotal,
      txBytesTotal,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NetworkInfo decode(Object result) {
    result as List<Object?>;
    return NetworkInfo(
      type: result[0]! as String,
      connected: result[1]! as bool,
      metered: result[2]! as bool,
      ipv4: result[3] as String?,
      ipv6: result[4] as String?,
      rxBytesTotal: result[5]! as int,
      txBytesTotal: result[6]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NetworkInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type) &&
        _deepEquals(connected, other.connected) &&
        _deepEquals(metered, other.metered) &&
        _deepEquals(ipv4, other.ipv4) &&
        _deepEquals(ipv6, other.ipv6) &&
        _deepEquals(rxBytesTotal, other.rxBytesTotal) &&
        _deepEquals(txBytesTotal, other.txBytesTotal);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NetworkInfo(type: $type, connected: $connected, metered: $metered, ipv4: $ipv4, ipv6: $ipv6, rxBytesTotal: $rxBytesTotal, txBytesTotal: $txBytesTotal)';
  }
}

/// The Wi-Fi link. Codec 131.
///
/// ─── HALF OF THIS NEEDS LOCATION ─────────────────────────────────────────────
///
/// From Android 10, SSID, BSSID and MAC are only real with ACCESS_FINE_LOCATION.
/// Without it the system hands back "<unknown ssid>" and 02:00:00:00:00:00, and
/// an app that prints those is printing a refusal as though it were data.
///
/// So they are NULLABLE and native returns null rather than the placeholder. The
/// UI shows the row missing and names the permission once.
class WifiInfo {
  WifiInfo({
    required this.connected,
    this.ssid,
    this.bssid,
    this.macAddress,
    this.standard,
    this.frequencyMhz,
    this.linkSpeedMbps,
    this.rxLinkSpeedMbps,
    this.signalPercent,
    this.security,
    required this.supports5Ghz,
    required this.supports6Ghz,
    required this.hasLocationPermission,
  });

  bool connected;

  String? ssid;

  String? bssid;

  String? macAddress;

  /// "802.11n", "802.11ac", "802.11ax".
  String? standard;

  int? frequencyMhz;

  int? linkSpeedMbps;

  int? rxLinkSpeedMbps;

  int? signalPercent;

  String? security;

  bool supports5Ghz;

  bool supports6Ghz;

  /// So the UI can say which permission would fill the gaps, rather than
  /// guessing from a null that might just be a disconnected radio.
  bool hasLocationPermission;

  List<Object?> _toList() {
    return <Object?>[
      connected,
      ssid,
      bssid,
      macAddress,
      standard,
      frequencyMhz,
      linkSpeedMbps,
      rxLinkSpeedMbps,
      signalPercent,
      security,
      supports5Ghz,
      supports6Ghz,
      hasLocationPermission,
    ];
  }

  Object encode() {
    return _toList();
  }

  static WifiInfo decode(Object result) {
    result as List<Object?>;
    return WifiInfo(
      connected: result[0]! as bool,
      ssid: result[1] as String?,
      bssid: result[2] as String?,
      macAddress: result[3] as String?,
      standard: result[4] as String?,
      frequencyMhz: result[5] as int?,
      linkSpeedMbps: result[6] as int?,
      rxLinkSpeedMbps: result[7] as int?,
      signalPercent: result[8] as int?,
      security: result[9] as String?,
      supports5Ghz: result[10]! as bool,
      supports6Ghz: result[11]! as bool,
      hasLocationPermission: result[12]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WifiInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(connected, other.connected) &&
        _deepEquals(ssid, other.ssid) &&
        _deepEquals(bssid, other.bssid) &&
        _deepEquals(macAddress, other.macAddress) &&
        _deepEquals(standard, other.standard) &&
        _deepEquals(frequencyMhz, other.frequencyMhz) &&
        _deepEquals(linkSpeedMbps, other.linkSpeedMbps) &&
        _deepEquals(rxLinkSpeedMbps, other.rxLinkSpeedMbps) &&
        _deepEquals(signalPercent, other.signalPercent) &&
        _deepEquals(security, other.security) &&
        _deepEquals(supports5Ghz, other.supports5Ghz) &&
        _deepEquals(supports6Ghz, other.supports6Ghz) &&
        _deepEquals(hasLocationPermission, other.hasLocationPermission);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'WifiInfo(connected: $connected, ssid: $ssid, bssid: $bssid, macAddress: $macAddress, standard: $standard, frequencyMhz: $frequencyMhz, linkSpeedMbps: $linkSpeedMbps, rxLinkSpeedMbps: $rxLinkSpeedMbps, signalPercent: $signalPercent, security: $security, supports5Ghz: $supports5Ghz, supports6Ghz: $supports6Ghz, hasLocationPermission: $hasLocationPermission)';
  }
}

/// One camera. Codec 132.
class CameraInfo {
  CameraInfo({
    required this.id,
    required this.facing,
    required this.megapixels,
    required this.widthPx,
    required this.heightPx,
    required this.focalLengthsMm,
    required this.apertures,
    this.isoMin,
    this.isoMax,
    required this.supportsRaw,
    required this.hasFlash,
  });

  String id;

  /// "front" | "back" | "external"
  String facing;

  double megapixels;

  int widthPx;

  int heightPx;

  List<double> focalLengthsMm;

  List<double> apertures;

  int? isoMin;

  int? isoMax;

  bool supportsRaw;

  bool hasFlash;

  List<Object?> _toList() {
    return <Object?>[
      id,
      facing,
      megapixels,
      widthPx,
      heightPx,
      focalLengthsMm,
      apertures,
      isoMin,
      isoMax,
      supportsRaw,
      hasFlash,
    ];
  }

  Object encode() {
    return _toList();
  }

  static CameraInfo decode(Object result) {
    result as List<Object?>;
    return CameraInfo(
      id: result[0]! as String,
      facing: result[1]! as String,
      megapixels: result[2]! as double,
      widthPx: result[3]! as int,
      heightPx: result[4]! as int,
      focalLengthsMm: (result[5]! as List<Object?>).cast<double>(),
      apertures: (result[6]! as List<Object?>).cast<double>(),
      isoMin: result[7] as int?,
      isoMax: result[8] as int?,
      supportsRaw: result[9]! as bool,
      hasFlash: result[10]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CameraInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(facing, other.facing) &&
        _deepEquals(megapixels, other.megapixels) &&
        _deepEquals(widthPx, other.widthPx) &&
        _deepEquals(heightPx, other.heightPx) &&
        _deepEquals(focalLengthsMm, other.focalLengthsMm) &&
        _deepEquals(apertures, other.apertures) &&
        _deepEquals(isoMin, other.isoMin) &&
        _deepEquals(isoMax, other.isoMax) &&
        _deepEquals(supportsRaw, other.supportsRaw) &&
        _deepEquals(hasFlash, other.hasFlash);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CameraInfo(id: $id, facing: $facing, megapixels: $megapixels, widthPx: $widthPx, heightPx: $heightPx, focalLengthsMm: $focalLengthsMm, apertures: $apertures, isoMin: $isoMin, isoMax: $isoMax, supportsRaw: $supportsRaw, hasFlash: $hasFlash)';
  }
}

/// What the hardware has. Codec 133.
class FeatureFlags {
  FeatureFlags({
    required this.nfc,
    required this.gps,
    required this.uwb,
    required this.usbHost,
    required this.fingerprint,
    required this.bluetooth,
    required this.bluetoothLe,
    required this.telephony,
  });

  bool nfc;

  bool gps;

  bool uwb;

  bool usbHost;

  bool fingerprint;

  bool bluetooth;

  bool bluetoothLe;

  bool telephony;

  List<Object?> _toList() {
    return <Object?>[
      nfc,
      gps,
      uwb,
      usbHost,
      fingerprint,
      bluetooth,
      bluetoothLe,
      telephony,
    ];
  }

  Object encode() {
    return _toList();
  }

  static FeatureFlags decode(Object result) {
    result as List<Object?>;
    return FeatureFlags(
      nfc: result[0]! as bool,
      gps: result[1]! as bool,
      uwb: result[2]! as bool,
      usbHost: result[3]! as bool,
      fingerprint: result[4]! as bool,
      bluetooth: result[5]! as bool,
      bluetoothLe: result[6]! as bool,
      telephony: result[7]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! FeatureFlags || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(nfc, other.nfc) &&
        _deepEquals(gps, other.gps) &&
        _deepEquals(uwb, other.uwb) &&
        _deepEquals(usbHost, other.usbHost) &&
        _deepEquals(fingerprint, other.fingerprint) &&
        _deepEquals(bluetooth, other.bluetooth) &&
        _deepEquals(bluetoothLe, other.bluetoothLe) &&
        _deepEquals(telephony, other.telephony);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'FeatureFlags(nfc: $nfc, gps: $gps, uwb: $uwb, usbHost: $usbHost, fingerprint: $fingerprint, bluetooth: $bluetooth, bluetoothLe: $bluetoothLe, telephony: $telephony)';
  }
}

/// One throughput reading. Codec 134.
class ThroughputSample {
  ThroughputSample({
    required this.rxBytesPerSecond,
    required this.txBytesPerSecond,
    required this.rxBytesTotal,
    required this.txBytesTotal,
  });

  /// A RATE, computed natively from two counter reads.
  ///
  /// Native owns the previous counter and the elapsed time, because doing the
  /// subtraction in Dart would make every rate wrong by however long the UI
  /// thread was busy.
  int rxBytesPerSecond;

  int txBytesPerSecond;

  int rxBytesTotal;

  int txBytesTotal;

  List<Object?> _toList() {
    return <Object?>[
      rxBytesPerSecond,
      txBytesPerSecond,
      rxBytesTotal,
      txBytesTotal,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ThroughputSample decode(Object result) {
    result as List<Object?>;
    return ThroughputSample(
      rxBytesPerSecond: result[0]! as int,
      txBytesPerSecond: result[1]! as int,
      rxBytesTotal: result[2]! as int,
      txBytesTotal: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ThroughputSample || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(rxBytesPerSecond, other.rxBytesPerSecond) &&
        _deepEquals(txBytesPerSecond, other.txBytesPerSecond) &&
        _deepEquals(rxBytesTotal, other.rxBytesTotal) &&
        _deepEquals(txBytesTotal, other.txBytesTotal);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ThroughputSample(rxBytesPerSecond: $rxBytesPerSecond, txBytesPerSecond: $txBytesPerSecond, rxBytesTotal: $rxBytesTotal, txBytesTotal: $txBytesTotal)';
  }
}

/// One sensor, reading now. Codec 135.
class SensorReading {
  SensorReading({
    required this.type,
    required this.name,
    required this.values,
    required this.unit,
    this.maxRange,
  });

  /// The Android sensor type constant, as a string. Numbers would be an enum,
  /// and an enum here would renumber every class above it.
  String type;

  String name;

  /// One to three axes. Light and pressure send one, the accelerometer sends
  /// three, and the caller renders whatever arrives rather than assuming.
  List<double> values;

  /// "m/s2", "lux", "uT", "rad/s", "hPa", "cm".
  String unit;

  /// The largest value this sensor can report, for scaling a bar. Null where
  /// the sensor does not declare one.
  double? maxRange;

  List<Object?> _toList() {
    return <Object?>[type, name, values, unit, maxRange];
  }

  Object encode() {
    return _toList();
  }

  static SensorReading decode(Object result) {
    result as List<Object?>;
    return SensorReading(
      type: result[0]! as String,
      name: result[1]! as String,
      values: (result[2]! as List<Object?>).cast<double>(),
      unit: result[3]! as String,
      maxRange: result[4] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SensorReading || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type) &&
        _deepEquals(name, other.name) &&
        _deepEquals(values, other.values) &&
        _deepEquals(unit, other.unit) &&
        _deepEquals(maxRange, other.maxRange);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SensorReading(type: $type, name: $name, values: $values, unit: $unit, maxRange: $maxRange)';
  }
}

/// One SIM. Codec 136.
///
/// ─── WHAT IS FREE AND WHAT IS NOT ────────────────────────────────────────────
///
/// Carrier name, country, MCC and MNC come from SubscriptionManager and need
/// READ_PHONE_STATE from Android 11. The number and the ICCID need more than
/// that and are not read at all: a recovery app does not need the subscriber's
/// phone number, and asking for it would be the single most alarming permission
/// in the app.
class SimInfo {
  SimInfo({
    required this.slot,
    this.carrier,
    this.countryIso,
    this.mcc,
    this.mnc,
    required this.embedded,
    required this.roaming,
    required this.dataDefault,
  });

  int slot;

  String? carrier;

  /// Two letters, uppercased for display. Null where the SIM does not report a
  /// country, which happens on some MVNOs.
  String? countryIso;

  String? mcc;

  String? mnc;

  /// An eSIM rather than a physical card.
  bool embedded;

  bool roaming;

  /// The SIM carrying mobile data. False on both when data is off.
  bool dataDefault;

  List<Object?> _toList() {
    return <Object?>[
      slot,
      carrier,
      countryIso,
      mcc,
      mnc,
      embedded,
      roaming,
      dataDefault,
    ];
  }

  Object encode() {
    return _toList();
  }

  static SimInfo decode(Object result) {
    result as List<Object?>;
    return SimInfo(
      slot: result[0]! as int,
      carrier: result[1] as String?,
      countryIso: result[2] as String?,
      mcc: result[3] as String?,
      mnc: result[4] as String?,
      embedded: result[5]! as bool,
      roaming: result[6]! as bool,
      dataDefault: result[7]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SimInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(slot, other.slot) &&
        _deepEquals(carrier, other.carrier) &&
        _deepEquals(countryIso, other.countryIso) &&
        _deepEquals(mcc, other.mcc) &&
        _deepEquals(mnc, other.mnc) &&
        _deepEquals(embedded, other.embedded) &&
        _deepEquals(roaming, other.roaming) &&
        _deepEquals(dataDefault, other.dataDefault);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SimInfo(slot: $slot, carrier: $carrier, countryIso: $countryIso, mcc: $mcc, mnc: $mnc, embedded: $embedded, roaming: $roaming, dataDefault: $dataDefault)';
  }
}

/// One paired device. Codec 137.
class PairedDevice {
  PairedDevice({
    required this.name,
    required this.address,
    required this.type,
    required this.connected,
  });

  String name;

  /// Masked to the last four characters. A full MAC on screen is a tracking
  /// identifier for a device the user may be about to photograph the screen of.
  String address;

  /// "audio" | "phone" | "computer" | "wearable" | "input" | "other"
  String type;

  bool connected;

  List<Object?> _toList() {
    return <Object?>[name, address, type, connected];
  }

  Object encode() {
    return _toList();
  }

  static PairedDevice decode(Object result) {
    result as List<Object?>;
    return PairedDevice(
      name: result[0]! as String,
      address: result[1]! as String,
      type: result[2]! as String,
      connected: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PairedDevice || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(name, other.name) &&
        _deepEquals(address, other.address) &&
        _deepEquals(type, other.type) &&
        _deepEquals(connected, other.connected);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PairedDevice(name: $name, address: $address, type: $type, connected: $connected)';
  }
}

/// The Bluetooth radio. Codec 138.
class BluetoothInfo {
  BluetoothInfo({
    required this.available,
    required this.enabled,
    this.name,
    required this.hasPermission,
    required this.paired,
    required this.leSupported,
    required this.le2mSupported,
    required this.leCodedSupported,
    required this.leAudioSupported,
  });

  /// The device has a radio at all.
  bool available;

  bool enabled;

  /// Null without BLUETOOTH_CONNECT, which is where the adapter name lives from
  /// Android 12.
  String? name;

  bool hasPermission;

  /// Empty without the permission, which is not the same as no paired devices.
  /// [hasPermission] tells the two apart.
  List<PairedDevice> paired;

  bool leSupported;

  bool le2mSupported;

  bool leCodedSupported;

  bool leAudioSupported;

  List<Object?> _toList() {
    return <Object?>[
      available,
      enabled,
      name,
      hasPermission,
      paired,
      leSupported,
      le2mSupported,
      leCodedSupported,
      leAudioSupported,
    ];
  }

  Object encode() {
    return _toList();
  }

  static BluetoothInfo decode(Object result) {
    result as List<Object?>;
    return BluetoothInfo(
      available: result[0]! as bool,
      enabled: result[1]! as bool,
      name: result[2] as String?,
      hasPermission: result[3]! as bool,
      paired: (result[4]! as List<Object?>).cast<PairedDevice>(),
      leSupported: result[5]! as bool,
      le2mSupported: result[6]! as bool,
      leCodedSupported: result[7]! as bool,
      leAudioSupported: result[8]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BluetoothInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(available, other.available) &&
        _deepEquals(enabled, other.enabled) &&
        _deepEquals(name, other.name) &&
        _deepEquals(hasPermission, other.hasPermission) &&
        _deepEquals(paired, other.paired) &&
        _deepEquals(leSupported, other.leSupported) &&
        _deepEquals(le2mSupported, other.le2mSupported) &&
        _deepEquals(leCodedSupported, other.leCodedSupported) &&
        _deepEquals(leAudioSupported, other.leAudioSupported);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BluetoothInfo(available: $available, enabled: $enabled, name: $name, hasPermission: $hasPermission, paired: $paired, leSupported: $leSupported, le2mSupported: $le2mSupported, leCodedSupported: $leCodedSupported, leAudioSupported: $leAudioSupported)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();

  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is DisplayInfo) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is NetworkInfo) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is WifiInfo) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is CameraInfo) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is FeatureFlags) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is ThroughputSample) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is SensorReading) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is SimInfo) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is PairedDevice) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is BluetoothInfo) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return DisplayInfo.decode(readValue(buffer)!);
      case 130:
        return NetworkInfo.decode(readValue(buffer)!);
      case 131:
        return WifiInfo.decode(readValue(buffer)!);
      case 132:
        return CameraInfo.decode(readValue(buffer)!);
      case 133:
        return FeatureFlags.decode(readValue(buffer)!);
      case 134:
        return ThroughputSample.decode(readValue(buffer)!);
      case 135:
        return SensorReading.decode(readValue(buffer)!);
      case 136:
        return SimInfo.decode(readValue(buffer)!);
      case 137:
        return PairedDevice.decode(readValue(buffer)!);
      case 138:
        return BluetoothInfo.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class HardwareHostApi {
  /// Constructor for [HardwareHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  HardwareHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<DisplayInfo> display() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.HardwareHostApi.display$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as DisplayInfo;
  }

  Future<NetworkInfo> network() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.HardwareHostApi.network$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NetworkInfo;
  }

  Future<WifiInfo> wifi() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.HardwareHostApi.wifi$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as WifiInfo;
  }

  Future<List<CameraInfo>> cameras() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.HardwareHostApi.cameras$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<CameraInfo>();
  }

  Future<FeatureFlags> features() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.HardwareHostApi.features$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as FeatureFlags;
  }

  /// One reading, taken against the previous call.
  ///
  /// The first call after a cold start returns zero rates and real totals, since
  /// there is nothing to subtract from yet.
  Future<ThroughputSample> throughput() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.HardwareHostApi.throughput$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as ThroughputSample;
  }

  /// Starts listening to a small set of sensors.
  ///
  /// ─── EXPLICIT START AND STOP, NOT A STANDING SUBSCRIPTION ────────────────
  ///
  /// A registered SensorEventListener wakes the CPU at whatever rate it asked
  /// for, whether or not anything is looking. Tying registration to a screen
  /// being open is the difference between a page that costs nothing when closed
  /// and a background drain nobody attributes to this app.
  Future<void> startSensors(List<String> types) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.HardwareHostApi.startSensors$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[types],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> stopSensors() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.HardwareHostApi.stopSensors$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// The latest value from each started sensor.
  ///
  /// Polled rather than pushed. A sensor at its default rate fires far more
  /// often than a screen refreshes, and forwarding every event over a channel
  /// would spend more time in serialisation than in the reading.
  Future<List<SensorReading>> sensorValues() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.HardwareHostApi.sensorValues$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<SensorReading>();
  }

  /// Every SIM the phone can see, by slot.
  Future<List<SimInfo>> sims() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.HardwareHostApi.sims$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<SimInfo>();
  }

  Future<BluetoothInfo> bluetooth() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.HardwareHostApi.bluetooth$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as BluetoothInfo;
  }

  /// Plays a steady tone through one or both speakers.
  ///
  /// ─── GENERATED, NOT A BUNDLED FILE ───────────────────────────────────────
  ///
  /// A sine wave written straight into an AudioTrack. An asset would be a few
  /// hundred kilobytes in the APK for a sound the phone can compute, and a
  /// plugin would be a dependency for sixty lines of Kotlin.
  ///
  /// [channel] is "left", "right" or "both". Separate channels are the whole
  /// point: a phone with one dead speaker sounds fine on "both".
  Future<void> playTone(double hertz, int milliseconds, String channel) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.HardwareHostApi.playTone$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[hertz, milliseconds, channel],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> stopTone() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.HardwareHostApi.stopTone$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// [pattern] is "short", "long" or "double".
  Future<bool> vibrate(String pattern) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.HardwareHostApi.vibrate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[pattern],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Opens the system dialog for nearby Bluetooth devices.
  Future<bool> requestBluetooth() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.HardwareHostApi.requestBluetooth$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Opens the system dialog for phone state, which SIM details need.
  Future<bool> requestPhoneState() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.HardwareHostApi.requestPhoneState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Opens the system dialog for fine location.
  Future<bool> requestLocation() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.HardwareHostApi.requestLocation$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }
}
