// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// The primary shared volume. Codec 129.
class VolumeInfo {
  VolumeInfo({
    required this.totalBytes,
    required this.freeBytes,
    required this.usedBytes,
  });

  /// From StatFs on the data partition.
  ///
  /// NOT the number on the box. A 256 GB phone reports around 234 GB usable
  /// after the filesystem, the system image and the vendor partition take their
  /// share, and a user comparing against Settings must see the same figure we
  /// do, which is this one.
  int totalBytes;

  int freeBytes;

  /// total minus free. Includes the OS and every app's private data, so it is
  /// always larger than the sum of what the categories below can see.
  int usedBytes;

  List<Object?> _toList() {
    return <Object?>[totalBytes, freeBytes, usedBytes];
  }

  Object encode() {
    return _toList();
  }

  static VolumeInfo decode(Object result) {
    result as List<Object?>;
    return VolumeInfo(
      totalBytes: result[0]! as int,
      freeBytes: result[1]! as int,
      usedBytes: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VolumeInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(totalBytes, other.totalBytes) &&
        _deepEquals(freeBytes, other.freeBytes) &&
        _deepEquals(usedBytes, other.usedBytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VolumeInfo(totalBytes: $totalBytes, freeBytes: $freeBytes, usedBytes: $usedBytes)';
  }
}

/// One media kind. Codec 130.
class KindUsage {
  KindUsage({
    required this.kind,
    required this.itemCount,
    required this.totalBytes,
  });

  /// "image" | "video" | "audio" | "document" | "other". A String, because an
  /// enum here would renumber the whole schema.
  String kind;

  int itemCount;

  int totalBytes;

  List<Object?> _toList() {
    return <Object?>[kind, itemCount, totalBytes];
  }

  Object encode() {
    return _toList();
  }

  static KindUsage decode(Object result) {
    result as List<Object?>;
    return KindUsage(
      kind: result[0]! as String,
      itemCount: result[1]! as int,
      totalBytes: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KindUsage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) &&
        _deepEquals(itemCount, other.itemCount) &&
        _deepEquals(totalBytes, other.totalBytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KindUsage(kind: $kind, itemCount: $itemCount, totalBytes: $totalBytes)';
  }
}

/// One folder, as MediaStore reports it. Codec 131.
class FolderUsage {
  FolderUsage({
    required this.path,
    required this.label,
    required this.itemCount,
    required this.totalBytes,
  });

  /// The RELATIVE_PATH value, for example "DCIM/Camera/".
  String path;

  /// The last meaningful segment, for display.
  String label;

  int itemCount;

  int totalBytes;

  List<Object?> _toList() {
    return <Object?>[path, label, itemCount, totalBytes];
  }

  Object encode() {
    return _toList();
  }

  static FolderUsage decode(Object result) {
    result as List<Object?>;
    return FolderUsage(
      path: result[0]! as String,
      label: result[1]! as String,
      itemCount: result[2]! as int,
      totalBytes: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! FolderUsage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(path, other.path) &&
        _deepEquals(label, other.label) &&
        _deepEquals(itemCount, other.itemCount) &&
        _deepEquals(totalBytes, other.totalBytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'FolderUsage(path: $path, label: $label, itemCount: $itemCount, totalBytes: $totalBytes)';
  }
}

/// One year, for the age histogram. Codec 132.
class AgeBucket {
  AgeBucket({
    required this.year,
    required this.itemCount,
    required this.totalBytes,
  });

  int year;

  int itemCount;

  int totalBytes;

  List<Object?> _toList() {
    return <Object?>[year, itemCount, totalBytes];
  }

  Object encode() {
    return _toList();
  }

  static AgeBucket decode(Object result) {
    result as List<Object?>;
    return AgeBucket(
      year: result[0]! as int,
      itemCount: result[1]! as int,
      totalBytes: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AgeBucket || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(year, other.year) &&
        _deepEquals(itemCount, other.itemCount) &&
        _deepEquals(totalBytes, other.totalBytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AgeBucket(year: $year, itemCount: $itemCount, totalBytes: $totalBytes)';
  }
}

/// A file that is still on the device. Codec 133.
class StorageFile {
  StorageFile({
    required this.fileId,
    required this.name,
    required this.kind,
    required this.sizeBytes,
    this.relativePath,
    this.mimeType,
    this.dateModifiedMillis,
    this.durationMillis,
  });

  /// Opaque handle. Dart must never parse it.
  String fileId;

  String name;

  String kind;

  int sizeBytes;

  String? relativePath;

  String? mimeType;

  int? dateModifiedMillis;

  int? durationMillis;

  List<Object?> _toList() {
    return <Object?>[
      fileId,
      name,
      kind,
      sizeBytes,
      relativePath,
      mimeType,
      dateModifiedMillis,
      durationMillis,
    ];
  }

  Object encode() {
    return _toList();
  }

  static StorageFile decode(Object result) {
    result as List<Object?>;
    return StorageFile(
      fileId: result[0]! as String,
      name: result[1]! as String,
      kind: result[2]! as String,
      sizeBytes: result[3]! as int,
      relativePath: result[4] as String?,
      mimeType: result[5] as String?,
      dateModifiedMillis: result[6] as int?,
      durationMillis: result[7] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! StorageFile || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(fileId, other.fileId) &&
        _deepEquals(name, other.name) &&
        _deepEquals(kind, other.kind) &&
        _deepEquals(sizeBytes, other.sizeBytes) &&
        _deepEquals(relativePath, other.relativePath) &&
        _deepEquals(mimeType, other.mimeType) &&
        _deepEquals(dateModifiedMillis, other.dateModifiedMillis) &&
        _deepEquals(durationMillis, other.durationMillis);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'StorageFile(fileId: $fileId, name: $name, kind: $kind, sizeBytes: $sizeBytes, relativePath: $relativePath, mimeType: $mimeType, dateModifiedMillis: $dateModifiedMillis, durationMillis: $durationMillis)';
  }
}

/// Everything the Storage tab draws on open. Codec 134.
class StorageOverview {
  StorageOverview({
    required this.volume,
    required this.kinds,
    required this.folders,
    required this.ages,
    required this.indexedBytes,
    required this.indexedCount,
    required this.complete,
  });

  VolumeInfo volume;

  List<KindUsage> kinds;

  /// Largest first, capped natively. A phone can have hundreds of folders and a
  /// treemap of hundreds of rectangles is a texture, not information.
  List<FolderUsage> folders;

  List<AgeBucket> ages;

  /// The total this overview can actually account for.
  ///
  /// ALWAYS LESS THAN [VolumeInfo.usedBytes], and the gap is not an error. It is
  /// the OS, app code, and every app's private directory, none of which
  /// MediaStore indexes and none of which any app can enumerate. The UI shows
  /// the gap as its own segment rather than quietly inflating a category, which
  /// is what a cleaner app does to make its numbers look bigger.
  int indexedBytes;

  int indexedCount;

  /// False when the index was truncated for time. The figures are then a floor.
  bool complete;

  List<Object?> _toList() {
    return <Object?>[
      volume,
      kinds,
      folders,
      ages,
      indexedBytes,
      indexedCount,
      complete,
    ];
  }

  Object encode() {
    return _toList();
  }

  static StorageOverview decode(Object result) {
    result as List<Object?>;
    return StorageOverview(
      volume: result[0]! as VolumeInfo,
      kinds: (result[1]! as List<Object?>).cast<KindUsage>(),
      folders: (result[2]! as List<Object?>).cast<FolderUsage>(),
      ages: (result[3]! as List<Object?>).cast<AgeBucket>(),
      indexedBytes: result[4]! as int,
      indexedCount: result[5]! as int,
      complete: result[6]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! StorageOverview || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(volume, other.volume) &&
        _deepEquals(kinds, other.kinds) &&
        _deepEquals(folders, other.folders) &&
        _deepEquals(ages, other.ages) &&
        _deepEquals(indexedBytes, other.indexedBytes) &&
        _deepEquals(indexedCount, other.indexedCount) &&
        _deepEquals(complete, other.complete);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'StorageOverview(volume: $volume, kinds: $kinds, folders: $folders, ages: $ages, indexedBytes: $indexedBytes, indexedCount: $indexedCount, complete: $complete)';
  }
}

/// A filter. Codec 135.
class StorageQuerySpec {
  StorageQuerySpec({
    required this.kinds,
    required this.limit,
    this.minBytes,
    this.olderThanDays,
    this.folderPrefix,
    this.nameContains,
    required this.sort,
  });

  /// Empty means every kind.
  List<String> kinds;

  int limit;

  int? minBytes;

  int? olderThanDays;

  String? folderPrefix;

  String? nameContains;

  /// "newest" | "oldest" | "largest" | "smallest" | "name"
  ///
  /// SORTED NATIVELY, and it has to be. The query returns at most [limit] rows,
  /// so ordering in Dart afterwards would sort the page rather than the library:
  /// asking for smallest first would hand back the smallest of the 400 largest,
  /// which is wrong in a way nobody notices until they trust it.
  ///
  /// A String rather than an enum, matching every other field here: an enum
  /// numbers before classes and adding a sixth order would renumber every class
  /// in the schema.
  String sort;

  List<Object?> _toList() {
    return <Object?>[
      kinds,
      limit,
      minBytes,
      olderThanDays,
      folderPrefix,
      nameContains,
      sort,
    ];
  }

  Object encode() {
    return _toList();
  }

  static StorageQuerySpec decode(Object result) {
    result as List<Object?>;
    return StorageQuerySpec(
      kinds: (result[0]! as List<Object?>).cast<String>(),
      limit: result[1]! as int,
      minBytes: result[2] as int?,
      olderThanDays: result[3] as int?,
      folderPrefix: result[4] as String?,
      nameContains: result[5] as String?,
      sort: result[6]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! StorageQuerySpec || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kinds, other.kinds) &&
        _deepEquals(limit, other.limit) &&
        _deepEquals(minBytes, other.minBytes) &&
        _deepEquals(olderThanDays, other.olderThanDays) &&
        _deepEquals(folderPrefix, other.folderPrefix) &&
        _deepEquals(nameContains, other.nameContains) &&
        _deepEquals(sort, other.sort);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'StorageQuerySpec(kinds: $kinds, limit: $limit, minBytes: $minBytes, olderThanDays: $olderThanDays, folderPrefix: $folderPrefix, nameContains: $nameContains, sort: $sort)';
  }
}

/// Codec 136.
class StorageQueryResult {
  StorageQueryResult({
    required this.files,
    required this.matchCount,
    required this.matchBytes,
    required this.folders,
    required this.ages,
  });

  /// Capped by [StorageQuerySpec.limit]. [matchCount] is the real total, so the
  /// headline figure never lies just because the list was truncated.
  List<StorageFile> files;

  int matchCount;

  int matchBytes;

  /// Breakdown of the MATCH, not of the device. This is what makes a query an
  /// answer with a shape rather than a list.
  List<FolderUsage> folders;

  List<AgeBucket> ages;

  List<Object?> _toList() {
    return <Object?>[files, matchCount, matchBytes, folders, ages];
  }

  Object encode() {
    return _toList();
  }

  static StorageQueryResult decode(Object result) {
    result as List<Object?>;
    return StorageQueryResult(
      files: (result[0]! as List<Object?>).cast<StorageFile>(),
      matchCount: result[1]! as int,
      matchBytes: result[2]! as int,
      folders: (result[3]! as List<Object?>).cast<FolderUsage>(),
      ages: (result[4]! as List<Object?>).cast<AgeBucket>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! StorageQueryResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(files, other.files) &&
        _deepEquals(matchCount, other.matchCount) &&
        _deepEquals(matchBytes, other.matchBytes) &&
        _deepEquals(folders, other.folders) &&
        _deepEquals(ages, other.ages);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'StorageQueryResult(files: $files, matchCount: $matchCount, matchBytes: $matchBytes, folders: $folders, ages: $ages)';
  }
}

/// Codec 137.
class StorageOutcome {
  StorageOutcome({
    required this.fileId,
    required this.status,
    required this.detail,
  });

  String fileId;

  /// "deleted" | "trashed" | "needsConsent" | "notFound" | "denied" | "failed"
  ///
  /// `trashed` is distinct from `deleted` on purpose: the default action moves a
  /// file to the OS trash where it is recoverable for thirty days, and telling
  /// the user it was deleted when it was not would be the same overclaim this
  /// app refuses to make in the other direction.
  String status;

  String detail;

  List<Object?> _toList() {
    return <Object?>[fileId, status, detail];
  }

  Object encode() {
    return _toList();
  }

  static StorageOutcome decode(Object result) {
    result as List<Object?>;
    return StorageOutcome(
      fileId: result[0]! as String,
      status: result[1]! as String,
      detail: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! StorageOutcome || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(fileId, other.fileId) &&
        _deepEquals(status, other.status) &&
        _deepEquals(detail, other.detail);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'StorageOutcome(fileId: $fileId, status: $status, detail: $detail)';
  }
}

/// One thing inside a folder. Codec 138.
///
/// Appended last, so nothing before it renumbers.
///
/// ─── THIS IS NOT StorageFile ─────────────────────────────────────────────────
///
/// StorageFile is a MediaStore row: indexed, with a kind and a media id, and
/// reachable by every other method here. This is what is actually on disk, which
/// is a different and larger set. MediaStore never saw the zip a file manager
/// dropped into Download, and it has no idea that Android/data exists.
///
/// Keeping them apart is the point. A browser that could only show indexed files
/// would teach a false picture of the filesystem, which is the one thing this
/// screen exists not to do.
class DirEntry {
  DirEntry({
    required this.path,
    required this.name,
    required this.isDirectory,
    required this.sizeBytes,
    required this.modifiedMillis,
    this.childCount,
    required this.readable,
    required this.hidden,
  });

  String path;

  String name;

  bool isDirectory;

  /// Zero for a directory. Summing a tree means walking it, and a browser that
  /// stalled on every folder to total its contents would be unusable on a
  /// phone.
  int sizeBytes;

  int modifiedMillis;

  /// How many things are directly inside, or null when it could not be read.
  ///
  /// Null is meaningful here and is not the same as zero: an empty folder and a
  /// folder the system refuses to open look identical without it.
  int? childCount;

  /// False for the folders Android will not open, chiefly Android/data and
  /// Android/obb from Android 11 onward.
  ///
  /// Shown rather than hidden. A person who cannot see the locked door does not
  /// learn that it is locked, and this is the same folder that makes deleted
  /// chat messages unrecoverable.
  bool readable;

  /// Starts with a dot. Listed, but behind a toggle, because a browser that
  /// silently omits things teaches the wrong shape of the filesystem.
  bool hidden;

  List<Object?> _toList() {
    return <Object?>[
      path,
      name,
      isDirectory,
      sizeBytes,
      modifiedMillis,
      childCount,
      readable,
      hidden,
    ];
  }

  Object encode() {
    return _toList();
  }

  static DirEntry decode(Object result) {
    result as List<Object?>;
    return DirEntry(
      path: result[0]! as String,
      name: result[1]! as String,
      isDirectory: result[2]! as bool,
      sizeBytes: result[3]! as int,
      modifiedMillis: result[4]! as int,
      childCount: result[5] as int?,
      readable: result[6]! as bool,
      hidden: result[7]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DirEntry || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(path, other.path) &&
        _deepEquals(name, other.name) &&
        _deepEquals(isDirectory, other.isDirectory) &&
        _deepEquals(sizeBytes, other.sizeBytes) &&
        _deepEquals(modifiedMillis, other.modifiedMillis) &&
        _deepEquals(childCount, other.childCount) &&
        _deepEquals(readable, other.readable) &&
        _deepEquals(hidden, other.hidden);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DirEntry(path: $path, name: $name, isDirectory: $isDirectory, sizeBytes: $sizeBytes, modifiedMillis: $modifiedMillis, childCount: $childCount, readable: $readable, hidden: $hidden)';
  }
}

/// A mounted volume. Codec 139.
///
/// ─── NOT VolumeInfo ──────────────────────────────────────────────────────────
///
/// VolumeInfo is three numbers about the volume an overview describes. This is
/// a volume the phone has, with a name and a path, so it can be listed and
/// opened. A phone with an SD card has two of these and one overview.
class VolumeEntry {
  VolumeEntry({
    required this.id,
    required this.label,
    this.path,
    required this.totalBytes,
    required this.freeBytes,
    required this.removable,
    required this.primary,
  });

  String id;

  /// What the system calls it. "SanDisk SD card" rather than a mount point,
  /// because the mount point is a different string on every device.
  String label;

  /// Null when the volume is mounted somewhere this app cannot reach, which
  /// happens on some OEM builds for USB drives.
  String? path;

  int totalBytes;

  int freeBytes;

  bool removable;

  /// Internal storage. There is exactly one, and it is the one the overview
  /// already describes.
  bool primary;

  List<Object?> _toList() {
    return <Object?>[
      id,
      label,
      path,
      totalBytes,
      freeBytes,
      removable,
      primary,
    ];
  }

  Object encode() {
    return _toList();
  }

  static VolumeEntry decode(Object result) {
    result as List<Object?>;
    return VolumeEntry(
      id: result[0]! as String,
      label: result[1]! as String,
      path: result[2] as String?,
      totalBytes: result[3]! as int,
      freeBytes: result[4]! as int,
      removable: result[5]! as bool,
      primary: result[6]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VolumeEntry || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(label, other.label) &&
        _deepEquals(path, other.path) &&
        _deepEquals(totalBytes, other.totalBytes) &&
        _deepEquals(freeBytes, other.freeBytes) &&
        _deepEquals(removable, other.removable) &&
        _deepEquals(primary, other.primary);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VolumeEntry(id: $id, label: $label, path: $path, totalBytes: $totalBytes, freeBytes: $freeBytes, removable: $removable, primary: $primary)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();

  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is VolumeInfo) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is KindUsage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is FolderUsage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is AgeBucket) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is StorageFile) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is StorageOverview) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is StorageQuerySpec) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is StorageQueryResult) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is StorageOutcome) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is DirEntry) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is VolumeEntry) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return VolumeInfo.decode(readValue(buffer)!);
      case 130:
        return KindUsage.decode(readValue(buffer)!);
      case 131:
        return FolderUsage.decode(readValue(buffer)!);
      case 132:
        return AgeBucket.decode(readValue(buffer)!);
      case 133:
        return StorageFile.decode(readValue(buffer)!);
      case 134:
        return StorageOverview.decode(readValue(buffer)!);
      case 135:
        return StorageQuerySpec.decode(readValue(buffer)!);
      case 136:
        return StorageQueryResult.decode(readValue(buffer)!);
      case 137:
        return StorageOutcome.decode(readValue(buffer)!);
      case 138:
        return DirEntry.decode(readValue(buffer)!);
      case 139:
        return VolumeEntry.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class StorageHostApi {
  /// Constructor for [StorageHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  StorageHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Volume stats plus the MediaStore aggregate. One pass, no directory walk.
  Future<StorageOverview> overview() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.StorageHostApi.overview$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as StorageOverview;
  }

  Future<StorageQueryResult> query(StorageQuerySpec spec) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.StorageHostApi.query$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[spec],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as StorageQueryResult;
  }

  /// JPEG preview bytes, downscaled natively. Same reasoning as the recovery
  /// thumbnail: Flutter cannot load a content URI, and shipping full size
  /// bitmaps across the channel is how a grid runs a phone out of memory.
  ///
  /// [kind], [name] and [mimeType] are passed IN rather than looked up.
  ///
  /// Native has only the file id, which carries no type, so deciding how to
  /// draw a preview would mean a second MediaStore query per thumbnail: on a
  /// scrolling grid, one extra cursor per cell. Dart already holds all three on
  /// the StorageFile it is drawing, so handing them over costs nothing and the
  /// native side goes straight to the right renderer.
  ///
  /// Without this the call site hardcoded "image", which meant audio artwork
  /// and PDF first pages could never be reached however well they worked.
  Future<Uint8List?> thumbnail(
    String fileId,
    int maxPixels,
    String kind,
    String? name,
    String? mimeType,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.StorageHostApi.thumbnail$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[fileId, maxPixels, kind, name, mimeType],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as Uint8List?;
  }

  /// Moves files to the OS trash by default, where the user has thirty days to
  /// change their mind. [permanent] skips that.
  Future<List<StorageOutcome>> remove(
    List<String> fileIds,
    bool permanent,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.StorageHostApi.remove$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[fileIds, permanent],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<StorageOutcome>();
  }

  /// A playable content URI for this file, or null if it is no longer listed.
  ///
  /// The one thing video playback cannot be done without. VideoPlayerController
  /// takes a content URI and nothing else will do: Dart cannot open a
  /// MediaStore row by id, and the file path behind it is unreadable under
  /// scoped storage even when the row is perfectly readable.
  ///
  /// A STRING, not a typed URI, because Pigeon has no URI and because the same
  /// value is handed straight back to the platform for the external chooser.
  Future<String?> contentUri(String fileId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.StorageHostApi.contentUri$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[fileId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  /// Raw bytes, for the formats this app renders itself.
  ///
  /// Text and CSV, and nothing larger than [maxBytes]. Dart cannot read a
  /// content URI on its own, so the bytes have to cross the bridge, and a
  /// three hundred megabyte log decoded into a Dart string would take the app
  /// down on a phone that had every right to survive opening it.
  ///
  /// Returns null when the file is missing or larger than the cap. The caller
  /// distinguishes the two by checking the size it already has.
  Future<Uint8List?> readBytes(String fileId, int maxBytes) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.StorageHostApi.readBytes$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[fileId, maxBytes],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as Uint8List?;
  }

  /// Every mounted volume: internal, and any SD card or USB drive.
  ///
  /// From StorageManager rather than a guessed path. On a phone with an SD card
  /// the second volume has a different id on every device, and hardcoding
  /// /storage/sdcard1 was already wrong a decade ago.
  Future<List<VolumeEntry>> volumes() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.StorageHostApi.volumes$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<VolumeEntry>();
  }

  /// What is directly inside a folder.
  ///
  /// [path] null means the roots: internal storage, plus any SD card or USB
  /// volume currently mounted.
  ///
  /// One level only. A recursive walk is what makes file managers hang on a
  /// folder with forty thousand files in it, and nothing on this screen needs
  /// more than the level being looked at.
  Future<List<DirEntry>> listDirectory(String? path) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.StorageHostApi.listDirectory$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[path],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<DirEntry>();
  }

  /// Hands the file to whatever app can open it.
  ///
  /// For the formats with no credible in-app renderer, which on Android means
  /// office documents and anything proprietary. Returns false when nothing on
  /// the phone can handle the type, so the UI can say that instead of appearing
  /// to do nothing.
  ///
  /// Grants read permission on the URI for the duration of the target activity.
  /// Without that flag the chooser opens onto a permission error, which looks
  /// like a bug in this app rather than in the one that was launched.
  Future<bool> openExternally(String fileId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.g_recovery.StorageHostApi.openExternally$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[fileId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }
}
